### ISSUE TITLE
Crash on fedora 19

### ISSUE THREAD

**Issue by jdeisenberg** [zealdocs/zeal#164] opened 2014-06-25 06:25 UTC
Built on Fedora 19 for ARM (on a chromebook). I can download docsets; the left panel shows up fine, the actual documentation does not appear. When I start zeal, I get this message:

QObject::connect: signal not found in QTreeView

And when I quit after attempting to view a page, I get this:

*** Error in `zeal': munmap_chunk(): invalid pointer: 0x4c000000 ***
======= Backtrace: =========
/lib/libc.so.6[0x4845aa50]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
zeal[0x23af8]
======= Memory map: ========
00008000-00081000 r-xp 00000000 b3:35 143724     /usr/bin/zeal
00088000-0008a000 r--p 00078000 b3:35 143724     /usr/bin/zeal
0008a000-0008c000 rw-p 0007a000 b3:35 143724     /usr/bin/zeal
0090c000-00d5e000 rw-p 00000000 00:00 0          [heap]
41000000-413ae000 r-xp 00000000 b3:35 137497     /usr/lib/libQt5Core.so.5.2.1
413ae000-413b6000 ---p 003ae000 b3:35 137497     /usr/lib/libQt5Core.so.5.2.1
413b6000-413ba000 r--p 003ae000 b3:35 137497     /usr/lib/libQt5Core.so.5.2.1
413ba000-413bc000 rw-p 003b2000 b3:35 137497     /usr/lib/libQt5Core.so.5.2.1
413bc000-413bd000 rw-p 00000000 00:00 0 
413c0000-4140f000 r-xp 00000000 b3:35 161523     /usr/lib/libpcre16.so.0.2.0
4140f000-41417000 ---p 0004f000 b3:35 161523     /usr/lib/libpcre16.so.0.2.0
41417000-41418000 r--p 0004f000 b3:35 161523     /usr/lib/libpcre16.so.0.2.0
41418000-41419000 rw-p 00050000 b3:35 161523     /usr/lib/libpcre16.so.0.2.0
41420000-41734000 r-xp 00000000 b3:35 161669     /usr/lib/libQt5Qml.so.5.2.1
41734000-4173c000 ---p 00314000 b3:35 161669     /usr/lib/libQt5Qml.so.5.2.1
4173c000-41746000 r--p 00314000 b3:35 161669     /usr/lib/libQt5Qml.so.5.2.1
41746000-41749000 rw-p 0031e000 b3:35 161669     /usr/lib/libQt5Qml.so.5.2.1
41749000-4174a000 rw-p 00000000 00:00 0 
41750000-4185d000 r-xp 00000000 b3:35 161810     /usr/lib/libQt5Network.so.5.2.1
4185d000-41864000 ---p 0010d000 b3:35 161810     /usr/lib/libQt5Network.so.5.2.1
41864000-41867000 r--p 0010c000 b3:35 161810     /usr/lib/libQt5Network.so.5.2.1
41867000-41869000 rw-p 0010f000 b3:35 161810     /usr/lib/libQt5Network.so.5.2.1
41870000-41be3000 r-xp 00000000 b3:35 161663     /usr/lib/libQt5Gui.so.5.2.1
41be3000-41beb000 ---p 00373000 b3:35 161663     /usr/lib/libQt5Gui.so.5.2.1
41beb000-41bf5000 r--p 00373000 b3:35 161663     /usr/lib/libQt5Gui.so.5.2.1
41bf5000-41bf9000 rw-p 0037d000 b3:35 161663     /usr/lib/libQt5Gui.so.5.2.1
41c00000-41e9d000 r-xp 00000000 b3:35 161852     /usr/lib/libQt5Quick.so.5.2.1
41e9d000-41ea5000 ---p 0029d000 b3:35 161852     /usr/lib/libQt5Quick.so.5.2.1
41ea5000-41eb3000 r--p 0029d000 b3:35 161852     /usr/lib/libQt5Quick.so.5.2.1
41eb3000-41eb6000 rw-p 002ab000 b3:35 161852     /usr/lib/libQt5Quick.so.5.2.1
41eb6000-41eb7000 rw-p 00000000 00:00 0 
41ec0000-4239d000 r-xp 00000000 b3:35 161801     /usr/lib/libQt5Widgets.so.5.2.1
4239d000-423a5000 ---p 004dd000 b3:35 161801     /usr/lib/libQt5Widgets.so.5.2.1
423a5000-423b7000 r--p 004dd000 b3:35 161801     /usr/lib/libQt5Widgets.so.5.2.1
423b7000-423bb000 rw-p 004ef000 b3:35 161801     /usr/lib/libQt5Widgets.so.5.2.1
423bb000-423bc000 rw-p 00000000 00:00 0 
423c0000-43ccf000 r-xp 00000000 b3:35 161672     /usr/lib/libQt5WebKit.so.5.2.1
43ccf000-43cd7000 ---p 0190f000 b3:35 161672     /usr/lib/libQt5WebKit.so.5.2.1
43cd7000-43d9c000 r--p 0190f000 b3:35 161672     /usr/lib/libQt5WebKit.so.5.2.1
43d9c000-43dad000 rw-p 019d4000 b3:35 161672     /usr/lib/libQt5WebKit.so.5.2.1
43dad000-43dc3000 rw-p 00000000 00:00 0 
43dc8000-43ea1000 r-xp 00000000 b3:35 161861     /usr/lib/libgstreamer-1.0.so.0.6.0
43ea1000-43ea8000 ---p 000d9000 b3:35 161861     /usr/lib/libgstreamer-1.0.so.0.6.0
43ea8000-43eab000 r--p 000d8000 b3:35 161861     /usr/lib/libgstreamer-1.0.so.0.6.0
43eab000-43ead000 rw-p 000db000 b3:35 161861     /usr/lib/libgstreamer-1.0.so.0.6.0
43eb0000-43efe000 r-xp 00000000 b3:35 159120     /usr/lib/libgstbase-1.0.so.0.6.0
43efe000-43f05000 ---p 0004e000 b3:35 159120     /usr/lib/libgstbase-1.0.so.0.6.0
43f05000-43f06000 r--p 0004d000 b3:35 159120     /usr/lib/libgstbase-1.0.so.0.6.0
43f06000-43f07000 rw-p 0004e000 b3:35 159120     /usr/lib/libgstbase-1.0.so.0.6.0
43f10000-43f53000 r-xp 00000000 b3:35 159121     /usr/lib/libgstaudio-1.0.so.0.6.0
43f53000-43f5a000 ---p 00043000 b3:35 159121     /usr/lib/libgstaudio-1.0.so.0.6.0
43f5a000-43f5b000 r--p 00042000 b3:35 159121     /usr/lib/libgstaudio-1.0.so.0.6.0
43f5b000-43f5c000 rw-p 00043000 b3:35 159121     /usr/lib/libgstaudio-1.0.so.0.6.0
43f60000-43f96000 r-xp 00000000 b3:35 140762     /usr/lib/libgstvideo-1.0.so.0.6.0
43f96000-43f9d000 ---p 00036000 b3:35 140762     /usr/lib/libgstvideo-1.0.so.0.6.0
43f9d000-43f9e000 r--p 00035000 b3:35 140762     /usr/lib/libgstvideo-1.0.so.0.6.0
43f9e000-43fa1000 rw-p 00036000 b3:35 140762     /usr/lib/libgstvideo-1.0.so.0.6.0
43fa8000-43fd9000 r-xp 00000000 b3:35 159123     /usr/lib/libQt5Sql.so.5.2.1
43fd9000-43fe0000 ---p 00031000 b3:35 159123     /usr/lib/libQt5Sql.so.5.2.1
43fe0000-43fe1000 r--p 00030000 b3:35 159123     /usr/lib/libQt5Sql.so.5.2.1
43fe1000-43fe2000 rw-p 00031000 b3:35 159123     /usr/lib/libQt5Sql.so.5.2.1
43fe8000-4401a000 r-xp 00000000 b3:35 137961     /usr/lib/libgsttag-1.0.so.0.6.0
4401a000-44021000 ---p 00032000 b3:35 137961     /usr/lib/libgsttag-1.0.so.0.6.0
44021000-44022000 r--p 00031000 b3:35 137961     /usr/lib/libgsttag-1.0.so.0.6.0
44022000-44023000 rw-p 00032000 b3:35 137961     /usr/lib/libgsttag-1.0.so.0.6.0
44028000-44047000 r-xp 00000000 b3:35 159122     /usr/lib/libgstpbutils-1.0.so.0.6.0
44047000-4404e000 ---p 0001f000 b3:35 159122     /usr/lib/libgstpbutils-1.0.so.0.6.0
4404e000-4404f000 r--p 0001e000 b3:35 159122     /usr/lib/libgstpbutils-1.0.so.0.6.0
4404f000-44050000 rw-p 0001f000 b3:35 159122     /usr/lib/libgstpbutils-1.0.so.0.6.0
44058000-44062000 r-xp 00000000 b3:35 161678     /usr/lib/libgstapp-1.0.so.0.6.0
44062000-44069000 ---p 0000a000 b3:35 161678     /usr/lib/libgstapp-1.0.so.0.6.0
44069000-4406a000 r--p 00009000 b3:35 161678     /usr/lib/libgstapp-1.0.so.0.6.0
4406a000-4406b000 rw-p 0000a000 b3:35 161678     /usr/lib/libgstapp-1.0.so.0.6.0
44070000-440bd000 r-xp 00000000 b3:35 161889     /usr/lib/libQt5OpenGL.so.5.2.1
440bd000-440c4000 ---p 0004d000 b3:35 161889     /usr/lib/libQt5OpenGL.so.5.2.1
440c4000-440c5000 r--p 0004c000 b3:35 161889     /usr/lib/libQt5OpenGL.so.5.2.1
440c5000-440c7000 rw-p 0004d000 b3:35 161889     /usr/lib/libQt5OpenGL.so.5.2.1
440d0000-4411f000 r-xp 00000000 b3:35 161568     /usr/lib/libQt5PrintSupport.so.5.2.1
4411f000-44127000 ---p 0004f000 b3:35 161568     /usr/lib/libQt5PrintSupport.so.5.2.1
44127000-44129000 r--p 0004f000 b3:35 161568     /usr/lib/libQt5PrintSupport.so.5.2.1
44129000-4412a000 rw-p 00051000 b3:35 161568     /usr/lib/libQt5PrintSupport.so.5.2.1
44130000-4415f000 r-xp 00000000 b3:35 161804     /usr/lib/libQt5WebKitWidgets.so.5.2.1
4415f000-44166000 ---p 0002f000 b3:35 161804     /usr/lib/libQt5WebKitWidgets.so.5.2.1
44166000-44167000 r--p 0002e000 b3:35 161804     /usr/lib/libQt5WebKitWidgets.so.5.2.1
44167000-44169000 rw-p 0002f000 b3:35 161804     /usr/lib/libQt5WebKitWidgets.so.5.2.1
483b8000-483d6000 r-xp 00000000 b3:35 158828     /usr/lib/ld-2.17.so
483de000-483df000 r--p 0001e000 b3:35 158828     /usr/lib/ld-2.17.so
483df000-483e0000 rw-p 0001f000 b3:35 158828     /usr/lib/ld-2.17.so
483e8000-48527000 r-xp 00000000 b3:35 158829     /usr/lib/libc-2.17.so
48527000-4852e000 ---p 0013f000 b3:35 158829     /usr/lib/libc-2.17.so
4852e000-48530000 r--p 0013e000 b3:35 158829     /usr/lib/libc-2.17.so
48530000-48531000 rw-p 00140000 b3:35 158829     /usr/lib/libc-2.17.so
48531000-48534000 rw-p 00000000 00:00 0 
48538000-48556000 r-xp 00000000 b3:35 158831     /usr/lib/libgcc_s-4.8.2-20131212.so.1
48556000-4855d000 ---p 0001e000 b3:35 158831     /usr/lib/libgcc_s-4.8.2-20131212.so.1
4855d000-4855e000 rw-p 0001d000 b3:35 158831     /usr/lib/libgcc_s-4.8.2-20131212.so.1
48560000-48574000 r-xp 00000000 b3:35 158830     /usr/lib/libpthread-2.17.so
48574000-4857b000 ---p 00014000 b3:35 158830     /usr/lib/libpthread-2.17.so
4857b000-4857c000 r--p 00013000 b3:35 158830     /usr/lib/libpthread-2.17.so
4857c000-4857d000 rw-p 00014000 b3:35 158830     /usr/lib/libpthread-2.17.so
4857d000-4857f000 rw-p 00000000 00:00 0 
48588000-4858c000 r-xp 00000000 b3:35 158833     /usr/lib/libdl-2.17.so
4858c000-48593000 ---p 00004000 b3:35 158833     /usr/lib/libdl-2.17.so
48593000-48594000 r--p 00003000 b3:35 158833     /usr/lib/libdl-2.17.so
48594000-48595000 rw-p 00004000 b3:35 158833     /usr/lib/libdl-2.17.so
48598000-485ab000 r-xp 00000000 b3:35 158832     /usr/lib/libz.so.1.2.7
485ab000-485b2000 ---p 00013000 b3:35 158832     /usr/lib/libz.so.1.2.7
485b2000-485b3000 r--p 00012000 b3:35 158832     /usr/lib/libz.so.1.2.7
485b3000-485b4000 rw-p 00013000 b3:35 158832     /usr/lib/libz.so.1.2.7
485b8000-48623000 r-xp 00000000 b3:35 158837     /usr/lib/libm-2.17.so
48623000-4862a000 ---p 0006b000 b3:35 158837     /usr/lib/libm-2.17.so
4862a000-4862b000 r--p 0006a000 b3:35 158837     /usr/lib/libm-2.17.so
4862b000-4862c000 rw-p 0006b000 b3:35 158837     /usr/lib/libm-2.17.so
48630000-48636000 r-xp 00000000 b3:35 158836     /usr/lib/librt-2.17.so
48636000-4863d000 ---p 00006000 b3:35 158836     /usr/lib/librt-2.17.so
4863d000-4863e000 r--p 00005000 b3:35 158836     /usr/lib/librt-2.17.so
4863e000-4863f000 rw-p 00006000 b3:35 158836     /usr/lib/librt-2.17.so
48648000-4869f000 r-xp 00000000 b3:35 158841     /usr/lib/libpcre.so.1.2.0
4869f000-486a6000 ---p 00057000 b3:35 158841     /usr/lib/libpcre.so.1.2.0
486a6000-486a7000 r--p 00056000 b3:35 158841     /usr/lib/libpcre.so.1.2.0
486a7000-486a8000 rw-p 00057000 b3:35 158841     /usr/lib/libpcre.so.1.2.0
486b0000-486cc000 r-xp 00000000 b3:35 158842     /usr/lib/libselinux.so.1
486cc000-486d3000 ---p 0001c000 b3:35 158842     /usr/lib/libselinux.so.1
486d3000-486d4000 r--p 0001b000 b3:35 158842     /usr/lib/libselinux.so.1
486d4000-486d5000 rw-p 0001c000 b3:35 158842     /usr/lib/libselinux.so.1
486d5000-486d6000 rw-p 00000000 00:00 0 
486d8000-486ef000 r-xp 00000000 b3:35 158840     /usr/lib/libresolv-2.17.so
486ef000-486f7000 ---p 00017000 b3:35 158840     /usr/lib/libresolv-2.17.so
486f7000-486f8000 r--p 00017000 b3:35 158840     /usr/lib/libresolv-2.17.so
486f8000-486f9000 rw-p 00018000 b3:35 158840     /usr/lib/libresolv-2.17.so
486f9000-486fb000 rw-p 00000000 00:00 0 
48700000-4880a000 r-xp 00000000 b3:35 158834     /usr/lib/libglib-2.0.so.0.3600.4
4880a000-48811000 ---p 0010a000 b3:35 158834     /usr/lib/libglib-2.0.so.0.3600.4
48811000-48812000 r--p 00109000 b3:35 158834     /usr/lib/libglib-2.0.so.0.3600.4
48812000-48813000 rw-p 0010a000 b3:35 158834     /usr/lib/libglib-2.0.so.0.3600.4
48818000-4885c000 r-xp 00000000 b3:35 158870     /usr/lib/libgobject-2.0.so.0.3600.4
4885c000-48864000 ---p 00044000 b3:35 158870     /usr/lib/libgobject-2.0.so.0.3600.4
48864000-48865000 r--p 00044000 b3:35 158870     /usr/lib/libgobject-2.0.so.0.3600.4
48865000-48866000 rw-p 00045000 b3:35 158870     /usr/lib/libgobject-2.0.so.0.3600.4
48868000-4886e000 r-xp 00000000 b3:35 158869     /usr/lib/libffi.so.6.0.1
4886e000-48875000 ---p 00006000 b3:35 158869     /usr/lib/libffi.so.6.0.1
48875000-48876000 r--p 00005000 b3:35 158869     /usr/lib/libffi.so.6.0.1Aborted

**Comment by trollixx** [comment] 2015-01-30 02:37
The report is quite old, and the backtrace has no useful information. I am closing the issue, but please reopen if the problem is still there. In a such case a stack trace of debug build would be helpful.

**Closed by trollixx** 2015-01-30 02:37 UTC
