### ISSUE TITLE
Get installed docsets from the command line

### ISSUE THREAD

**Issue by Miguellissimo** [zealdocs/zeal#368] opened 2015-07-08 16:56 UTC
Id would be nice to get a list of installed docsets from zeal via the command line.
For example:
```bash
$ zeal --installed-docsets
python2.7 python3 html
```  
This can be useful for IDE/texteditor plugins to limit a requested search to a specific language and the installed docsets

**Comment by trollixx** [comment] 2015-07-26 03:27
Hi. What is the exact use case you have? IDE integration should be done via `dash-plugin:` protocol, and there's no need to check whether or not a specific docset is installed.

**Comment by KabbAmine** [comment] 2015-07-26 10:28
@trollixx With my [vim plugin](https://github.com/kabbamine/zeavim.vim) for example, some commands use docset name completion, those names are extracted directly from the docset's directory (The one specified in zeal's options).
So in this case, it will be quicker to get the installed docset from a command line.

**Comment by Miguellissimo** [comment] 2015-07-26 13:23
@trollixx Lets assume that I am working on a python file inside a texteditor. To make a request to zeal from a texteditor or IDE, it would end up in a call like (in this example I use the find function):
```bash
$ zeal python:find
```   
which is not working, because there is no docset named python, only python 2 or python 3, depending which one is installed (maybe even both). For a zeal plugin it would be useful to make a request first to gather the information which language docset version is installed and make the actual request based on that information.

**Comment by trollixx** [comment] 2015-07-26 18:29
Ah, I see the problem. It's the same one as #383. I am working on it right now, and Zeal will provide search compatible to Dash.

`python:` already works in unreleased version (if you'd build it from the Git), because the problem is caused by my mistake in 0.1.1 (see #333).

IDE plugins should only rely on the context (file extension, included libraries, etc), not on the list of installed docsets.

Another issue with all command line output parsing is that it might break if layout would need to be changed.

On another note, I believe there could be some use cases when Zeal API would make sense. But it should be something reliable and cross-platform, parsing CLI output is one of the worst approaches.

**Comment by trollixx** [comment] 2015-09-10 04:51
Closing in favour of #400.

**Closed by trollixx** 2015-09-10 04:51 UTC
Labels: needs feedback
