### ISSUE TITLE
search in selected docsets

### ISSUE THREAD

**Issue by vnn198** [zealdocs/zeal#442] opened 2015-11-30 15:07 UTC
Very need search in selected docsets.

**Comment by klonos** [comment] 2015-11-30 22:42
This feature is already available. You can try ```docksetname:searchterm```. From the [online documentation](https://zealdocs.org/usage.html):

> **Search Filters**

> You can limit search results to a specific (or a set of specific) docsets.
> The docset filter and the search query are delimited by a colon character (:).

> Examples:

> - ```ruby:set_x``` will search all docsets containing ruby (e.g. ironruby, ruby and ruby2) for ```set_x```
> - ```set_x``` will search all docsets for ```set_x```

**Comment by vnn198** [comment] 2015-12-01 07:32
But this very unusable. if i'm search in CSS or HTML this method convenient, but if im search in Bootstrap 3 or JavaScript this method not faster . very usable method . if have selected docsets search only in selected or place dropdawn menu in search field. as variant may place chekbox in left list docsets for limit search range

**Comment by trollixx** [comment] 2015-12-02 05:30
Feels like a duplicate of the ancient #77. Unfortunately, not possible at the moment.

**Closed** 2016-01-16 01:56 UTC
Labels: duplicate
