### ISSUE TITLE
Downloadable docset listing is in ASCII code/Unicode order rather than alphabetical order.

### ISSUE THREAD

**Issue by ChaiTRex** [zealdocs/zeal#973] opened 2018-08-13 21:54 UTC
This is on 0.5.0 and without entering any search terms. A few examples:

* CSS is before CakePHP
* LaTeX is before Laravel
* jQuery is after literally everything else

I've just started using Zeal, and so many potential docsets might be useful to me that I just scrolled down the list. Then, if I remembered something I wanted but didn't notice on the first scrollthrough, scrolling to its approximate alphabetical location is much faster for me than switching to the keyboard and typing something in.

This threw me for a loop because I couldn't find CSS and it seemed an odd thing to be left out.

**Comment by trollixx** [comment] 2018-10-20 03:07
Duplicate of #244.

**Closed by trollixx** 2018-10-20 03:07 UTC
Labels: Component: UI/Docset Manager, Resolution: Duplicate, Type: Defect
