### ISSUE TITLE
Improve search result ordering

### ISSUE THREAD

**Issue by SamueleDecarli** [zealdocs/zeal#645] opened 2016-11-02 08:49 UTC
Currently search results are sorted alphabetically. When there are a lot of results, many of which aren't that relevant (for example, "listener" matching "list"), this is not very usable. Sorting results by how actually relevant to the query they are, would considerably improve the usability of search.

**Comment by trollixx** [comment] 2016-11-07 05:49
Duplicate of #603.

**Closed by trollixx** 2016-11-07 05:49 UTC
