### ISSUE TITLE
Zeal Crashes with Android Docset

### ISSUE THREAD

**Issue by RiajulKashem** [zealdocs/zeal#952] opened 2018-06-25 13:00 UTC
I am using Zeal 0.6.0  on my Manjaro Linux. I have installed the android docset (and several other ones). When clicking on an entry in the guides category of Android Zeal crashes reproducibly. It's crash on every entry.

**Console output of zeal, when crashes :(**

> qt5ct: using qt5ct plugin
> zeal.core.applicationsingleton: Singleton ID: rSxzOih_mLzEfSW2XIMCyxwc4oOVbEtE0DfNj0nVZbQ
> zeal.core.applicationsingleton: Starting as a primary instance. (PID: 3811)
> qt5ct: D-Bus global menu: no
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> qt5ct: D-Bus system tray: no
> Empty filename passed to function
> free(): invalid pointer
> Aborted (core dumped)
>

**Comment by trollixx** [comment] 2018-06-25 13:36
Do you have Oracle JDK installed by any chance?

>

**Comment by RiajulKashem** [comment] 2018-06-25 13:55
Yeah, recently I have installed Oracle JDK 10 for the android studio.

**Comment by trollixx** [comment] 2018-06-25 17:12
It's a know bug. Plus Oracle JDK is not supported by Arch Linux.

**Comment by RiajulKashem** [comment] 2018-06-26 01:59
Is there any alternative way to resolve this problem without uninstalling Oracle JDK?

**Comment by trollixx** [comment] 2018-06-26 04:39
Sadly not at the moment.

Duplicate of #802.

**Closed by trollixx** 2018-06-26 04:39 UTC

**Comment by Det87** [comment] 2018-06-26 14:48
Uh. Yes there is. I'm the maintainer of Oracle JDK for Arch, and added an .install note about the NPAPI symlink just for that: https://aur.archlinux.org/cgit/aur.git/tree/jdk.install?h=jdk#n41

**Comment by RiajulKashem** [comment] 2018-06-27 06:36
I am new Linux, Do You have any solution for this problem (Crashes of Zeal)? Actually, I don't want to uninstall Oracle JDK.

**Comment by trollixx** [comment] 2018-06-28 05:46
@RiajulKashem I think the workaround is deleting `/usr/lib/mozilla/plugins/libnpjp2-jdk10.so` symlink.

**Comment by Det87** [comment] 2018-06-28 05:47
F

On Jun 28, 2018 08:46, "Oleg Shparber" <notifications@github.com> wrote:

@RiajulKashem <https://github.com/RiajulKashem> I think the workaround is
deleting /usr/lib/mozilla/plugins/libnpjp2-jdk10.so symlink.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zealdocs/zeal/issues/952#issuecomment-400917661>, or mute
the thread

**Comment by RiajulKashem** [comment] 2018-06-28 11:11
@trollixx So how can i  deleting /usr/lib/mozilla/plugins/libnpjp2-jdk10.so symlink ? Can you explaine in details kindly !!

**Comment by trollixx** [comment] 2018-06-28 14:28
`sudo rm <path>` in the terminal

**Comment by RiajulKashem** [comment] 2018-06-29 05:06
@trollixx Thank you so much :) after deleting /usr/lib/mozilla/plugins/libnpjp2-jdk10.so zeal stoped crashing.
