### ISSUE TITLE
Some docsets are not display correct

### ISSUE THREAD

**Issue by goldenages1989** [zealdocs/zeal#374] opened 2015-07-13 09:50 UTC
![jserror](https://cloud.githubusercontent.com/assets/3285965/8646682/78e22752-2984-11e5-84c4-454f479ba8ed.png)

i get this when i search in javascript docset.

**Comment by trollixx** [comment] 2015-07-21 05:10
Hi, I need more information about versions of Zeal, Qt and your operating system. Does it happen all the time?

**Comment by goldenages1989** [comment] 2015-07-22 08:52
zeal version: 0.1.1
qt version: 5.4.1
operating system: wIndows 7 x64
and yes it happens all the time

**Comment by trollixx** [comment] 2017-04-08 06:30
Duplicate of #359.

**Closed by trollixx** 2017-04-08 06:30 UTC
Labels: Component: Web View, Platform: Windows, Type: Defect
