### ISSUE TITLE
Content rendering error - Windows 10

### ISSUE THREAD

**Issue by ArtooS** [zealdocs/zeal#1188] opened 2020-02-13 02:30 UTC
After installing Zeal 0.6.1 on Win10 and downloading a few of the docsets, I'm getting 'Content rendering error' when I try to view the docsets for HTML, CSS and Javascript.

Is anyone else having the same problem with those docsets?

**Comment by trollixx** [comment] 2020-02-13 03:38
Duplicate of #1155.

**Closed by trollixx** 2020-02-13 03:38 UTC
