### ISSUE TITLE
JAVA DOC MAKE APP CRASH

### ISSUE THREAD

**Issue by juanccalzadilla** [zealdocs/zeal#1389] opened 2022-04-28 20:50 UTC
When i try to open the java documentation the app get exit. It only happen with java so far.

**Comment by MarneusAugustusCalgar** [comment] 2022-06-20 05:57
The bug is still unsolved :(

**Comment by wdscxsj** [comment] 2022-07-05 07:28
As a workaround, use Java SE14.

**Comment by trollixx** [comment] 2022-07-23 18:04
Duplicate of #868.

**Closed by trollixx** 2022-07-23 18:04 UTC
