### ISSUE TITLE
ubuntu 14.04.3 logout immediately when search jquery: or select a different docset

### ISSUE THREAD

**Issue by susan51531** [zealdocs/zeal#449] opened 2015-12-17 09:55 UTC
which log file content shoud i post?

**Comment by susan51531** [comment] 2015-12-17 09:56
```
QxtGlobalShortcut failed to register: Meta+Z
QxtGlobalShortcut failed to unregister: Meta+Z
Cannot determine index file for docset SQLite
QxtGlobalShortcut failed to register: Meta+Z
QxtGlobalShortcut failed to unregister: Meta+Z
load glyph failed err=6 face=0x1ea1910, glyph=3097
load glyph failed err=6 face=0x1ea1910, glyph=3097
zeal: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Terminated
```

**Comment by susan51531** [comment] 2015-12-17 10:17
My home partition is a partition of SSD.
This problem doesn't happend after i move the docsets folder to a different partition of HDD

**Comment by susan51531** [comment] 2015-12-17 15:49
Happend again!,
I was selecting docsets where there docsets download tasks running background;

**Comment by trollixx** [comment] 2016-01-20 03:21
I have no idea how to reproduce this. I would think it's a problem with the disk. Does it still happen?

**Comment by trollixx** [comment] 2016-09-19 03:04
Seems like a duplicate of #429, but I have no idea how to reproduce this.

**Closed by trollixx** 2016-09-19 03:04 UTC
Labels: Platform: Linux, Resolution: Duplicate, Type: Defect
