### ISSUE TITLE
crash with "*** Error in `zeal': free(): invalid pointer: 0x00007f46b5dd33c0 ***" when view angularts docs

### ISSUE THREAD

**Issue by eppdev** [zealdocs/zeal#807] opened 2017-10-27 05:16 UTC
I download angularts and other docs from zeal, but when i want to view the angularts document, zeal crashed and I see "*** Error in `zeal': free(): invalid pointer: 0x00007f46b5dd33c0 ***“ in my console.
My OS is archlinux with gome desktop.

I tried zeal-git from aur, and the problem still exists.

**Comment by abelmul** [comment] 2017-10-27 14:23
Yes similar problem here. But when I reverted back Java 9 to Java 8, It works fine. The gdb output looks like this
`#0  0x00007ffff113a8a0 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff113bf09 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff117d517 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff1183c84 in malloc_printerr () at /usr/lib/libc.so.6
#4  0x00007ffff1185599 in _int_free () at /usr/lib/libc.so.6
#5  0x00007fff42959282 in std::locale::_Impl::_M_install_facet(std::locale::id const*, std::locale::facet const*) ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#6  0x00007fff42965de3 in std::locale::_Impl::_Impl(unsigned long) ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#7  0x00007fff42966d55 in std::locale::_S_initialize_once() ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#8  0x00007ffff1db5dbf in __pthread_once_slow () at /usr/lib/libpthread.so.0
#9  0x00007fff42966da1 in std::locale::_S_initialize() ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#10 0x00007fff42966de3 in std::locale::locale() ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#11 0x00007fff429386a4 in std::ios_base::Init::Init() ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#12 0x00007fff429307b8 in __static_initialization_and_destruction_0(int, int) () at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#13 0x00007fff429307ea in _GLOBAL__sub_I_JLIWrapper_md.cpp ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
---Type <return> to continue, or q <return> to quit---
#14 0x00007ffff7de757a in call_init.part () at /lib64/ld-linux-x86-64.so.2
#15 0x00007ffff7de7686 in _dl_init () at /lib64/ld-linux-x86-64.so.2
#16 0x00007ffff7debb5e in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
#17 0x00007ffff1237f14 in _dl_catch_error () at /usr/lib/libc.so.6
#18 0x00007ffff7deb37a in _dl_open () at /lib64/ld-linux-x86-64.so.2
#19 0x00007fffefde5e86 in  () at /usr/lib/libdl.so.2
#20 0x00007ffff1237f14 in _dl_catch_error () at /usr/lib/libc.so.6
#21 0x00007fffefde6587 in  () at /usr/lib/libdl.so.2
#22 0x00007fffefde5f22 in dlopen () at /usr/lib/libdl.so.2
#23 0x00007ffff24dbbce in  () at /usr/lib/libQt5Core.so.5
#24 0x00007ffff24d5429 in QLibrary::load() () at /usr/lib/libQt5Core.so.5
#25 0x00007ffff3e0c791 in  () at /usr/lib/libQt5WebKit.so.5
#26 0x00007ffff3defd38 in  () at /usr/lib/libQt5WebKit.so.5
#27 0x00007ffff3dece41 in  () at /usr/lib/libQt5WebKit.so.5
#28 0x00007ffff3ded812 in  () at /usr/lib/libQt5WebKit.so.5
#29 0x00007ffff3dcbb3b in  () at /usr/lib/libQt5WebKit.so.5
#30 0x00007ffff4f6618c in WebCore::Page::pluginData() const ()
    at /usr/lib/libQt5WebKit.so.5
#31 0x00007ffff510035e in  () at /usr/lib/libQt5WebKit.so.5
#32 0x00007ffff54c1a9b in  () at /usr/lib/libQt5WebKit.so.5
#33 0x00007ffff3f4a907 in JSC::PropertySlot::customGetter(JSC::ExecState*, JSC::PropertyName) const () at /usr/lib/libQt5WebKit.so.5
#34 0x00007ffff4396072 in  () at /usr/lib/libQt5WebKit.so.5
---Type <return> to continue, or q <return> to quit---
#35 0x00007ffff4134e7e in  () at /usr/lib/libQt5WebKit.so.5
#36 0x00007fff00000002 in  ()
#37 0x00007fff61c36ec0 in  ()
#38 0x00007fff61c23b00 in  ()
#39 0x0000000000000000 in  ()
`
It appears that some library is using the java locale, as in these lines
`#9  0x00007fff42966da1 in std::locale::_S_initialize() ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#10 0x00007fff42966de3 in std::locale::locale() ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#11 0x00007fff429386a4 in std::ios_base::Init::Init() ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#12 0x00007fff429307b8 in __static_initialization_and_destruction_0(int, int) () at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so
#13 0x00007fff429307ea in _GLOBAL__sub_I_JLIWrapper_md.cpp ()
    at /usr/lib/jvm/java-9-jdk/lib/libdeploy.so`

**Comment by trollixx** [comment] 2017-10-27 18:06
I think something is messed up with the Arch Linux packages... Qt WebKit has nothing to do with any Java.

**Comment by trollixx** [comment] 2017-10-27 18:08
Duplicate of #802.

**Closed by trollixx** 2017-10-27 18:08 UTC
