### ISSUE TITLE
Vim keys to navigate in Zeal

### ISSUE THREAD

**Issue by OrionRandD** [zealdocs/zeal#1614] opened 2024-04-10 23:52 UTC
Hi,
Could you add Vim keys to navigate in Zeal documentations?
Like j,k,l,h et.al.
Thx a lot.

**Comment by uunnxx** [comment] 2024-04-11 09:41
Yep, at least `j, k, l, h` would be nice to have.

**Comment by novaTopFlex** [comment] 2024-04-29 17:40
I disagree. I would like to see an option for enabling and disabling `vim` keys but do not want to be forced to have `vim` keys on by default.

**Comment by OrionRandD** [comment] 2024-05-01 16:01
> I disagree. I would like to see an option for enabling and disabling `vim` keys but do not want to be forced to have `vim` keys on by default.

There are no comments on the previous posts saying that the vim keys should be forced...
People nowadays do not know how to properly read text and information. They read one thing and interpret what is not written in the texts and answer them as if they had stated what is in their mind and not in texts itself... LOL

**Comment by trollixx** [comment] 2024-06-17 03:31
A very frequent ask, unfortunately requires quite a bit of rework in the configuration management. Duplicate of #10.

**Closed by trollixx** 2024-06-17 03:31 UTC
