### ISSUE TITLE
the javascript documentation doesn't good rendered

### ISSUE THREAD

**Issue by ariskusnulwiditama** [zealdocs/zeal#1198] opened 2020-03-04 19:57 UTC
![Screenshot from 2020-03-05 02-55-38](https://user-images.githubusercontent.com/23493295/75917732-0970ab80-5e8d-11ea-8b4b-c7c9f3fdf218.png)

**Comment by ariancruz** [comment] 2020-03-08 14:02
![error](https://user-images.githubusercontent.com/16599239/76164274-4f976a80-612c-11ea-9147-eea62c9c2a37.png)

**Comment by daymerfillad** [comment] 2020-03-11 03:58
Same error

**Comment by trollixx** [comment] 2020-03-14 05:59
Duplicate of #1155.

**Closed by trollixx** 2020-03-14 05:59 UTC
