### ISSUE TITLE
Content rendering error

### ISSUE THREAD

**Issue by Obura98** [zealdocs/zeal#1216] opened 2020-04-22 07:20 UTC
I'm trying to use zeal for Html and CSS documentation but I get this error.....
An unhandled error occurred in the application. We apologize for the inconvenience!
How do I solve the problem???

**Comment by trollixx** [comment] 2020-04-22 14:42
Duplicate of #1155, which has a temporary workaround.

**Closed by trollixx** 2020-04-22 14:42 UTC
