### ISSUE TITLE
Angular docset.

### ISSUE THREAD

**Issue by Skyd1400** [zealdocs/zeal#668] opened 2016-12-14 00:18 UTC
I've downloaded the angular docset, and I found out it is for the 2.x version. Could you split it and provide the 1.x version. It's the one I use as a number of my projects (commercial ones) use it. LovelyDocs does it. It will be very good if you could too.

**Comment by trollixx** [comment] 2016-12-15 06:15
Duplicate of #208.

**Closed by trollixx** 2016-12-15 06:15 UTC
