### ISSUE TITLE
New offer for ZealDocs Windows application(Linux too)

### ISSUE THREAD

**Issue by MDReal32** [zealdocs/zeal#1142] opened 2019-10-02 14:27 UTC
I give a new idea for Application. Give permission or give client side function, Users can group all installed libraries. For exaple:
I want new group where named as backend and here are PHP, C++, Java
Or any different user want group where in PHP, JS, HTML, CSS and named as Web

**Comment by trollixx** [comment] 2019-10-04 04:39
I guess this is a duplicate of #77.

**Closed** 2019-10-04 04:40 UTC
Labels: resolution/duplicate, scope/registry, type/feature
