### ISSUE TITLE
javascript docset has error (Content rendering error)

### ISSUE THREAD

**Issue by james-muriithi** [zealdocs/zeal#1174] opened 2019-12-19 11:24 UTC
![Screenshot (62)](https://user-images.githubusercontent.com/26818458/71169960-3be61180-226b-11ea-8351-9bc4607af157.png)

**Comment by wwwpalmercom** [comment] 2019-12-20 10:26
have u resolved the problem?

**Comment by james-muriithi** [comment] 2019-12-20 10:32
No

**Comment by metastork** [comment] 2019-12-20 10:42
Have also had the same issue for a few weeks, only with the Javascript docset, others work fine. Have tried updating the docset, deleting it and re-downloading it, and same issue. There are around 1.4GB in the Javascript.docset folder in .local/share and the DB seems fine.

Using Ubuntu (Budgie) 19.10. Please let me know if I can provide any other information.

**Comment by intact** [comment] 2019-12-20 15:57
you can use #1164 patch with some NodeList iterator polyfill

**Comment by AnonymousXuser264** [comment] 2019-12-22 14:22
I wasted a lot of time figuring it out and also some money for the internet. But the end result as same as always. I just wasted my fucking time...
FUCK U All...

**Comment by m4rii0** [comment] 2019-12-25 20:55
Duplicate of #1155

**Closed** 2019-12-27 04:24 UTC
