### ISSUE TITLE
Display documentation outline (aka Table of Contents)

### ISSUE THREAD

**Issue by mcomella** [zealdocs/zeal#1031] opened 2018-11-10 16:35 UTC
Dash has a feature where certain kinds of documentation will display an outline of the file you're currently in:
![Screenshot of outline feature](https://web.archive.org/web/20180918125814/https://kapeli.com/img/dash-s2.png)

In particular, I use this feature on Dash with the Java and Android docsets where opening a class documentation file will show an outline view sorted into categories - fields, constructors, methods - and each of the categories contains the corresponding entries from that class. Clicking one of those items will take you directly to that part of the documentation (i.e. clicking the `computeScroll` method in the outline view of the `WebView` documentation will take you directly to the `computeScroll` method in the documentation viewer).

**Comment by mcomella** [comment] 2018-11-10 16:45
Dash calls this a table of contents: https://kapeli.com/dash_guide#tableOfContents

**Comment by mcomella** [comment] 2018-11-10 21:32
fwiw, I noticed that the qt5 docs come with an outline view:
![screenshot_2018-11-10_13-31-58](https://user-images.githubusercontent.com/759372/48306418-137ad800-e4ed-11e8-9730-469d1bd120a2.png)

**Comment by trollixx** [comment] 2018-11-11 02:51
Duplicate of #386.

Dash has a complicated implementation, that either requires parsing DOM, or using ToC generated for iOS version of Dash, but IIRC there still was a problem with that.

**Closed by trollixx** 2018-11-11 02:51 UTC
