### ISSUE TITLE
Feature request : support user_contributed docs [descriped]

### ISSUE THREAD

**Issue by AlBannaTechno** [zealdocs/zeal#822] opened 2017-11-20 22:17 UTC
HI : 
we just want to support user_contributed docs which dash and velocity support it
The method to do this 
just fetch all user_contributed docs[names/info] from
[index.json](http://sanfrancisco.kapeli.com/feeds/zzz/user_contributed/build/index.json)
or any provided server of kapeli
Then fetch this specific docs as

http://\<mirror\>.kapeli.com/feeds/zzz/user_contributed/build/\<key name inside json\>/\<archive name\>

>Most of times  archive name= key name inside json.tgz

For Example if we need to download bitcoin docs
which it's data in index.json : 
` "Bitcoin" : {
      "author" : {
        "name" : "Jerzy Kozera",
        "link" : "https:\/\/github.com\/jkozera"
      }`
we will use next link

> http://newyork.kapeli.com/feeds/zzz/user_contributed/build/Bitcoin/Bitcoin.tgz

Please 💯 remember to separate user_contributed docs in new section
Good luck 👌

**Comment by trollixx** [comment] 2017-11-21 06:24
Duplicate of #170.

**Closed by trollixx** 2017-11-21 06:24 UTC
