### ISSUE TITLE
Developing node crashes app

### ISSUE THREAD

**Issue by Traroth** [zealdocs/zeal#1503] opened 2023-06-01 09:15 UTC
On some large documentations, like Spring or Java SE 17, Zeal crashes when I click on the develop "+" on the left panel.

To reproduce the issue:

-Click on the documentation in the left panel to display the doc's home
-Click on the "+" of given doc in the left panel to develop the summary

It seems to work for a second, then crashes.

If I do it the other way around, first click on "+" and the on the main title, it develops the summary tree and displays the home, but it still crashes after a few seconds.

**Comment by trollixx** [comment] 2023-08-08 04:40
Duplicate of #868. Please try the latest code from the `main` branch or [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml).

**Closed by trollixx** 2023-08-08 04:40 UTC
