### ISSUE TITLE
Web site still doesn't mention VC runtime dependency

### ISSUE THREAD

**Issue by ernstki** [zealdocs/zeal#1093] opened 2019-04-05 22:11 UTC
There are a slew of closed / locked issues about this, but the problem still remains, and on a "fresh" Windows you will get an error about `VCRUNTIME140.DLL` being missing the first time you try to run Zeal.

![screenshot 2](https://user-images.githubusercontent.com/4009681/55659046-da117480-57cd-11e9-97df-a419c4e36506.png)

I get that #979 is going to add the VC++ runtime as a bundled dependency. But in the meantime, the ["Download" section](https://zealdocs.org/download.html#windows) of the web site could just mention that you need to download the runtime appropriate for your architecture (32-bit or 64-bit) **right there**.

Googling `vcruntime140.dll` is just as likely to lead to malware as the [official Microsoft download page](https://www.microsoft.com/en-us/download/details.aspx?id=52685).

Maybe _some_ users will think to search through the existing issues on GitHub (we are all developers, after all), but the issues search is either terrible or broken, because [searching for `vcruntime`](https://github.com/zealdocs/zeal/issues?utf8=%E2%9C%93&q=is%3Aissue+vcruntime) right now actually turns up... nothing! I didn't even realize there were existing issues until I opened a _new_ issue, and started getting the "beta" suggestions.

So could you maybe just drop a quick note, right there on the downloads page?

**Comment by trollixx** [comment] 2019-04-06 17:34
Done. Duplicate of #936.

**Closed by trollixx** 2019-04-06 17:34 UTC
Labels: resolution/duplicate, scope/documentation, type/enhancement

**Comment by ernstki** [comment] 2019-06-22 23:24
Thanks!
