### ISSUE TITLE
Support installing docs via *.tgz/compressed files

### ISSUE THREAD

**Issue by AlBannaTechno** [zealdocs/zeal#823] opened 2017-11-20 23:18 UTC
Hi : 
i notice : many users have a problem with downloading large docs
because zeal don't support  resume-downloading or multi connection-downloading type
so i suggest to give the users the ability to add docs from compressed files
which zeal get the docs from 
it's very easy you will just use extractor libs/core/extractor class to do this on specific local path
and add complete the life cycle of the operation(fetch docs) so you just will escape downloading docs step

But to be more clearness : how people will get those docs ?
I will answer 😄 
There is two type of docs on kapeli/dash probject

- 1 - docs provided with kapeli it self
 those docs we can get it with next steps
     first:  go to 

>  https://github.com/Kapeli/feeds

Then you will find all of docs provided with kapeli
so you just need to it's name
    Second: use this link
> http://sanfrancisco.kapeli.com/feeds/name-Of-Doc.tgz  located in feeds-master.zip or https://github.com/Kapeli/feeds

For-example : to download NET_Framework docs
which NET_Framework.xml : 

```json
<entry>
    <version>4.7.0</version>
    <ios_version>1</ios_version>
    <url>http://sanfrancisco.kapeli.com/feeds/NET_Framework.tgz</url>
    <url>http://london.kapeli.com/feeds/NET_Framework.tgz</url>
    <url>http://newyork.kapeli.com/feeds/NET_Framework.tgz</url>
    <url>http://tokyo.kapeli.com/feeds/NET_Framework.tgz</url>
    <url>http://frankfurt.kapeli.com/feeds/NET_Framework.tgz</url>
    <url>http://sydney.kapeli.com/feeds/NET_Framework.tgz</url>
    <url>http://singapore.kapeli.com/feeds/NET_Framework.tgz</url>
    <other-versions>
        <version><name>4.7.0</name></version>
        <version><name>4.6.2</name></version>
        <version><name>4.6.1</name></version>
    </other-versions>
</entry>
```

Notic You can use any mirror such: 

> sanfrancisco , london , newyork , tokyo , frankfurt , frankfurt ,sydney  , singapore

i will use this : 

> http://sanfrancisco.kapeli.com/feeds/NET_Framework.tgz

- 2 : docs contributed with users
   First fetch all user_contributed docs[names/info] from

> http://sanfrancisco.kapeli.com/feeds/zzz/user_contributed/build/index.json

or any provided server of kapeli
Then fetch this specific docs as

> http://\<mirror\>.kapeli.com/feeds/zzz/user_contributed/build/\<key name inside json\>/\<archive name\>

> Most of times archive name= key name inside json.tgz

For Example if we need to download bitcoin docs
which it's data in index.json :

`"Bitcoin" : { "author" : { "name" : "Jerzy Kozera", "link" : "https:\/\/github.com\/jkozera" }
`
we will use next link

> http://newyork.kapeli.com/feeds/zzz/user_contributed/build/Bitcoin/Bitcoin.tgz

Remember You can use any mirror such: 

> sanfrancisco , london , newyork , tokyo , frankfurt , frankfurt ,sydney  , singapore

Note : when you use this method you will not get the icon of the docs because of icon of docs not embedded in those links , method to do this was implemented in the source code of zeal

Good Luck 🌻

**Comment by trollixx** [comment] 2017-11-21 06:27
Duplicate of #138. Please use search before creating a new issue.

**Comment by trollixx** [comment] 2017-11-21 06:33
I thought it's a duplicate of #138, but no. This ticket describes how Zeal downloads docsets, so I am not sure what is actually requested. There's #430 for resuming downloads, and #170 for user contributed docsets.

**Comment by trollixx** [comment] 2017-11-21 06:33
Please explain what feature are you looking for specifically.

**Comment by AlBannaTechno** [comment] 2017-11-21 07:10
> i'am sorry i forget to explain this [i work with phpstorm/gfm-plugin]


i just want to add a new section to zeal:Tools/Docsets
to add new doc-set from *.tgz files & support multi-file extraction for it
the purpose of this : 
1- give zeal the ability to store only data added from it /Feature request
it's mean prevent user from coping docs manually to zeal docs-dir
this will help if you will support data-base docs indexing like 'velocity'
2-give user the ability to get those docs from anywhere 
 either docs location is local-path or internal server/network [fetch-all-docs]
it's very generic but it's the idea
to give zeal more flexibility and Control

Thanks , Sorry

**Comment by abelmul** [comment] 2017-12-23 21:09
I think you can do this by extracting the *.tgz file in the zeal docs directory(You can find it in preferences). Except for the icon you have to download and put the icons there yourself.

**Comment by trollixx** [comment] 2018-01-02 22:05
As @abelmul mentioned, part of the problem is lack if some meta information in the archives. 

This is a duplicate of #392, so please subscribe for updates.

**Closed by trollixx** 2018-01-02 22:05 UTC
Labels: Component: UI/Docset Manager, Resolution: Awaiting Response, Type: Feature
