### ISSUE TITLE
Close button on tabs is too big and is cut: a part is missing

### ISSUE THREAD

**Issue by Porkepix** [zealdocs/zeal#935] opened 2018-05-01 17:36 UTC
As summary state it, the close button on tabs is too bug, a part of it is missing.

See joined screenshot:

![screenshot from 2018-05-01 19-34-26](https://user-images.githubusercontent.com/709500/39484718-f0f621c6-4d76-11e8-9ae6-1bc430852513.png)

EDIT: This is looking this way using latest Gnome (3.28) on Archlinux.

**Comment by trollixx** [comment] 2018-05-22 05:16
This can be a bug in your Qt's theme, Qt's support for GTK themes, or some scaling issue. Zeal doesn't have any special code for tabs styling.

What theme do you use for Qt applications?

**Comment by Porkepix** [comment] 2018-05-22 05:18
I'm not using any theme. It's the latest Gnome and latest GTK on Archlinux with absolutely no customization.

**Comment by trollixx** [comment] 2018-05-22 05:24
HiDPI screen?

**Comment by Porkepix** [comment] 2018-05-22 05:27
Full HD, on a 14.1" laptop. However I noticed similar issue on VLC which is also using Qt, could that be related? See https://trac.videolan.org/vlc/ticket/18959

**Comment by trollixx** [comment] 2018-05-22 05:34
Yeah, it's a bug in Qt. Please try the suggested `export QT_AUTO_SCREEN_SCALE_FACTOR=0` work around.

I believe this is another manifestation of the scaling issue from #869.

**Comment by Porkepix** [comment] 2018-05-22 06:31
Yes, with `QT_AUTO_SCREEN_SCALE_FACTOR=0` it does not have the issue. And the window does open in a small window instead of the usual maximized mode.

**Comment by trollixx** [comment] 2018-09-28 01:40
Duplicate of #869.

**Closed by trollixx** 2018-09-28 01:40 UTC
Labels: Component: UI, Resolution: Duplicate, Type: Defect
