### ISSUE TITLE
When updating latest spring framework's docset, error happens

### ISSUE THREAD

**Issue by yosaku01** [zealdocs/zeal#835] opened 2017-12-04 05:55 UTC
The environment is Windows 10 64bit.
When I updating the latest spring framework's docset,  the progress reaches 99 percent, and one error message dialog shows as below graph
![image](https://user-images.githubusercontent.com/1314082/33538146-a08ebd92-d8fa-11e7-9651-1b22fd43f749.png)
The zeal version is 0.4.0

**Comment by yosaku01** [comment] 2017-12-04 05:56
In windows 7 64bit environment, the same dialog shows.

**Comment by yosaku01** [comment] 2017-12-04 09:29
In CentOS 7.4, this problem does not happen.

**Comment by trollixx** [comment] 2017-12-04 21:27
Remove docset directory from your docset storage path. Duplicate of #788.

**Closed by trollixx** 2017-12-04 21:27 UTC

**Comment by yosaku01** [comment] 2017-12-05 01:31
Thank you, I will try it.
