### ISSUE TITLE
Missing UI hint if docset is Python 2 or Python 3

### ISSUE THREAD

**Issue by pszalanski** [zealdocs/zeal#554] opened 2016-07-05 05:47 UTC
If I have the python 2 and python 3 docsets installed, I can see no difference between search results from either docset. A different icon, a little emblem or a tooltip on the result list would be sufficient. 

Any ideas / suggestions?

**Comment by trollixx** [comment] 2016-07-21 04:31
Thanks for reporting. This is a duplicate of #343. Please follow that issue for progress updates.

**Closed by trollixx** 2016-07-21 04:31 UTC
Labels: Component: UI, Type: Enhancement
