### ISSUE TITLE
Feature Request: Group docsets with user defined keywords

### ISSUE THREAD

**Issue by ajmwagar** [zealdocs/zeal#944] opened 2018-05-17 15:57 UTC
This feature would allow users to group multiple docsets under a single keyword.

Say if I wanted to create a keyword for js I would add my node.js docset my mongoose docset maybe pug and a few more. Then I could search them all with: `<keyword>:<search>`.

For example `java:` and `python:` group all the java/python docsets together. 
This would allow the user to create their own groupings.

**Comment by trollixx** [comment] 2018-05-23 02:41
Duplicate of #77.

**Closed by trollixx** 2018-05-23 02:41 UTC
