### ISSUE TITLE
Provide mysql version 5.7 documentation

### ISSUE THREAD

**Issue by Danielesk** [zealdocs/zeal#988] opened 2018-09-08 13:12 UTC
Can you provide documentation for mysql version 5.7? The default is 8.0; the version is differentiated like the supplied java document.

![java_doc](https://user-images.githubusercontent.com/10652829/45254494-c6bf3780-b3ab-11e8-8d51-b6566c7affa0.png)

**Comment by auscompgeek** [comment] 2018-09-08 14:13
Duplicate of #208.

**Comment by trollixx** [comment] 2018-09-12 12:41
per above

**Closed by trollixx** 2018-09-12 12:41 UTC
