### ISSUE TITLE
Zeal 0.6.1 crashes with  Java SE (9 to 16)

### ISSUE THREAD

**Issue by apietroluongo** [zealdocs/zeal#1341] opened 2021-06-07 16:25 UTC
#### Describe the bug

Zeal crashes with Java SE docsets. (9 to 16).

on  Windows 10 (Installer and Portable).

**Comment by Dominiquini** [comment] 2021-12-13 01:31
I'm having problems with Java SE15 and Java SE16! Java SE14 works fine for me!

Duplicate: https://github.com/zealdocs/zeal/issues/1339

**Comment by king0billy** [comment] 2021-12-17 11:35
ooh  I'm having exactly the same problem as yours, lol

**Comment by trollixx** [comment] 2022-07-23 22:04
Duplicate of #868.

**Closed by trollixx** 2022-07-23 22:04 UTC
