### ISSUE TITLE
Feature: editable keywords for docsets

### ISSUE THREAD

**Issue by jytug** [zealdocs/zeal#765] opened 2017-08-24 15:47 UTC
I started using Zeal after a period during which I had been working on a mac, and one of the features I miss the most from Dash is being able to set my own keywords for docsets.
This way, for instance, `py2` instead of `python2`, or `hs` instead of `haskell`, would allow much quicker scoped search.

**Comment by trollixx** [comment] 2017-08-26 22:34
Duplicate of #421.

**Closed by trollixx** 2017-08-26 22:34 UTC
Labels: Component: Docset Registry, Resolution: Duplicate, Type: Feature
