### ISSUE TITLE
Docset storage is readonly

### ISSUE THREAD

**Issue by iambrojohnson** [zealdocs/zeal#1421] opened 2022-08-15 02:30 UTC
i can't install any doc because of the message saying docset storage is readonly
I've tried every solution here but it does not seem to work
I'm using PopOs even tho I've not experienced this in LInux MInt

**Comment by trollixx** [comment] 2023-09-27 08:19
Duplicate of #1036.

**Closed by trollixx** 2023-09-27 08:19 UTC
