### ISSUE TITLE
Build Debian Sid, Qt5.2.0 error (qpa/qplatformnativeinterface.h - no such file)

### ISSUE THREAD

**Issue by lebies** [zealdocs/zeal#123] opened 2014-03-03 10:08 UTC
Trying to install on SolydXK (KDE), based on Debian testing.

Details:
```$ uname -a
Linux leon 3.11-2-amd64 #1 SMP Debian 3.11.10-1 (2013-12-04) x86_64 GNU/Linux```

Qt5 prerequisits installed from -t unstable

```$ qmake
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!```

```$ make
g++ -c -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIE -DZEAL_VERSION=\"20140215\" -DLINUX -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Iquazip -I/usr/include/qt5 -I/usr/include/qt5/QtWebKitWidgets -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWebKit -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtGui/5.2.0 -I/usr/include/qt5/QtGui/5.2.0/QtGui -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o mainwindow.o mainwindow.cpp
mainwindow.cpp:30:42: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
 #include <qpa/qplatformnativeinterface.h>
                                          ^
compilation terminated.
make: *** [mainwindow.o] Error 1```

I've had this issue before which was fixed by developer removing the include reference (and some other fixes I would imagine).

Help/advice appreciated.

Thanks in advance.

**Comment by trollixx** [comment] 2015-01-30 06:13
Zeal's website will be updated with compilation instructions for different distributions.

I am closing this one as a duplicate of #61.

**Closed by trollixx** 2015-01-30 06:13 UTC

**Comment by psykokwak4** [comment] 2015-02-28 16:08
@spacewander million thanks!
