### ISSUE TITLE
Follow OS theme with respect to font color

### ISSUE THREAD

**Issue by namandixit** [zealdocs/zeal#557] opened 2016-07-08 15:48 UTC
Some docsets are plain HTML with no styling information. On Linux Mint 17.3 with Xfce 4.12, with a dark theme (GTK 2), the text should appear white (as it does in other softwares). However, in Zeal, the text still appear black while the background follows the dark theme. This makes the text very hard to read with blackish themes; with grey/blue themes, blue hyperlinks are unreadble.

Solutions will include:
1. Following the OS theme for the font too (which on dark themes is generally white), or
3. Giving an option to change appearance settings per docset, or
2. Giving a default fallback CSS file or something

![screenshot_2016-07-08_21-06-02](https://cloud.githubusercontent.com/assets/8736472/16693086/2c89eea0-4551-11e6-8c93-ec473a6f4750.png)

**Comment by Sathors** [comment] 2016-07-09 16:32
I do have the same problem, using a dark theme, but only with some docsets (SQLite and Neat in my case).

I guess the easiest in a first step would be the 2. option (the last one!).

**Comment by trollixx** [comment] 2016-07-09 18:13
This is a duplicate of #488. Please continue the discussion there.

I am yet not sure what's the best way to address this problem, but most I'll add an override CSS for now.

**Closed by trollixx** 2016-07-09 18:13 UTC
