### ISSUE TITLE
JavaScript documentation is not rendered.

### ISSUE THREAD

**Issue by quasiblob** [zealdocs/zeal#1283] opened 2020-09-21 14:19 UTC
**Only thing that gets rendered is:**
_"Content rendering error
An unhandled error occurred in the application. We apologize for the inconvenience!"_

And a "Reload Page" button below this error.

I think this has been broken for more than 6 months. 

Is there going to be a fix or should I start looking for another viewer?

**Comment by EdricChan03** [comment] 2020-09-22 04:03
Duplicate of the pinned issue #1155

**Comment by jorgeTalancon** [comment] 2020-09-26 16:37
I do have the same problem! :)

**Comment by lesar** [comment] 2020-10-02 07:05
same problem on Ubuntu 20.04 desktop on rpi4

**Comment by iootaa** [comment] 2020-10-10 02:40
There are some more info **and solutions** there https://github.com/zealdocs/zeal/issues/1155#issuecomment-642579981

**Closed** 2020-10-22 03:22 UTC
Labels: resolution/duplicate, scope/ui/webview, type/defect
