### ISSUE TITLE
search problem

### ISSUE THREAD

**Issue by aryayounesi** [zealdocs/zeal#1406] opened 2022-06-27 22:47 UTC
greetings. first of all, I would like to congratulate to you for building free open source apps; It is very humanly. 
after that, I am not sure if you are still developing Zeal, but I had faced problem with search in codes on WX with many docsets. for example, when I am looking for a tag and trying to write it down for a few seconds a list appeared the app gets closed, crushed exactly. regards.

**Comment by mquinson** [comment] 2022-07-14 19:27
Hello, could you please provide more information about your setup (OS, version of Zeal)? 
Thanks,

**Comment by kevlptimes** [comment] 2022-07-22 00:15
hello team,

I get exact same issue, it happens to me when I click on Java documentation it stops and closes itself, I applied the workaround on  the website to install redistributable but it is the same. im running windows 11 and zeal version 0.6.1

**Comment by trollixx** [comment] 2022-07-23 22:05
Duplicate of #868. The problem is fixed in the `master` branch.

**Closed by trollixx** 2022-07-23 22:05 UTC

**Comment by kevlptimes** [comment] 2022-07-24 02:02
Hello, on latest version 0.6.1 still crashes with almost all javadoc sets, im using windows 11, which version has the fix?

**Comment by trollixx** [comment] 2022-07-24 02:12
> Hello, on latest version 0.6.1 still crashes with almost all javadoc sets, im using windows 11, which version has the fix?

v0.7.0 will have it. For now the code in the `master` branch should work fine if you want to build it yourself.

**Comment by aryayounesi** [comment] 2022-07-28 00:06
> Hello, could you please provide more information about your setup (OS, version of Zeal)? Thanks,

hello; yes sure. the problem I described was on my windows 10 machine. to give details, I use the latest version of zeal, and for docsets I had html, css, php, python 2&3, markdown, latex, java scripts, and bootstrap. the problem pops out when I try to search a code, e.g. I am looking for "direction" tag. at first for one second a list appeared in all docs then the application would be closed automatically. I tried to reduce docs but it persists. not sure about apps behavior on linux. 
hope this would be clearer, if not let me know please.
regards.
~~~~
