### ISSUE TITLE
Windows: Pages with * (star) in URL cannot be opened

### ISSUE THREAD

**Issue by mmaulwurff** [zealdocs/zeal#994] opened 2018-09-18 04:14 UTC
![zeal-star](https://user-images.githubusercontent.com/742823/45663942-4e870d80-bb33-11e8-84ca-4fac0a4ca06e.png)

Example: std::shared_ptr page in C++ documentation contains a link to
file:///C:/Users/kromm/AppData/Local/Zeal/Zeal/docsets/C++.docset/Contents/Resources/Documents/en.cppreference.com/w/cpp/memory/shared_ptr/operator*.html

This can be considered a docset's problem, though.

**Comment by trollixx** [comment] 2018-09-19 04:12
Linux and macOS allow asterisks in file names, Windows doesn't. I think this will stay open until #138 gets implemented.

**Comment by trollixx** [comment] 2020-04-26 23:11
Marking this as a duplicate of #1009, which is not Windows specific, but caused by the same underlying problem, and contains more discussion.

**Closed by trollixx** 2020-04-26 23:11 UTC
Labels: status/duplicate, type/defect, platform/windows, scope/docset-registry
