### ISSUE TITLE
font rendering issue

### ISSUE THREAD

**Issue by blackarcher21** [zealdocs/zeal#468] opened 2016-01-12 13:03 UTC
Screenshot:
http://i.imgur.com/S8yxGKm.png

I found it on laravel docset. it looks fine when open on external browser

**Comment by trollixx** [comment] 2016-01-20 04:18
I think it's a QWebKit issue. I am going to provide test build based on QWebEngine, then we can see whether the issue is solved there.

**Comment by jabui** [comment] 2016-02-24 09:10
Similar issue happening with the PHP docs, for me Zeal is rendering every page in italics
Screenshot: [http://imgur.com/y2p5Vja](http://imgur.com/y2p5Vja)

**Comment by kraml** [comment] 2016-03-01 01:28
Could you provide the QWebEngine based test build? I have issue with Zeal font rendering when using MacType on Windows. With MacType enabled, the fonts referred by the document which does not exist locally are all rendered as garbage characters. But Chrome have no problem with MacType so I suspect it is QWebKit problem and QWebEngine may solve it.

**Comment by coccoinomane** [comment] 2016-03-31 13:20
Hi, I am experiencing the same problem as @jabui: Zeal renders every page of the PHP docs in italics. I am using the Windows binary on Win10 (0.2.1, Built on Nov 19 2015), directly dowloaded today from `https://zealdocs.org/download.html`. I am afraid I know nothing about QWebEngine.

If I may add another potential issue, the jQuery docs look a bit too grainy, as if they are not anti-aliased; please refer to the screenshot.
![jquery aliased](https://cloud.githubusercontent.com/assets/3920436/14176945/f9e56240-f753-11e5-9985-42fec15f0df2.png)

**Comment by trollixx** [comment] 2016-04-01 04:40
I'll switch CI builds to use Qt WebEngine soon. Then quick tests will show us whether this is a Qt WebKit specific problem.

**Comment by frantic1048** [comment] 2016-05-02 10:45
**Platform**: Arch Linux latest

Similar issue happens on several docs: MDN docs, React, Sinon.

![image](https://cloud.githubusercontent.com/assets/3102803/14952509/8374f9c2-1026-11e6-8706-9ce22ff4ef02.png)

With an external browser, the doc looks fine.

I found it's the issue with the generic font-family setting. If I don't have the fonts required by the doc, then this issue happens -- fallback to a not so cool font.

On browsers, there're settings allow users to define which font will be used on sans/sans-serif/monospace/... fallback. I think Zeal may need such settings to make fonts cool, if possible :)

**Comment by z-engine** [comment] 2016-11-04 02:45
> I think Zeal may need such settings to make fonts cool, if possible :)

I fully support this opinion. Archlinux with [infinality font bundle](https://wiki.archlinux.org/index.php/Infinality). Zeal look like this:
[![](https://imgur.com/dRVJw62.png)](https://imgur.com/dRVJw62.png)
With google-chrome docs look good:
[![](https://imgur.com/YoCcTUc.png)](https://imgur.com/YoCcTUc.png)

**Comment by trollixx** [comment] 2016-12-16 03:11
Marking this issue as a duplicate of #359. These all are Qt WebKit problems.

**Closed by trollixx** 2016-12-16 03:11 UTC
Labels: Component: Web View, Platform: Windows, Type: Defect
