### ISSUE TITLE
Prefixes for Rails 4/5

### ISSUE THREAD

**Issue by Sathors** [zealdocs/zeal#647] opened 2016-11-02 22:56 UTC
Hi,

Are there different prefixes to search in rails 4 and in rails 5? I have tried some combinations, nothing works.

When I open the *.docset/Contents/Info.plist, both have the same CFBundleIdentifier set to rails.
Is this where the prefix is taken from?

It's similar to issue #604.

Thanks.

**Comment by trollixx** [comment] 2016-11-07 05:51
Duplicate of #604.

**Closed by trollixx** 2016-11-07 05:51 UTC

**Comment by trollixx** [comment] 2016-11-16 08:57
[Update](https://github.com/zealdocs/zeal/issues/604#issuecomment-260889546) on the new search keywords.
