### ISSUE TITLE
Zeal crash opening some docsets

### ISSUE THREAD

**Issue by Dominiquini** [zealdocs/zeal#1339] opened 2021-05-29 05:34 UTC
I recently successfully downloaded the "Java SE16" docstet, but when I try to view it, the application overlaps. The same problem happens with "Java SE15"!
The "Java SE14" docset and any others I tested seem to work well!

This is the only log that I was able to find: [Report.wer.log](https://github.com/zealdocs/zeal/files/6564083/Report.wer.log)

Thanks.

**Comment by nikitabobko** [comment] 2021-05-29 20:43
Also reproduciable on `Android` docset

**Comment by Dominiquini** [comment] 2021-05-29 21:00
The Android docset is working for me!

**Comment by Dominiquini** [comment] 2021-05-29 21:00
> 
> 
> Also reproduciable on `Android` docset

The `Android` docset is working for me!

**Comment by bmix** [comment] 2021-06-03 22:46
It crashes me, whenever I open the Java 9SE docset, but Java 8SE is fine. I am on Windows 10.

**Comment by alenwesker** [comment] 2021-10-30 07:58
Me too, java ee15/16 docset crashes when open any page of the conent.

**Comment by VinKang** [comment] 2021-11-21 05:56
Me too.

**Comment by Dominiquini** [comment] 2022-02-04 18:58
Java SE 17 docset is also crashing!

**Comment by XaverB** [comment] 2022-07-02 07:23
Java SE 18 docset is also crashing!

**Comment by nomadbard916** [comment] 2022-07-20 11:53
for me the latest applicable version is Java SE 14

**Comment by trollixx** [comment] 2022-07-23 22:02
Duplicate of #868.

**Closed by trollixx** 2022-07-23 22:02 UTC
