### ISSUE TITLE
Enhance the search

### ISSUE THREAD

**Issue by inprealpha** [zealdocs/zeal#288] opened 2015-03-07 13:27 UTC
Many times zeal turns _really_ irrelevant results. I read the issues, fuzzy search and Full text searches will definitely improve the search. Also you can introduce search operators. This will help in FTS which is usually slower. This will take zeal from good to awesome!

**Comment by trollixx** [comment] 2015-03-08 07:42
Could you provide actual examples of irrelevant search results? All data Zeal has is a list of symbols (classes, methods, etc), so search results are simply all symbol names that contain entered term.

**Comment by abirwas** [comment] 2015-03-09 15:30
Say I forgot about an escape sequence, searched escape sequence in zeal (for a list of escape sequences) and the result is not exactly what I want. I understand that zeal uses specific names of functions, classes, etc. but this is just feedback, a way to make zeal even better.

**Comment by trollixx** [comment] 2015-03-10 07:43
I like the idea with logical operators. Perhaps that could be implemented along with the full-text search (#280). Although, that's a really long shot.

**Comment by scientist-st** [comment] 2015-03-25 13:36
Support for topic / headline search would be very nice.

E.g. to find the following page of the Qt help one must navigate 3 pages from the Qt docs start page, searching for "c++ plugin" or similar terms turns up nothing:

![zeal_search_issue](https://cloud.githubusercontent.com/assets/2573046/6825545/a2db900a-d2fb-11e4-8f40-07e301f052cd.png)


BR,
Samuel

**Comment by trollixx** [comment] 2015-03-25 19:44
The Qt example is problem in the docset itself. Looks like not all articles are part of the index.

The full-text search would certainly eliminate such issues.

**Comment by Kapeli** [comment] 2015-03-25 19:55
The Qt docset does not include guides, only API stuff. I'll try to include guides the next time I generate the docset (i.e. when Qt releases a new version).

**Comment by dimaursu** [comment] 2015-05-13 14:24
Devdocs.io has a nice search implementation - it's fuzzy and stuff, but I don't think it's a full-text search. That would be way too expensive, especially when you have several massive documentations enabled (think sass + wordpress + php + vim + other stuff) 

https://github.com/Thibaut/devdocs/blob/c5ace7effd0bbb7f226b1cd90ae74976a02fc09b/assets/javascripts/views/search/search.coffee

**Comment by trollixx** [comment] 2015-05-14 03:15
I think to utilise one of C++ ports of Lucene engine. That should make fuzzy and full-text search possible and really fast. Not sure about ETA unfortunately, as it's pretty time consuming task.

**Comment by trollixx** [comment] 2017-10-07 22:03
Fuzzy search has been implemented (see #100). Development of FTS (or rather lack of) is tracked in #280. 

Closing as a duplicate of #100 and #280.

**Closed by trollixx** 2017-10-07 22:03 UTC
Labels: Component: Docset Registry, Type: Feature
