### ISSUE TITLE
[feature] Disable downloaded Docsets

### ISSUE THREAD

**Issue by n9r** [zealdocs/zeal#663] opened 2016-11-24 23:47 UTC
Possibility to disable (not include in the search) particular docsets that are already stored on disk.

**Comment by jalcine** [comment] 2016-11-25 02:25
Since it's a search, would this be considered a _filter_? Attempting to centralize language of the feature request to the domain it'd be affecting.

**Comment by n9r** [comment] 2016-11-27 22:00
Effectively yes but could also improve efficiency on low spec machines.

**Comment by trollixx** [comment] 2016-12-15 06:40
Duplicate of #77.

**Closed by trollixx** 2016-12-15 06:40 UTC
Labels: Component: Docset Registry, Resolution: Duplicate, Type: Feature
