### ISSUE TITLE
Java and Spring Error

### ISSUE THREAD

**Issue by RaynerSoto** [zealdocs/zeal#1508] opened 2023-06-21 23:46 UTC
Java and Spring helps shut down the application at once without throwing exceptions

**Comment by SantiagoNoguera** [comment] 2023-06-22 04:08
It's true, I download the Spring framework and Java domumentation but the application shut down when I try to see something of the documentation

**Comment by trollixx** [comment] 2023-08-06 16:47
Duplicate of #868.

Until v0.7.0 is released, please build Zeal from `main` or give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try.

**Closed by trollixx** 2023-08-06 16:47 UTC
Labels: resolution/duplicate, type/defect, scope/ui/webview
