### ISSUE TITLE
Many pages of the javascript docs don't open that did recently

### ISSUE THREAD

**Issue by David-Else** [zealdocs/zeal#1044] opened 2018-11-26 17:10 UTC
I am running Zeal 0.6.1.

I have seen a few error reports regarding the JS Docs in the past, but this seems different/worse and only recent. Many pages just can't be accessed, for example, many of the keywords:

keywords/ break / const / continue / debugger / import / if...else / label / let

It is totally messed up, is there a link to an old docset that works, or is this likely to be fixed? Cheers.

**Comment by David-Else** [comment] 2018-12-17 11:53
Still not working with the new Docset update.

As Javascript is the most popular language right now, will this be addressed? Cheers.

https://insights.stackoverflow.com/survey/2018/#technology

**Comment by auscompgeek** [comment] 2018-12-17 12:13
If you're on an OS with case-sensitive filesystems, this is a duplicate of #1009. If not, well, nothing Zeal can do about it I guess.

**Comment by David-Else** [comment] 2018-12-17 19:18
@auscompgeek Thanks! Changing `JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/statements `to `Statements`. Did the job.

**Closed** 2018-12-17 19:18 UTC

**Comment by trollixx** [comment] 2018-12-19 03:51
Unfortunately, there's not much we can do until we move to a new compressed format.
