### ISSUE TITLE
Mouse wheel not working on (X)ubuntu 14.10 64bit

### ISSUE THREAD

**Issue by gionkunz** [zealdocs/zeal#277] opened 2015-02-19 13:06 UTC
I can't seem to scroll with my mouse in the embedded browser. Is this a known problem?

**Comment by trollixx** [comment] 2015-02-19 16:47
No. I haven't seen such issues.  What Zeal version are you using?

**Comment by gionkunz** [comment] 2015-02-19 17:03
Zeal 2014015 with qt 5.3.0

**Comment by trollixx** [comment] 2015-02-19 17:32
That is really old, could you try to build a version from the master branch?

**Comment by gionkunz** [comment] 2015-02-19 17:34
Well i got it from your PPA :-) if its that old maybe we can update it
there too? Ill try to build it.
Am 19.02.2015 18:32 schrieb "Oleg Shparber" <notifications@github.com>:

**Comment by trollixx** [comment] 2015-02-22 09:16
Please try our [daily PPA](https://launchpad.net/~jerzy-kozera/+archive/ubuntu/zeal-daily).

**Comment by trollixx** [comment] 2015-03-25 17:02
Closing for now as it's been too long without user response. Feel free to reopen in case the problem still occurs.

**Comment by gionkunz** [comment] 2015-04-01 18:26
Hi, sorry for the late reply, I was very busy. I'm now using the daily build (from today) and Qt 5.3.0 on a fresh Ubuntu 14.10 64bit version and my mouse wheel is not working for scrolling. I need to grab the scroll bar and scroll like this.

**Comment by gionkunz** [comment] 2015-05-11 07:08
Any updates on this? Cheers

**Comment by trollixx** [comment] 2015-05-11 19:39
I haven't got a chance to check this problem. :( It doesn't occur on Ubuntu 14.04 LTS, so maybe the bug is related to Qt version. In meanwhile, could you try to unset global hotkey and see if the problem is still there? We have a weird XCB issue, and it triggers different problems in unexpected places.

**Comment by trollixx** [comment] 2015-05-21 06:11
It looks like this problem is caused by Qt 5.3 and not Zeal.

@gionkunz Could you try Zeal with Qt 5.4?

**Comment by gionkunz** [comment] 2015-05-21 11:11
I can test this, sure.

**Comment by trollixx** [comment] 2016-09-20 22:30
No updates for over a year, I hope the problem is gone with the newer Qt versions.

**Closed by trollixx** 2016-09-20 22:30 UTC
Labels: Component: UI, Platform: Linux, Type: Defect
