### ISSUE TITLE
rust docset entries flooded with trait implementors

### ISSUE THREAD

**Issue by margh** [zealdocs/zeal#1110] opened 2019-06-24 06:50 UTC
over the last few versions of the rust docset the entries have been increasing and becoming less accurate.

there seem to be huge numbers of entries because of links to trait implementors. 
some method entries still accurately link to the documentation but most of them only direct to the top level of the trait definition page. some methods do link to the page with actual definitions but they no longer reference the correct heading on the page and instead break on the top level.

i realise this is probably related to the zeal generated metadata but i'm not sure where to report issues for that.

dash 0.3.1 on debian stretch (0.6 seems to depend on a version of libqt that's only available in sid)

![Screenshot_2019-06-24_16-32-10](https://user-images.githubusercontent.com/28417/59996922-033ff380-969f-11e9-87ac-9d34509b47c6.png)

**Comment by auscompgeek** [comment] 2019-07-14 11:14
This is not actually an issue with Zeal, but from Kapeli's upstream docset.

@Kapeli, would it be possible to improve this situation? I agree with OP that this makes searching rather difficult, to the point where I'm considering using the upstream docs package instead.

**Comment by trollixx** [comment] 2019-07-14 14:23
This is a duplicate of #1032. Dash figures out result grouping on its own, Zeal needs to do the same.

**Comment by auscompgeek** [comment] 2019-07-14 15:10
The Rust docset is a bit of an oddity in this case - all those entries point to the same page, with only the URL fragment being different. I'd definitely say this one is an upstream issue and not a duplicate.

**Comment by Kapeli** [comment] 2019-07-14 21:27
In Dash each of those entries point to the correct anchor within the page. So if Zeal is not jumping to the correct anchor it's a bug with Zeal I think.

Regardless, the issue is the huge amount of entries. [The docs](https://doc.rust-lang.org/1.36.0/core/iter/trait.Iterator.html) list a lot of stuff under "Implementors", which I currently index. Should I ignore everything under "Implementors" while indexing?

**Comment by auscompgeek** [comment] 2019-07-15 11:58
Unless Dash somehow disambiguates each entry with the type for which the trait is being implemented, I would say that indexing every implementation isn't useful.

Funnily enough, the size of the particular doc page in question was a problem in itself - nightly builds have a slight improvement on that front, see https://github.com/rust-lang/rust/issues/55900

**Comment by Kapeli** [comment] 2019-07-17 17:38
Dash is able to disambiguate each entry, but not currently (it's missing the extra data in Rust's index). I'll add this data. @trollixx you were correct to mark this as duplicate of https://github.com/zealdocs/zeal/issues/1032.

**Closed** 2019-07-19 16:04 UTC
Labels: resolution/duplicate, scope/registry, type/feature
