### ISSUE TITLE
To open a link in a new window opens an empty window

### ISSUE THREAD

**Issue by tonyfrenzy** [zealdocs/zeal#914] opened 2018-03-23 08:52 UTC
- On PC, to open an internal link from a doc page in a new window opens an empty window (zealdoc's welcome page) and opens the link on top of the current window.

- An there's also an "Error opening C:/Users/***.html: The system cannot find the path specified".

**Comment by trollixx** [comment] 2018-04-03 06:56
Duplicate of #635. Fixed in the (unreleased) 0.6.x branch.

**Closed by trollixx** 2018-04-03 06:56 UTC
