### ISSUE TITLE
Wordpress default index page not found error

### ISSUE THREAD

**Issue by indiarocks08** [zealdocs/zeal#1344] opened 2021-06-22 06:41 UTC
![error](https://user-images.githubusercontent.com/3152306/122876237-e5bbc800-d352-11eb-9a0b-7478b5625f5b.PNG)

**Comment by albertomarun** [comment] 2022-04-28 22:46
Good day, I corrected it manually edit the file "Info.plist" file located in "\Zeal\ docsets\WordPress.docset\Contents"

The corrected content is this:

```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
<key>isJavaScriptEnabled</key><true/><key>CFBundleIdentifier</key>
<string>wordpress</string>
<key>CFBundleName</key>
<string>WordPress</string>
<key>DocSetPlatformFamily</key>
<string>wordpress</string><key>DashDocSetBlocksOnlineResources</key><true/><key>DashDocSetFamily</key><string>unsorteddashtoc</string><key>dashIndexFilePath</key><string>codex.wordpress.org/index.html</string>
<key>isDashDocset</key>
<true/></dict>
</plist>
```

**Comment by Yabla1** [comment] 2022-04-29 07:17
@[albertomarun](https://github.com/albertomarun) thank you, this solved the viewing issue. now there"s another issue: All the text is displayed in _italic_
![cnB9wig](https://user-images.githubusercontent.com/44240084/165900318-576cfe54-a940-4c94-a8fc-d0c25e03d9c6.png)

**Comment by trollixx** [comment] 2023-04-15 05:55
Duplicate of #1316. This should be fixed in the `main` branch. Please try the latest [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build.

**Closed by trollixx** 2023-04-15 05:55 UTC
