### ISSUE TITLE
Crystal Docset

### ISSUE THREAD

**Issue by chun49** [zealdocs/zeal#550] opened 2016-05-27 16:35 UTC
please,add crystal-lang doc

**Comment by trollixx** [comment] 2016-05-28 03:48
No need to redact the original message, simply closing the issue is fine. Crystal docset is available [here](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Crystal).

**Closed** 2016-05-28 03:49 UTC
Labels: Component: Docsets, Resolution: Invalid, Type: Question

**Comment by chun49** [comment] 2016-06-01 13:21
why not include official docs and standard lib API??

**Comment by chun49** [comment] 2016-06-01 13:21
sorry my english so bad..

**Comment by trollixx** [comment] 2016-06-01 13:39
It's a wrong place to ask such questions. All docsets are coming from Dash,
and at the moment Zeal provides direct access to the official docsets only.
Please follow #170 for the progress on allowing to download user
contributed docsets within the app.
