### ISSUE TITLE
Zeal 0.6.1 crashes at open Java SE18 documentation

### ISSUE THREAD

**Issue by milen-prg** [zealdocs/zeal#1429] opened 2022-09-24 07:19 UTC
Zeal 0.6.1 crashes at open only Java SE18 documentation. Other docsets works properly.

**Comment by trollixx** [comment] 2022-10-02 18:52
Duplicate of #868. Please use version built from the `master` branch until v0.7.0 is out.

**Closed by trollixx** 2022-10-02 18:52 UTC

**Comment by KeZhimin** [comment] 2022-10-09 01:24
> 

when will v0.7.0 arrive
