### ISSUE TITLE
No cursor when search box in focus

### ISSUE THREAD

**Issue by mjs7231** [zealdocs/zeal#156] opened 2014-06-06 19:26 UTC
When the search box is in focus there is no cursor.  Its hard to tell I am in the right spot to start typing my search.  Once again it should be noted no other apps on my system display this behavior.

* If there is text in the search box when I focus the cursor appears as normal and stays even if i delete all the text in the box.
* If I focus when there is no text in the box, there is no cursor when selecting the search input (even after typing something). The input also doesn't get the orange border like it does when the text box is in focus.
* If there is no text in the box and I click and drag my mouse across the input (as if selecting everything) in the box, then it highlights and I get the cursor like one would expect.
* If I double-click the empty search input it also works as expect.

OS: Linux Mint 16
Controls Theme: Numix

**Comment by trollixx** [comment] 2015-02-10 04:34
I cannot reproduce the problem, I guess it has been fixed by #190.

**Closed by trollixx** 2015-02-10 04:34 UTC
