### ISSUE TITLE
Feature Request: Multiple (Search Path) "Docset Storage" locations

### ISSUE THREAD

**Issue by sdowdy** [zealdocs/zeal#615] opened 2016-10-08 01:25 UTC
Just started using this nice tool! (so i could be missing something)

I would like to be able to pre-install docsets into a common (NFS) directory for users to have access to that is centrally managed, with a fallback/override user-specific directory.  Implementation via a Search Path style Environment Variable (and compile-time default selection for paths) would be great.  This would keep from having to replicate downloaded sets on every user machine, and also help users get going right off the bat.  (of course things like a user being able to load a newer/updated docset version if the common lower-priority directories were stale -- especially since they'll be readonly, would be required).   Even if this were implemented as simply something like two  known pathing components in settings:
   docsetPath=...
   docsetPathCommon=...
(two paths only, and not a true SearchPath EnvVar), that'd still be much more useful for my needs.
(or adding an EnvVar at all for pointing to docsets and being able to override the XDG Config Zeal->[docsets]->path setting on-demand by command line in a separate forced instance)

btw, it'd be useful if the "Show Zeal" Global key shortcut (Meta+Z) was a toggle

Thanks much,
--stephen

**Comment by trollixx** [comment] 2016-10-08 15:35
This is a duplicate of #516.

> btw, it'd be useful if the "Show Zeal" Global key shortcut (Meta+Z) was a toggle
It is a toggle at the moment, I am not sure I want to keep it that way.

**Closed by trollixx** 2016-10-08 15:35 UTC
