### ISSUE TITLE
Windows x64 version crashed on start even though VC++ 2015 redist installed

### ISSUE THREAD

**Issue by sv158** [zealdocs/zeal#1305] opened 2020-12-28 09:01 UTC
Recently I installed VC++ 2019 redist both x86 and x64 versoin, and this make the 2015, 2017 and 2019 version merge into a single one which called `Microsoft Visual C++ 2015-2019 Redistributable`(x86/x64).

Today I tried to start Zeal(0.6.1, x64) but the window froze few seconds and then exited without any prompt. So I tried to download a newer version of Zeal but found that my installed version is the latest version(0.6.1). However, this time I noticed that the mention on the download page, so I uninstalled the VC++ redist 2015-2019, and reinstalled 2015,2017,2019 one by one, although I finally got the VC++ redist 2015-2019 again.

Zeal still crashed on start after I reinstalled VC++ redist. Then I think this problem in another way, so I downloaded a portable x86 version, and this version works fine with VC++ 2015-2019 redist.

There maybe something wrong inside the x64(msi) version.

**Comment by trollixx** [comment] 2023-09-17 18:46
This is old but probably a duplicate of #889.

**Closed by trollixx** 2023-09-17 18:46 UTC

**Comment by enginespot** [comment] 2024-02-18 03:12
Hi @trollixx 

I have tested the latest version of Zeal(0.7.0), whether it is installed through the Installer or Portable, it will prompt that Visual C++ related packages are missing. I tried to install Visual C++ Redistributable for Visual Studio 2015, but it failed

and in the end, I was able to run zeal well by install [Latest Microsoft Visual C++ Redistributable Version successful](https://aka.ms/vs/17/release/vc_redist.x64.exe)

Related introduction: https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc -170

Hope it can be helpful
