### ISSUE TITLE
Add custom docset keywords

### ISSUE THREAD

**Issue by mattkatz** [zealdocs/zeal#355] opened 2015-06-24 22:39 UTC
A fine feature from @Kapeli 's dash is the ability to change the docset keyword. 
This is useful for docsets you query often - I change angular: to ng: and so on.

**Comment by trollixx** [comment] 2015-06-25 05:06
Thanks for your feedback. This is actually a duplicate of #167. I think it will be part of the new docset management system (#354), but there is no ETA yet.

**Closed by trollixx** 2015-06-25 05:06 UTC
