### ISSUE TITLE
Windows: Zeal crashes downloading c++ docsets

### ISSUE THREAD

**Issue by illava** [zealdocs/zeal#757] opened 2017-08-07 02:40 UTC
When the downloading process reached 99% and ready to install, it crashes. Works fine with other type of docsets(mysql doc I just installed).
![default](https://user-images.githubusercontent.com/29905553/29010192-223f336e-7b5c-11e7-906a-049c79144797.PNG)

**Comment by trollixx** [comment] 2017-08-09 20:52
Please check your docset storage folder, and try removing any leftovers from the C++ docset.

**Comment by illava** [comment] 2017-08-24 02:28
The problem solved by doing that, thank you.

**Comment by trollixx** [comment] 2017-10-07 21:15
I think this is also a duplicate of #788.

**Closed by trollixx** 2017-10-07 21:15 UTC
Labels: Component: Docset Manager, Resolution: Need More Info, Type: Defect
