### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by feixia5712** [zealdocs/zeal#832] opened 2017-11-30 01:26 UTC
![image](https://user-images.githubusercontent.com/12670758/33408237-64a9558c-d5b0-11e7-8747-51cdd1a999a6.png)

System version：win10

**Comment by trollixx** [comment] 2017-11-30 02:56
Remove `HTML.docset` from the docset storage directory.

**Comment by feixia5712** [comment] 2017-11-30 13:21
ok Thanks

**Comment by trollixx** [comment] 2017-12-01 19:40
Duplicate of #788.

**Closed by trollixx** 2017-12-01 19:40 UTC
