### ISSUE TITLE
C++ docset download 404

### ISSUE THREAD

**Issue by nishanthkarthik** [zealdocs/zeal#1537] opened 2023-09-16 21:40 UTC
![image](https://github.com/zealdocs/zeal/assets/7759435/20a255f6-1b14-49a8-8695-6d07d4d1b13f)

Version ref v0.6.2-dev.309+cee4e50 on archlinux built from zeal-git

**Comment by trollixx** [comment] 2023-09-17 03:49
![image](https://github.com/zealdocs/zeal/assets/714940/dddafd1c-18bc-4209-af3f-be3635b13488)

Looks like another Next.js bug. For whatever reason dynamic route parameter loses plus signs when deployed on Vercel. It does work as expected locally.

Interestingly URL-encoding `C++` solves the problem: https://go.zealdocs.org/d/com.kapeli/C%2b%2b/latest

There are multiple of reported Next.js issues with similar problems:
* https://github.com/vercel/next.js/issues/48058
* https://github.com/vercel/next.js/issues/49646
* https://github.com/vercel/next.js/issues/52938
* https://github.com/vercel/next.js/issues/53426

At the same time some of the issues describe problems with processing `@` and `-` characters, which worked fine in my tests. So I may need to create another issue.

I think I have an ugly workaround until the problem is addressed by Vercel.

**Closed** 2023-09-17 03:52 UTC
Labels: type/defect, scope/misc/api-server

**Comment by trollixx** [comment] 2023-09-17 03:55
I deployed the fix. Thanks for reporting the issue.

**Comment by nishanthkarthik** [comment] 2023-09-17 03:57
Thanks for the quick fix! I can confirm it works again here

**Comment by milovangudelj** [comment] 2023-09-21 20:54
This is embarassng... :sweat_smile:

My issue (vercel/next.js#52938) was not what I thought. I misunderstood how Next.js treated dynamic params not generated at build time. The 'fix' was to export a config option from the route to show a 404 page for any parameter that hadn't already been generated. Here are the docs for that: [`dynamicParams`](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamicparams).

So I believe it was irrelevant for this issue.
