### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by rookie-lian** [zealdocs/zeal#1488] opened 2023-04-14 09:35 UTC
Sometimes when clicking on the API that needs to be displayed, the page will become blank. Sometimes it will even automatically exit, and this happens frequently.

**Comment by rookie-lian** [comment] 2023-04-14 09:37
java api ,when you click  java19 api ,app will auto exit

**Comment by trollixx** [comment] 2023-04-15 00:11
Please only use English when creating issues.

Sounds like duplicate of #868 and #1119. Both are fixed in the `main` branch. You can give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try. Binaries are attached to each build

**Closed** 2023-04-15 00:12 UTC
Labels: resolution/duplicate, type/defect, scope/ui/webview

**Comment by rookie-lian** [comment] 2023-04-21 02:04
oh ,yeah,than you very much.wish you do better ,
