### ISSUE TITLE
Any plans for cheatsheets and snippets support?

### ISSUE THREAD

**Issue by tacocats** [zealdocs/zeal#1242] opened 2020-06-21 20:12 UTC
This is more out of curiosity, it looks like there's a lot of stuff that takes priority over this, but I know dash has support for user created cheatsheets and snippet storage. I was wondering if there's any future plans to implement cheat sheets or snippets using maybe gists in the future or a local database? Is this something for example zeal would accept if someone were to work on implementing features like that or is it out of the scope of zeal?

**Comment by trollixx** [comment] 2020-06-29 02:55
It's a duplicate of #498 (cheatsheets) and #12 (snippets).

**Closed by trollixx** 2020-06-29 02:55 UTC
