### ISSUE TITLE
zeal not working in windows8.1  64 bit 

### ISSUE THREAD

**Issue by pavanyogi** [zealdocs/zeal#794] opened 2017-10-09 08:52 UTC
![screenshot 89](https://user-images.githubusercontent.com/13834016/31330739-36c3b5d0-acfd-11e7-9491-95552db06611.png)

**Comment by trollixx** [comment] 2017-10-09 20:09
Did 0.3.1 work for you?

**Comment by pavanyogi** [comment] 2017-10-10 05:55
zeal 0.3.1 is working fine , Thanks for suggestion.

**Comment by trollixx** [comment] 2017-10-10 08:56
I am not sure what exactly is different about Windows 8.1, and the error doesn't really give away any details. 0.4.0 is built with MSVC 2015, so I'd expect it to have less issues. Do you have [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed?

**Comment by pavanyogi** [comment] 2017-10-10 12:29
i have     Microsoft Visual C++  2013 installed, i did not upgraded due to some reasons

**Comment by trollixx** [comment] 2017-10-24 19:52
2013 and 2015 are unrelated. You need 2015 to run Zeal.

**Comment by trollixx** [comment] 2017-12-12 21:15
Duplicate of #800 somehow.

**Closed by trollixx** 2017-12-12 21:15 UTC
Labels: Platform: Windows
