### ISSUE TITLE
Restore last opened tabs on startup

### ISSUE THREAD

**Issue by quanzhuo** [zealdocs/zeal#744] opened 2017-06-30 00:18 UTC
Can you add such a new feature? This feature will sometimes very useful !

**Comment by anephew** [comment] 2017-07-10 00:39
+1 This feature is missing

**Comment by trollixx** [comment] 2017-10-01 17:40
Actually a duplicate of #78 .

**Closed by trollixx** 2017-10-01 17:40 UTC
Labels: Component: UI, Type: Feature

**Comment by anephew** [comment] 2018-01-02 00:18
This feature is missing. It takes a long time to return without bookmarks (https://github.com/zealdocs/zeal/issues/290) and last tabs to the current work (

Very much waiting for the both functions!

Thanks!
