### ISSUE TITLE
Cannot search Java SE7 and Java SE8 docsets

### ISSUE THREAD

**Issue by wenLiangcan** [zealdocs/zeal#639] opened 2016-10-23 02:42 UTC
My Zeal binary was built from commit 6cb63ee. I have both JavaScript, Java SE7 and Java SE8 docsets installed but the search box can only autocomplete docset name of JavaScript. I tried to type the name of Java docsets manually but Zeal can show search results of neither Java SE7 nor Java SE8 docsets.

**Comment by bendem** [comment] 2016-10-23 09:49
try `java se7:` or `java se8`. Alternatively, `java:` will work too.

**Comment by wenLiangcan** [comment] 2016-10-23 11:42
@bendem Thank you, `java` is work, but not `java se7` nor `java se8` as I've reported.

**Comment by trollixx** [comment] 2016-10-29 04:45
Duplicate of #604.

**Closed by trollixx** 2016-10-29 04:45 UTC
