### ISSUE TITLE
Android docset is not working anymore

### ISSUE THREAD

**Issue by spectrumIG** [zealdocs/zeal#600] opened 2016-09-23 09:31 UTC
Hi, sorry if this is duplicate in some way but I search and I couldn't find anything in tracker.
Anyway, since the update of yesterday the Android docset is not working anymore. I tried to uninstall/install, download it directly from @Kapeli site but nothing. 
Maybe it's just me but i wasn't sure. 
Thanks

**Comment by trollixx** [comment] 2016-09-23 12:30
It's a duplicate of #596. You need the fresh 0.3.0 version. Not all packages and installers are ready yet, hence no announce, but you can build it yourself or get a CI build (Windows).

**Comment by spectrumIG** [comment] 2016-09-23 12:33
Thanks and I'm sorry for the duplicate issue.

**Closed** 2016-10-03 07:24 UTC
Labels: Component: Docset Registry, Component: Docsets, Resolution: Duplicate, Type: Defect
