### ISSUE TITLE
After update CSS3 and HTML5 Docsets Unable to load Content.

### ISSUE THREAD

**Issue by afajansari** [zealdocs/zeal#1171] opened 2019-12-12 19:58 UTC
After update CSS3 and HTML5 docsets I'm unable to load content of these docsets.
I want to know how to fix this bug. If you don't then please give me suggestion for solving this issue, all content of this docsets load in browser but not in applicaton.
Please fix this ASAP.
![image](https://user-images.githubusercontent.com/31520700/70744540-e4661400-1d47-11ea-9da5-21b0cc18b29b.png)

**Comment by usernamelectro** [comment] 2019-12-13 17:50
Duplicate of #1155

**Comment by wecblues** [comment] 2019-12-15 08:57
I encountered the same problem and was troubled

**Comment by JWleo** [comment] 2019-12-18 01:47
i have the same problem.how to solve it permanently?

<img width="775" alt="12" src="https://user-images.githubusercontent.com/32316654/71048680-019d4700-217b-11ea-80e1-3a4d4672023b.PNG">

but i can open it in my chrome.
![image](https://user-images.githubusercontent.com/32316654/71048780-50e37780-217b-11ea-85d3-604b70d5eeaa.png)

**Closed** 2019-12-27 04:26 UTC
