### ISSUE TITLE
Sort Search Results by Entry Name Length/Relevance First

### ISSUE THREAD

**Issue by arrrggghhh** [zealdocs/zeal#791] opened 2017-10-06 11:01 UTC
Searching "String" lists entries that contain "string" in ascending order by default.

![fuzzy off](https://user-images.githubusercontent.com/19325420/31274871-dacb97c2-aacf-11e7-8c68-7d003e6d57cf.png)

In most cases, users are looking for entries that start with search term or perfectly match, aren't they?

Currently in version 0.4.0, if you turn on fuzzy search from preferences, you get this behavior.

![fuzzy on](https://user-images.githubusercontent.com/19325420/31275111-d81641fc-aad0-11e7-8b5d-95211b3426f6.png)

I think this should be the default behavior.

Entries like xxxx.string or xxxx.yyyy(String zzz) can be further searched from sidebar.

Additionally, it would be convenient if searching supports regular expression.

**Comment by trollixx** [comment] 2018-01-02 21:36
Duplicate of #679, which is fixed in 0.5.0.

**Closed by trollixx** 2018-01-02 21:36 UTC
Labels: Component: Docset Registry (Search Engine), Type: Defect
