### ISSUE TITLE
Access to user submitted docsets

### ISSUE THREAD

**Issue by kevincianfarini** [zealdocs/zeal#1042] opened 2018-11-25 16:35 UTC
Is there any specific reason why user submitted docsets are not available for search within Zeal? #24 mentions that the Docset exchange has ended, and that was in 2013, so I'm a bit confused why we can't search through all available docsets yet.

**Comment by trollixx** [comment] 2018-11-25 19:09
Duplicate of #170.

**Closed** 2018-11-27 01:18 UTC
Labels: Component: UI/Docset Manager, Resolution: Duplicate, Type: Feature
