### ISSUE TITLE
Zeal latest version not working on Windows 10 version 10.0.16299.192

### ISSUE THREAD

**Issue by abel406** [zealdocs/zeal#907] opened 2018-03-14 15:40 UTC
Hi.I installed zeal using the latest installer zeal-0.5.0-windows-x64.msi and for some reason it does not work. Aparently it is related with the browser engine. The messsage is "A simple documentation browser. dejó de funcionar" In plain english "A simple documentation browser. stopped working".

Please, some help. Thanks.

**Comment by abel406** [comment] 2018-03-14 17:28
I tried to debug it and it shows an error with Qt5Core.dll. Could this have something to do with the reason for malfunctioning ?

**Comment by tserafim** [comment] 2018-03-14 19:50
Have you checked #889?

**Comment by trollixx** [comment] 2018-03-18 23:21
Duplicate of #889.

**Closed by trollixx** 2018-03-18 23:21 UTC
