### ISSUE TITLE
Content rendering error

### ISSUE THREAD

**Issue by Slamaio** [zealdocs/zeal#1179] opened 2020-01-14 20:10 UTC
# CSS & HTML docsets don't loading.
![image](https://user-images.githubusercontent.com/55360806/72378662-7df35d80-371a-11ea-91b6-0fc0c4b0a6c7.png)
![image](https://user-images.githubusercontent.com/55360806/72378685-89df1f80-371a-11ea-9e94-e1e720faa4aa.png)

**Comment by zeetsaay** [comment] 2020-01-15 04:09
![image](https://user-images.githubusercontent.com/29038962/72404322-2de5bc80-3755-11ea-8d1b-ce3b8529bc14.png)

**Comment by zeetsaay** [comment] 2020-01-15 04:10
**### And also Javascript**
![image](https://user-images.githubusercontent.com/29038962/72404374-5e2d5b00-3755-11ea-9799-e4ab14612695.png)

**Comment by trollixx** [comment] 2020-01-15 04:10
Duplicate of #1155.

**Closed by trollixx** 2020-01-15 04:10 UTC
Labels: resolution/duplicate, scope/ui/webview, type/defect
