### ISSUE TITLE
HTML5, CSS, JavaScript  issue

### ISSUE THREAD

**Issue by Vlad1235** [zealdocs/zeal#1169] opened 2019-11-30 18:41 UTC
Good day, when I downloaded both I try to open HTML5, CSS JavaScript alls  an error 

*Content rendering error. An unhandled error occurred in the application. We apologize for the inconvenience!*

So far did not meet same issue with other downloads.

**Comment by kikitte** [comment] 2019-12-01 11:45
> Good day, when I downloaded both I try to open HTML5, CSS JavaScript alls an error
> 
> _Content rendering error. An unhandled error occurred in the application. We apologize for the inconvenience!_
> 
> So far did not meet same issue with other downloads.

me too, but there is not problem with the older version of html, css, js.

**Comment by jaller94** [comment] 2019-12-02 09:11
Duplicate of #1155.

**Comment by Vlad1235** [comment] 2019-12-02 10:38
Awaiting for the resolve.

**Closed** 2019-12-02 10:38 UTC

**Comment by sandywu988** [comment] 2019-12-03 19:51
same issue here, have it solved?

**Comment by drizzer** [comment] 2020-05-11 21:58
Problem still until this date persistant with docsets(HTML, CSS, JS). **Zeal v0.6.1**

> "Content rendering error.
> An unhandled error occurred in the application. We apologize for the inconvenience!"

![Annotation 2020-05-11 235723](https://user-images.githubusercontent.com/46766033/81616119-35576280-93e3-11ea-8698-cb96dc17a326.png)
