### ISSUE TITLE
Italic Fonts on some Docs

### ISSUE THREAD

**Issue by elnasdgreat** [zealdocs/zeal#658] opened 2016-11-19 08:52 UTC
Some of the Docs have italic fonts. Like the PHP doc. All of it is in italic font!
Can you please add an option for changing the fonts?
![1](https://cloud.githubusercontent.com/assets/19590512/20454332/85fd4bc2-ae78-11e6-8005-fbfcbc725261.jpg)

**Comment by trollixx** [comment] 2016-12-18 15:41
This is another Qt WebKit issue :( Should be fixed when we switch to the new version of the engine. Marking as a duplicate of #359.

**Comment by trollixx** [comment] 2017-08-23 20:55
Actually, I see this problem with the new Qt WebKit. Italic is coming from somewhere else...

**Comment by trollixx** [comment] 2017-08-23 21:57
Somehow commenting the following in the CSS for Fira Sans font fixes the problem:

```
url('fonts/Fira/ttf/FiraSans-Book.ttf') format('truetype')
...
url('fonts/Fira/ttf/FiraSans-Medium.ttf') format('truetype')
```

Viewing php.net in Zeal also displays this bug.

**Comment by trollixx** [comment] 2017-08-23 21:58
Still looks like Qt WebKit bug, just a different one...

**Comment by trollixx** [comment] 2017-08-23 22:03
And here's the bug: annulen/webkit#270.

**Comment by annulen** [comment] 2019-02-13 19:22
Fix will be released in Qt 5.12.3, see https://bugreports.qt.io/browse/QTBUG-73660

**Comment by trollixx** [comment] 2019-02-16 03:54
@annulen thanks for the update!

I'll resolve the issue once we ship a new release with updated Qt.

**Comment by trollixx** [comment] 2019-03-27 03:40
[Looks like](https://github.com/qt/qtbase/commit/736cc1d564a204f66b2a3dd8e12a34b64a38d971) the fix made it into 5.12.2. Will be released with v0.7.0 binaries.

**Closed** 2020-04-26 23:17 UTC
Labels: resolution/done, resolution/upstream-problem, scope/packaging, scope/ui/webview, type/defect

**Comment by DenesKellner** [comment] 2021-06-05 20:55
A horrible hack until the real solution happens:

- Go to `...../PHP.docset/Contents/Resources/Documents/www.php.net/manual`
- Find all `<body class="docs " style="">`
- Replace all to `<body class="docs " style="font-family:sans-serif">`

Yes it's a lot to replace.
But after that, it's a relief.

**Comment by Nickieros** [comment] 2022-10-30 11:14
> Somehow commenting the following in the CSS for Fira Sans font fixes the problem:
> 
> ```
> url('fonts/Fira/ttf/FiraSans-Book.ttf') format('truetype')
> ...
> url('fonts/Fira/ttf/FiraSans-Medium.ttf') format('truetype')
> ```
> 
> Viewing php.net in Zeal also displays this bug.

@trollixx thanks, this works
I found this CSS file which contains FiraSans @font-face in PHP.docset\Contents\Resources\Documents\www.php.net\
and used regex to comment all FiraSans urls with truetype format in this file:
```
use regex
/(.*format\(\'truetype\'\))/
to replace it with
/*$1*/
```
