### ISSUE TITLE
what should I do?  Content rendering error An unhandled error occurred in the application. 

### ISSUE THREAD

**Issue by cloud-21** [zealdocs/zeal#1237] opened 2020-06-08 10:05 UTC
![20200608180345](https://user-images.githubusercontent.com/28580944/84018486-ae31e600-a9b2-11ea-840f-28c34889d44d.png)

**Comment by bruznic** [comment] 2020-06-09 16:37
I and a classmate have the same exact problem in the JavaScript documentation

**Comment by dc-rose** [comment] 2020-06-11 17:36
I have the same issue on javascript and on html.

**Comment by trollixx** [comment] 2020-06-13 23:08
Duplicate of #1155. This issue is fixed in the master branch, but a number of regressions introduced from migration to Qt WebEngine prevents me from cutting the next release quickly :(

**Closed by trollixx** 2020-06-13 23:08 UTC

**Comment by yekanchi** [comment] 2020-06-14 04:20
> 
> 
> Duplicate of #1155. This issue is fixed in the master branch, but a number of regressions introduced from migration to Qt WebEngine prevents me from cutting the next release quickly :(

where we can download **portable version for windows** before release? i couldn't find it in github actions for repo

**Comment by trollixx** [comment] 2020-06-14 15:07
> Where we can download latest build of **portable version for windows** before release?

https://ci.appveyor.com/project/zealdocs/zeal

Binary artifacts for Windows haven't been moved to GitHub Actions yet.
