### ISSUE TITLE
Provide help for keyboard shortcuts somewhere

### ISSUE THREAD

**Issue by Yanpas** [zealdocs/zeal#693] opened 2017-02-21 12:35 UTC
`Ctrl+K` is very useful kb shortcut. If only I could find it in help or accelerator (in the right side of menu entry). Some other tips would be useful too if exist

**Comment by trollixx** [comment] 2017-02-22 03:54
Actually, it's a duplicate of #72. One day I'll do that :)

**Closed by trollixx** 2017-02-22 03:54 UTC
Labels: Component: Documentation, Resolution: Duplicate, Type: Enhancement
