### ISSUE TITLE
It doesn't go directly to the part I want

### ISSUE THREAD

**Issue by LauLandWalker** [zealdocs/zeal#338] opened 2015-05-18 16:41 UTC
after I typed out something in the search field, the results starts at the top instead of going directly on the part where it should be, so i need to select it again on the 'see also' to be directed on the part I want.

**Comment by trollixx** [comment] 2015-05-18 20:39
Duplicate of #328. Fixed in 0.1 branch and will be released shortly in 0.1.2.

**Closed by trollixx** 2015-05-18 20:39 UTC
Labels: duplicate
