### ISSUE TITLE
Depending search

### ISSUE THREAD

**Issue by dix75** [zealdocs/zeal#591] opened 2016-09-09 08:38 UTC
Can you add a new type of search, only for the current docset.
for example:
- I want search only in the jquery library? the second time I want something find in the C++ library and so on.  

It would be very useful.

**Comment by trollixx** [comment] 2016-09-11 17:20
You can use `cpp:` prefix to search in the C++ docset, `jquery:` for jQuery.

**Comment by dix75** [comment] 2016-09-12 19:39
Thanks. Greate!
A What about another combobox with those prefixes?

**Comment by trollixx** [comment] 2016-09-12 19:52
Yeah, something like that is definitely required.

**Comment by trollixx** [comment] 2017-04-09 04:06
Marking as a duplicate of #716.

**Closed by trollixx** 2017-04-09 04:06 UTC
Labels: Component: Docset Registry, Resolution: Duplicate, Type: Enhancement
