### ISSUE TITLE
Feature request: allow the the user to enable or disable docsets

### ISSUE THREAD

**Issue by abtxu** [zealdocs/zeal#1362] opened 2021-10-25 11:12 UTC
When multiple docsets are installed, then some search terms may hit results in numerous docsets. 
I know the search result can be filtered by something like "css: ", but why not simply allowing the user to disable unwanted docsets?
Thanks in advance.

**Comment by trollixx** [comment] 2023-09-17 18:36
Duplicate of #77.

**Closed by trollixx** 2023-09-17 18:36 UTC
