### ISSUE TITLE
No support for high DPI displays

### ISSUE THREAD

**Issue by Djcoper** [zealdocs/zeal#1133] opened 2019-09-10 00:27 UTC
![Screenshot from 2019-09-10 01-23-08](https://user-images.githubusercontent.com/30577249/64575074-f8c1fb80-d369-11e9-9128-26aa7de9ccd5.png)

**Comment by trollixx** [comment] 2019-09-29 05:56
Duplicate of #869. Please see the ticket for some workaround to try.

**Closed by trollixx** 2019-09-29 05:56 UTC
