### ISSUE TITLE
When clicking to open the Spring Framework document, the software crashes

### ISSUE THREAD

**Issue by 2894462606** [zealdocs/zeal#1530] opened 2023-09-05 05:26 UTC
After installing Spring Framework, clicking to open Spring Framework in the list causes the software to crash.

**Comment by trollixx** [comment] 2023-09-08 03:58
Duplicate of #868.

Until v0.7.0 is released, please build Zeal from `main` or give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try.

**Closed by trollixx** 2023-09-08 03:58 UTC
