### ISSUE TITLE
threading/async(?) issues causing crashing and partial results list display

### ISSUE THREAD

**Issue by binki** [zealdocs/zeal#801] opened 2017-10-18 18:38 UTC
When I type fast in the search box, Zeal often becomes Not Responding and crashes (WER comes up) or sometimes renders just the upper half of the results listing box and I have to edit my search terms (e.g., remove and retype a char) to get it to redraw and display the list properly.

I didn’t see this behavior until updating to Zeal-0.4 (I updated because the prior version prompted me to). It’s like it’s trying to be more async/thready or something but it seems to be walking all over itself without synchronizing some things that need to be synchronized. I’d rather zeal run more slowly with the guarantee that it won’t crash than require me to restart it all the time which ends up taking longer.

Crashes and incorrect results list drawing seems more likely to happen if the PC is loaded down and things are generally running slower. Also, I mostly use the .net docset which is quite large. Also, I use zeal-0.4.0 on Windows.

**Comment by trollixx** [comment] 2017-10-21 11:49
Not sure how exactly to reproduce your problem. We really need a crash reporter to catch such issues.

**Comment by binki** [comment] 2017-11-08 18:31
More evidence of something like threading/synchronization issues is pictured. When I click on `Fragment`, I get `GetHashCode()`. When I click `Host`, I get `Password`. This is immediately after “typing fast”:

![image](https://user-images.githubusercontent.com/82626/32567149-68713826-c488-11e7-8c88-eb1d6de8b9ac.png)
![image](https://user-images.githubusercontent.com/82626/32567157-70018eba-c488-11e7-8b5e-b1f2f9a99216.png)

If I let it settle and then change characters—for example, typing an additional character that doesn’t change results—it catches up and fixes the problem:

![image](https://user-images.githubusercontent.com/82626/32567230-a8bce72c-c488-11e7-9ed5-2cd6c8ec46b7.png)
![image](https://user-images.githubusercontent.com/82626/32567273-c7508e3c-c488-11e7-9aee-9c85f33c8fd7.png)
![image](https://user-images.githubusercontent.com/82626/32567280-ce451140-c488-11e7-8f97-03c76c0c4857.png)

About dialog:
![image](https://user-images.githubusercontent.com/82626/32567298-d677df32-c488-11e7-91c4-8552aa948ac2.png)

**Comment by binki** [comment] 2017-11-08 20:27
Because of how `m_cancellationToken` is shared in https://github.com/zealdocs/zeal/blob/4769b7a228500105f3bae8e7beba0fc4046785ef/src/libs/registry/docsetregistry.cpp#L175 , it is possible for multiple queued `_runQuery` to run to completion. It looks like that is not intentional. However, I don’t see why this would be an issue. Maybe the UI doesn’t handle receiving multiple outdated `SearchModel::updated`? Aaaand, yeah, this does not seem to be the issue ;-).

I reproed a crash under debugger and got:

> Exception thrown at 0x00007FFBD3092352 (sqlite3.dll) in zeal.exe: 0xC0000005: Access violation reading location 0x0000000000000055.

```
>	sqlite3.dll!00007ffbd3092352()	Unknown	No symbols loaded.
 	sqlite3.dll!00007ffbd30ca6f3()	Unknown	No symbols loaded.
 	sqlite3.dll!00007ffbd3054bf1()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1ccff76()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1cc7997()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1cb8937()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1cb9e03()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1cb8e3e()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1cb8a3a()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1cb88e3()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1cbe2e3()	Unknown	No symbols loaded.
 	zeal.exe!00007ff7d1cbd0ee()	Unknown	No symbols loaded.
 	Qt5Concurrent.dll!0000000073c9129b()	Unknown	No symbols loaded.
 	Qt5Core.dll!00000000730b3267()	Unknown	No symbols loaded.
 	Qt5Core.dll!00000000730b6921()	Unknown	No symbols loaded.
```

Unfortunately, I don’t have symbols.

I was able to get it to crash by typing “uribuilder” after the keyword “net:” a bunch of times as fast as I could using the NET_Framework.docset which I appear to have downloaded in 2016-10-14.

If you can point me to symbols to load into VS I can try reproing it and get a better call stack. I’m uploading the mini dump I got. The version with heap is 317MB, so I assume GitHub wouldn’t let me share that, so this is heapless:
[zeal-noheap.zip](https://github.com/zealdocs/zeal/files/1455305/zeal-noheap.zip)

**Comment by trollixx** [comment] 2017-11-10 22:32
Thanks for debugging this! Indeed seems like a concurrent access bug.

**Comment by trollixx** [comment] 2018-09-16 05:45
@binki Do you still experience this problem with 0.5.0 or 0.6.0?

**Comment by trollixx** [comment] 2018-10-25 07:55
Closing, since I can't reproduce this anymore.

**Closed by trollixx** 2018-10-25 07:55 UTC
Labels: Component: Docset Registry (Search Engine), Resolution: Unable To Reproduce, Type: Defect
