### ISSUE TITLE
Zeal doesn't display any menus - no way to get docsets!

### ISSUE THREAD

**Issue by feoh** [zealdocs/zeal#213] opened 2014-10-30 22:04 UTC
KUbuntu 14.04.1

Since there is no Edit or other menu, I can't figure out how to get new docsets.

![image](https://cloud.githubusercontent.com/assets/330070/4852908/9bcd7f64-6080-11e4-9188-f5bf2c71d812.png)

**Comment by trollixx** [comment] 2015-01-10 20:51
Closing as a duplicate of #185 and #134.

**Closed by trollixx** 2015-01-10 20:51 UTC
