### ISSUE TITLE
Too many files

### ISSUE THREAD

**Issue by josephernest** [zealdocs/zeal#904] opened 2018-03-11 22:26 UTC
When installing ~10 docsets, I noticed that the `docsets` folder:

* uses 3 or 4 GB (that's not a problem at all)
* uses something like 100k or 200k files: that's really big, and thus it probably increases +30% the number of files I'm using since 5 years ;) 

Then it's slow when moving the folder from a partition to another (more than 10 minutes on a SSD!) 

**Question: isn't there a way to let a docset in a file package?** something like `wordpress.docset`, instead of using 60k files?

Wouldn't it be a cleaner design to have "packages" instead of hundreds of thousands of files?

Edit: Another problem : filenames/paths are often too long on Windows platform (leading to error message). Example of file with a too long filename:

    C:\Users\User\Desktop\zeal-portable-0.5.0-windows-x86\docsets\JavaScript.docset\
    Contents\Resources\Documents\developer.mozilla.org\en-US\docs\Games\Techniques\
    3D_collision_detection\Games\Techniques\
    3D_collision_detection\Bounding_volume_collision_detection_with_THREE.html

Thanks in advance, and congrats again for Zeal which is really great.

**Comment by trollixx** [comment] 2018-03-16 21:40
Duplicate of #138, please subscribe to it for updated.

**Closed by trollixx** 2018-03-16 21:40 UTC
