### ISSUE TITLE
Tray icon on Ubuntu Unity does not show correctly

### ISSUE THREAD

**Issue by dslul** [zealdocs/zeal#408] opened 2015-09-22 20:42 UTC
On Unity the tray icon should be on the right, but here it has this strange behaviour

![zeal](https://cloud.githubusercontent.com/assets/6121202/10030997/f198e194-617a-11e5-9098-2152cc5a6c23.png)

**Comment by trollixx** [comment] 2015-09-26 03:09
Duplicate of #321. There's a fix in 0.1 branch, but it hasn't been released yet.

**Closed by trollixx** 2015-09-26 03:09 UTC
