### ISSUE TITLE
How to get a previous version of a docset?

### ISSUE THREAD

**Issue by CodeShark37** [zealdocs/zeal#1663] opened 2024-10-08 13:10 UTC
I updated the docset from Vue2 to Vue3 but now I want to go back to the previous version, in this case Vue2, how do I do that? Is it possible to maintain both versions at the same time?

**Comment by HotStew** [comment] 2024-10-30 08:06
I ran into this same problem but with a different docset.

Docsets are source from Kapeli, the creators of Dash. I found the docset feeds here: https://github.com/Kapeli/feeds
If you navigate to `VueJS.xml` and open the file, you'll see there are many versions listed under the <other-versions> element. These are the versions that are available and provided by Kapeli.

What you need to do is to download that file, or just copy the contents and save it as .xml, and also change the <version> element's value at the very top to your desired version. Then in Zeal go to Tools -> Docsets... in your navigation bar, click on add feed and then paste in `file://[/absolute/path/to/xml]`

Unfortunately Zeal will save this docset without an icon and you also can't rename docsets.

Maybe there could be some development ideas here @trollixx ?
- Support for adding different versions of a docset
- Ability to rename docsets

**Comment by trollixx** [comment] 2024-11-05 03:11
This is a duplicate of #208. Due to the change in how Dash releases some docsets, I want add this feature in v0.8 series.

**Closed by trollixx** 2024-11-05 03:11 UTC
