### ISSUE TITLE
The zeal v3.0 can not be called by sublime text 3 zeal plugin

### ISSUE THREAD

**Issue by yosaku01** [zealdocs/zeal#617] opened 2016-10-08 10:38 UTC
When I updated my zeal to version 3.0, and want to call it from sublime text 3 by zeal plugin(I used shift + F1 shortcut key).
Some error happens.
The wrong message is:
Unknow option 'query'.
Please update the zeal plugin to be compatible with Zeal v3.0. Thank you.
My Os is Windows 7 64bit Sp1

**Comment by trollixx** [comment] 2016-10-08 15:22
Duplicate of #610.

**Closed by trollixx** 2016-10-08 15:22 UTC
Labels: Component: Plugin Support, Resolution: Duplicate, Type: Defect
