### ISSUE TITLE
Non-monospace fonts used for some code

### ISSUE THREAD

**Issue by Kwpolska** [zealdocs/zeal#562] opened 2016-07-16 08:54 UTC
On Arch Linux, Zeal has some issues with `font-family: monospace;` or equivalent. Django docs are rendered with a bitmap version of Helvetica. Vim, Python, Bash docs are rendered with Helvetica Neue, the sans-serif font on my OS.

**Comment by bradst** [comment] 2016-07-20 00:12
I've noticed this as well, using Arch Linux. Python 3, SciPy, Sass, and jQuery are some of the affected docsets. All inline code and code blocks are shown in variable-width font. The affected local files display properly in Firefox and Chromium. Interestingly, other docsets including CSS, Rust, and TypeScript are not affected; they show correctly monospaced fonts in Zeal.

**Comment by trollixx** [comment] 2016-07-20 02:14
It's a problem with the deprecated Qt WebKit module that is still in use. The are other related issues like #359 and #468. Building with Qt WebEngine fixes the rendering, but there some lacking features. 

Switching to https://github.com/annulen/webkit might be a good solution as well, but I haven't got time to test that myself.

**Comment by SyrakuShaikh** [comment] 2016-12-15 08:56
I'm using the latest `zeal-git` v0.3.1 in archlinux and the problems mentioned above are still the same.
The codes in `Python_3` docset cannot use the right monospace font and therefore cannot be aligned well.

Is there a workaround now? Thanks!

**Comment by bradst** [comment] 2016-12-15 17:12
@SyrakuShaikh Here's what I've been doing to manually enable WebEngine:

Add the following flag to the `qmake-qt5` call in the `PKGBUILD`:

```
CONFIG+=zeal_qtwebengine
```

Then add `qt5-webengine` to the `depends` array, and rebuild the package.

**Comment by SyrakuShaikh** [comment] 2016-12-16 01:26
Many thanks @bradst ! Rebuilding the package with `qt5-webengine` works and `zeal` now is almost perfect!

**Comment by trollixx** [comment] 2016-12-16 03:10
While using Qt WebEngine should indeed fix all rendnering issues, Zeal lacks proper support for it, and there are way more UX bugs with it. As I said above, my hope is that with the revived Qt WebKit all those issues will go away.

For now I'm marking this issue as a duplicate of #359 just to avoid multiple tickets about the same issue.

**Closed by trollixx** 2016-12-16 03:10 UTC
Labels: Component: Web View, Resolution: Upstream Problem, Type: Defect
