### ISSUE TITLE
Crashes Rust docset

### ISSUE THREAD

**Issue by Niakr1s** [zealdocs/zeal#963] opened 2018-07-23 16:32 UTC
Actually I used zeal for a while (thanks for this great app!), and everything was fine. And I used Rust docset for a month or so without any problem, and now I got crashes almost every time I try to search smth in Rust docset. I tried to reinstall and redownload docsets. Other docsets I am using work just fine as usual, I even tried Java EE8, that was mentioned above, it works impeccable.
OS: Windows 7 x64, Zeal 0.5.0

> Имя сбойного приложения: zeal.exe, версия: 0.5.0.0, отметка времени: 0x5a359a9b
> Имя сбойного модуля: Qt5WebKit.dll, версия: 0.0.0.0, отметка времени 0x5a346143
> Код исключения: 0xc0000005
> Смещение ошибки: 0x00000000002fcf8e
> Идентификатор сбойного процесса: 0xadc
> Время запуска сбойного приложения: 0x01d4229ecae96d6b
> Путь сбойного приложения: D:\Progs\zeal\zeal.exe
> Путь сбойного модуля: D:\Progs\zeal\Qt5WebKit.dll
> Код отчета: 0b8591c6-8e92-11e8-8d27-00265a6bc51d

Add: Crashes occur even on my manjaro linux! (Zeal 0.6.0)

**Comment by richarson** [comment] 2018-08-02 15:47
Did you, by any chance, recently installed Oracle's JDK on Manjaro?
Check out #802 

I don't think this afects Windows also.

**Comment by trollixx** [comment] 2018-08-03 02:13
The original report is for Windows, but I really cannot reproduce it. @Niakr1s please try to redownload the Rust docset.

**Comment by Niakr1s** [comment] 2018-08-03 03:49
@richarson Actually I moved from Manjaro to Kubuntu, on fresh Kubuntu rust works

**Comment by Niakr1s** [comment] 2018-08-03 03:51
@trollixx redownloaded, same error

**Comment by trollixx** [comment] 2018-08-22 02:42
Please reopen if the problem resurfaces, closing for now.

**Closed by trollixx** 2018-08-22 02:42 UTC
Labels: Component: UI/Web View, Resolution: Unable To Reproduce, Type: Defect
