### ISSUE TITLE
minimum window width

### ISSUE THREAD

**Issue by basaran** [zealdocs/zeal#1271] opened 2020-08-18 15:02 UTC
Zeal 0.6.1
Windows 10 2004

I'm not able to reduce the width of the main window less than 756px more or less a few pixels. This is causing an issue when using a window manager such as Powertoys, Divvy, etc. as the window overflows the predefined screen margins.

Even without a window manager, It would be nice if the window would get more narrow. Arguably, narrow text is easier to read (as in newspapers) than wide text.

![image](https://user-images.githubusercontent.com/30809170/90529540-d4f26280-e141-11ea-815c-a01900e70ce0.png)

**Comment by trollixx** [comment] 2020-08-19 03:14
Duplicate of #954. It was fixed in 0b45d6ebeab4943fd4ad88311e422f8190ebdf51. Will be released in v0.7.0.

**Closed by trollixx** 2020-08-19 03:14 UTC
