### ISSUE TITLE
[SUGGESTION] An option to disable a specific or many documentations

### ISSUE THREAD

**Issue by AnDroidEL** [zealdocs/zeal#366] opened 2015-07-03 20:44 UTC
When I have many documentations and I execute the Zeal software, my PC begin to stay slow because have very documentations to load. Is it possible add this option to disable documentations (ie. don't delete)?

**Comment by trollixx** [comment] 2015-07-05 15:09
Hi, thanks for the feedback. This report is actually a duplicate of a really old one #77. I can't give any estimates, but it will be implemented one day.

**Closed by trollixx** 2015-07-05 15:09 UTC

**Comment by AnDroidEL** [comment] 2015-07-05 20:26
Oh... I'm sorry. Thanks for answering! I didn't see this.
