### ISSUE TITLE
php document display language

### ISSUE THREAD

**Issue by fzls** [zealdocs/zeal#551] opened 2016-06-07 10:21 UTC
The content of the document displayed in something like chars in French, but when i copy it to other place or open it in browser, it displayed in English, do you know what cause this?
ps: the cpp and Python documents works normally in my machine, only php happens something like this.
![2016-06-07_181603](https://cloud.githubusercontent.com/assets/13483212/15854467/9449c430-2cdc-11e6-8c87-96aa9719b97f.png)

**Comment by trollixx** [comment] 2016-06-08 01:38
WOW, this is just insane! I have no idea how such corruption could happen. Are you sure PHP is the only docset affected?

**Comment by trollixx** [comment] 2016-06-08 01:39
Also, details about your OS and Zeal version would be helpful.

**Comment by fzls** [comment] 2016-06-08 01:56
Well, thanks for your timely reply.

My operating system is Win 10, and I just checked all the documents I downloaded, and find that only PHP appeared to be this strange .

 

 

发件人: Oleg Shparber [mailto:notifications@github.com] 
发送时间: Wednesday, June 8, 2016 9:38 AM
收件人: zealdocs/zeal <zeal@noreply.github.com>
抄送: 风之凌殇 <1054073896@qq.com>; Author <author@noreply.github.com>
主题: Re: [zealdocs/zeal] php document display language (#551)

 

WOW, this is just insane! I have no idea how such corruption could happen. Are you sure PHP is the only docset affected?

**Comment by trollixx** [comment] 2016-06-08 01:59
My guess is that this is a Qt WebKit bug. I am working on providing a Qt WebEngine based builds for Windows. Then we'll be able to check. Unfortunately, I don't know how to fix the problem right away.

**Comment by fzls** [comment] 2016-06-08 10:16
Thanks anyway.

Thanks for your excellent software. :)

 

发件人: Oleg Shparber [mailto:notifications@github.com] 
发送时间: Wednesday, June 8, 2016 10:00 AM
收件人: zealdocs/zeal <zeal@noreply.github.com>
抄送: 风之凌殇 <1054073896@qq.com>; Author <author@noreply.github.com>
主题: Re: [zealdocs/zeal] php document display language (#551)

 

My guess is that this is a Qt WebKit bug. I am working on providing a Qt WebEngine based builds for Windows. Then we'll be able to check. Unfortunately, I don't know how to fix the problem right away.

**Comment by trollixx** [comment] 2017-04-08 06:00
It's a duplicate of #359.

**Closed by trollixx** 2017-04-08 06:00 UTC
Labels: Component: Docsets, Component: Web View, Platform: Windows, Resolution: Upstream Problem, Type: Defect
