### ISSUE TITLE
I want to transport zeal to Simplified Chinese.

### ISSUE THREAD

**Issue by zjzdy** [zealdocs/zeal#274] opened 2015-02-14 17:35 UTC
I want to transport zeal to Simplified Chinese.
I use zeal-20141123 tag.
I add TRANSLATIONS = translate_zh_CN.ts to zeal.pro.
Then I lupdate.exe zeal.pro to build  translate_zh_CN.ts.
I transport it.
```
# translate_zh_CN.ts
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>MainWindow</name>
    <message>
        <location filename="mainwindow.ui" line="14"/>
        <source>Zeal</source>
        <translation>Zeal</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="112"/>
        <source>Enter your query</source>
        <translation>输入您要查询的内容</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="138"/>
        <source>Sections:</source>
        <translation>章节:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="177"/>
        <source>←</source>
        <translation>←</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="184"/>
        <source>→</source>
        <translation>→</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="199"/>
        <source>Open URL</source>
        <translation>打开链接</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="235"/>
        <source>&amp;File</source>
        <translation>文件(&amp;F)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="241"/>
        <source>&amp;Edit</source>
        <translation>编辑(&amp;E)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="247"/>
        <source>&amp;Help</source>
        <translation>帮助(&amp;H)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="254"/>
        <source>&amp;View</source>
        <translation>查看(&amp;V)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="261"/>
        <source>Tabs</source>
        <translation>标签页</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="277"/>
        <source>&amp;Quit</source>
        <translation>退出(&amp;Q)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="282"/>
        <source>&amp;Options</source>
        <translation>选项(&amp;O)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="287"/>
        <source>&amp;About</source>
        <translation>关于(&amp;A)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="292"/>
        <source>About &amp;Qt</source>
        <translation>关于Qt(&amp;Q)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="297"/>
        <source>&amp;Back</source>
        <translation>后退(&amp;B)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="302"/>
        <source>&amp;Forward</source>
        <translation>前进(&amp;F)</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="307"/>
        <source>New Tab</source>
        <translation>打开新的标签页</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="310"/>
        <source>Ctrl+T</source>
        <translation>Ctrl+T</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="315"/>
        <source>Close Tab</source>
        <translation>关闭标签页</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="320"/>
        <source>Next Tab</source>
        <translation>下一个标签页</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="325"/>
        <source>Previous Tab</source>
        <translation>上一个标签页</translation>
    </message>
</context>
<context>
    <name>QuaZipFilePrivate</name>
    <message>
        <location filename="quazip/quazipfile.cpp" line="217"/>
        <source>ZIP/UNZIP API error %1</source>
        <translation>ZIP/UNZIP API 错误 %1</translation>
    </message>
</context>
<context>
    <name>ZealSettingsDialog</name>
    <message>
        <location filename="zealsettingsdialog.ui" line="14"/>
        <source>Zeal Options</source>
        <translation>Zeal选项</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="24"/>
        <source>General</source>
        <translation>一般</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="32"/>
        <source>Hiding behavior</source>
        <translation>隐藏方式</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="41"/>
        <location filename="zealsettingsdialog.ui" line="72"/>
        <source>System Tray</source>
        <translation>系统托盘</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="51"/>
        <source>Minimize</source>
        <translation>最小化</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="63"/>
        <source>Startup behavior</source>
        <translation>启动后显示为</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="79"/>
        <source>Window</source>
        <translation>窗口</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="88"/>
        <source>Hotkey</source>
        <translation>热键</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="95"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="102"/>
        <source>Minimum font size</source>
        <translation>最小字体</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="112"/>
        <source>Docsets storage directory</source>
        <translation>Docsets存储目录</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="126"/>
        <source>Browse...</source>
        <translation>浏览...</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="137"/>
        <source>NOTE:</source>
        <translation>注意:</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="147"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Zeal will also look for docsets in the &apos;docsets&apos; subdirectory of the directory containing zeal binary file, if such &apos;docsets&apos; subdirectory exists. This is meant to be useful for creating portable versions of Zeal.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;如果Zeal的程序目录存在docsets目录,那么Zeal也会在zeal的程序目录下的docsets目录寻找docsets.这可以用来创建Zeal的便携式版本.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="167"/>
        <source>Network</source>
        <translation>网络</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="173"/>
        <source>No proxy</source>
        <translation>不设置代理</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="186"/>
        <source>System proxy settings</source>
        <translation>使用系统代理设置</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="196"/>
        <source>Manual proxy configuration</source>
        <translation>手动配置代理</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="222"/>
        <source>HTTP proxy:</source>
        <translation>HTTP代理:</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="239"/>
        <source>Port:</source>
        <translation>端口:</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="261"/>
        <source>HTTP proxy requires authentication</source>
        <translation>HTTP代理认证</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="286"/>
        <source>Username:</source>
        <translation>用户名:</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="303"/>
        <source>Password:</source>
        <translation>密码:</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="342"/>
        <source>Docsets</source>
        <translation>Docsets</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="353"/>
        <source>Update docsets</source>
        <translation>更新docsets</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="360"/>
        <source>Add feed</source>
        <translation>增加来源</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="383"/>
        <source>Delete</source>
        <translation>删除</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="400"/>
        <source>Download...</source>
        <translation>下载中...</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="409"/>
        <source>Downloadable docsets</source>
        <translation>可下载的docsets</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="418"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Docsets with icons are contributed by &lt;a href=&quot;http://kapeli.com/dash&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;Dash&lt;/span&gt;&lt;/a&gt;, the Mac OS X Documentation Browser.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Docsets以及图标为&lt;a href=&quot;http://kapeli.com/dash&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;Dash&lt;/span&gt;&lt;/a&gt;提供,一个Mac OS X文档浏览器.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="zealsettingsdialog.ui" line="449"/>
        <source>Download</source>
        <translation>下载</translation>
    </message>
</context>
</TS>
```

**Comment by trollixx** [comment] 2015-02-14 19:14
Hi,

That's a great work! We'll have translation support soon.

The problem is, that version 20141123 is very different from the current code.

We will be using an online tool (Transifex or something else), where it will be possible to translate strings.

**Comment by zjzdy** [comment] 2015-02-15 01:46
Ok.But where is online translation tool url?

**Comment by trollixx** [comment] 2015-02-16 03:01
It is yet to be done. I'll post an update here and in #275, once we have a translation system ready.

**Comment by trollixx** [comment] 2016-09-30 05:01
Closing this in favour of #275. Once we have some system in place, all translations should go through it.

**Closed by trollixx** 2016-09-30 05:01 UTC
