### ISSUE TITLE
Feature Request: Shortcuts

### ISSUE THREAD

**Issue by teslaNova** [zealdocs/zeal#824] opened 2017-11-21 10:23 UTC
I really like this project. What's missing are shortcuts. 

I often switch through my editor and zeal to look something up (duh!) and it'd be neat to keep the mouse untouched if I want to search for something in the current tab by using a shortcut to focus the search textbox.

**Comment by trollixx** [comment] 2017-11-21 10:32
`Ctrl+K`?

**Comment by trollixx** [comment] 2017-12-04 21:44
I guess problem is the lack of documentation. Duplicate of #72.

**Closed by trollixx** 2017-12-04 21:44 UTC
