### ISSUE TITLE
Example text in CL docset is smaller than the rest of the text

### ISSUE THREAD

**Issue by onitatsuo** [zealdocs/zeal#1018] opened 2018-10-23 04:51 UTC
Pretty much as the title says the example text in the CL docset is smaller than the rest of the text so much so that I can't even read the text.

**Comment by trollixx** [comment] 2018-10-24 00:48
Please try the solution from https://github.com/zealdocs/zeal/issues/1019#issuecomment-432187126.

**Comment by trollixx** [comment] 2018-12-14 06:20
Duplicate of #903.

**Closed by trollixx** 2018-12-14 06:20 UTC
