### ISSUE TITLE
Huge window

### ISSUE THREAD

**Issue by BrRoman** [zealdocs/zeal#943] opened 2018-05-16 07:18 UTC
Before all, please be indulgent: I'm not fluent nor in english, nor in Linux, nor in C++… :-)

Then, thanks a lot for this application. I just came from Mac OS and I'm glad to find an alternative of Dash.

Finally, here is my problem: on some screen, the window of Zeal is huge and unreduceable, like this:

![screenshot from 2018-05-12 08-22-39](https://user-images.githubusercontent.com/18112726/40101802-d1cd7b46-58e8-11e8-9a65-ebc53088f576.png)

I have fixed this problem by launching Zeal on a Terminal with a parameter (cf. Issue #869, answer of rogatty):

`QT_AUTO_SCREEN_SCALE_FACTOR=0 zeal`

But it's quite uncomfortable, so my question is: is it possible to insert this parameter in the code?

Thanks a lot again!

Ubuntu 18.04, QMake version 3.1, Qt version 5.9.5

Br. Roman Mary

**Comment by trollixx** [comment] 2018-05-22 04:54
There's no need to create a new ticket for the same problem, especially after you have discovered the existing one.

Yeah, it's possible to disable the new scaling functionality in Zeal, unfortunately that breaks it for other users. I have to investigate further if there is a way to address the problem globally.

Closing as a duplicate of #869. Let's keep all related conversation in one place.

**Closed by trollixx** 2018-05-22 04:54 UTC
