### ISSUE TITLE
Windows: Bad/No feedback when downloading/upgrading docsets

### ISSUE THREAD

**Issue by hkleynhans** [zealdocs/zeal#1060] opened 2019-01-07 17:49 UTC
There is no indication in the UI that a process is still ongoing when either (a) adding a new docset, or (b) updating docsets.  The only hint seems to be a message "Please wait for all operations to finish" which pops up when attempting to close the docset window.

It would be nice if you could actually see what the application is busy doing, even if there is no accurate detail on how long is left.

**Comment by trollixx** [comment] 2019-01-13 03:41
Duplicate of #707.

**Closed by trollixx** 2019-01-13 03:41 UTC
