### ISSUE TITLE
today after updating , then content of html,css and javascript   renders error.

### ISSUE THREAD

**Issue by wwwpalmercom** [zealdocs/zeal#1175] opened 2019-12-20 09:36 UTC
Zeal version: **0.6.1**
Error info:  **Content rendering error.An unhandled error occurred in the application. We apologize for the inconvenience!**

after updating all docs , the content of html , css and js can't be render. However, others' docs show noramlly.

**Comment by DKroot** [comment] 2019-12-20 22:38
Same here.

**Comment by kid1412621** [comment] 2019-12-24 05:55
same here.
![image](https://user-images.githubusercontent.com/26278054/71396418-f94e7b80-2654-11ea-8368-5ba58f375565.png)

**Comment by gigi206** [comment] 2019-12-24 16:29
Same issue

**Comment by m4rii0** [comment] 2019-12-25 20:54
Duplicate of #1155

**Closed** 2019-12-27 04:22 UTC

**Comment by mano9dev** [comment] 2020-02-13 10:33
I have same issue after update javascript docset
