### ISSUE TITLE
Cannot start with QtWebKit TP5

### ISSUE THREAD

**Issue by kraml** [zealdocs/zeal#691] opened 2017-02-13 01:42 UTC
QtWebKit has released Technical Preview 5: https://github.com/annulen/webkit/releases/tag/qtwebkit-tp5

Which supports build with MinGW now.

And MINGW-packages for MSYS2 project now is working on packaging it: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-qtwebkit

I've build and installed this QtWebKit TP5 under MSYS2/MinGW64, everything is fine. However after rebuild Zeal master against it, Zeal won't start. No UI window ever shown, just crash and exist. Before that I was running Zeal against the bundled webkit from Qt 5.7.0/5.7.1/5.8.0 from MSYS2/MinGW64, everything works fine.

Please let me know what further information you need and how to collect them.

**Comment by trollixx** [comment] 2017-02-13 13:23
Just yesterday I encountered a similar problem with Qt WebKit TP5 and
VS2015. In my case is was caused by missing zlib.dll, as I couldn't make
libarchive link statically.

**Comment by kraml** [comment] 2017-02-13 15:23
I never link libarchive statically while building Zeal on my computer with msys2, I've always modified core.pri to remove static linking. The reason is simply, msys2 only provide dynamic lib for libarchive.

**Comment by trollixx** [comment] 2017-02-13 19:02
Does Zeal start normally with Qt WebEngine?

**Comment by kraml** [comment] 2017-02-14 01:54
I build Zeal only with MSYS2 so I cannot link it with Qt WebEngine as it requires VS...

**Comment by trollixx** [comment] 2017-02-14 05:21
I have never tried MSYS2, but it sounds like the problem is with Qt WebKit TP5, not Zeal.

**Comment by kraml** [comment] 2017-02-14 06:11
Have you built Zeal + QtWebKit TP5 with VS? Everything works fine?

**Comment by trollixx** [comment] 2017-02-14 13:04
Yes, 64-bit, VS 2015, Qt 5.8. And it felt quite faster and smoother
compared to Qt WebEngine.

As I mentioned above, I couldn't make it link libarchive statically, but
that's a minor issue. Also prebuilt Qt binaries do not bundle OpenSSL.

I'll be spending time setting up AppVeyor to build all dependencies and
Zeal itself using VS 2015. Also there's a potential to reduce Qt libraries
down to required only functionality, thanks to the Qt Lite effort.

**Comment by annulen** [comment] 2017-02-15 07:55
@kraml: Could you try MSYS2/MinGW32? 64-bit MinGW package is known to crash, see https://github.com/supercollider/supercollider/issues/2204 for similar report

**Comment by kraml** [comment] 2017-02-15 15:34
Yes 32-bit build works.

**Comment by trollixx** [comment] 2017-02-16 02:59
Okay, it's an upstream bug, and has nothing to do with Zeal. Closing this ticket then.

**Closed by trollixx** 2017-02-16 02:59 UTC
