### ISSUE TITLE
Need feature that press Esc to hide Zeal window

### ISSUE THREAD

**Issue by perqin** [zealdocs/zeal#506] opened 2016-03-02 15:10 UTC
When I am coding and I press hot key the Zeal window popup up, but I have to close it using my mouse. Could you please allow to set hot key for hiding Zeal window?

**Comment by trollixx** [comment] 2016-03-02 17:59
Currently you can use the same global shortcut to hide Zeal too. Esc
focuses the query text field atm, I am not sure if this should be changed
or not.

**Comment by ssokolow** [comment] 2016-04-03 13:30
Why not use `Ctrl+L` to focus the query field since it's Zeal's analogue to a browser/file manager address bar?

...or at least add it as a second option. The current state of thing is actually a bit counter-productive since my muscle memory is programmed to hit Ctrl+L when I want to Google for documentation.

**Comment by trollixx** [comment] 2016-04-03 15:15
This issue is actually a duplicate of #153.

**Closed by trollixx** 2016-04-03 15:15 UTC
Labels: Component: UI, Type: Enhancement
