### ISSUE TITLE
Segmentation Fault when selecting text in Wordpress docset

### ISSUE THREAD

**Issue by infomaniac50** [zealdocs/zeal#902] opened 2018-03-10 04:06 UTC
It's probably an upstream issue but I'm sticking it in here anyway.
I get a segmentation fault when I try to select text in the Wordpress docset.

I can't even look at the Vue.js docset without it crashing.

```ldd
ldd src/build/bin/zeal 
	linux-vdso.so.1 (0x00007ffc40fc7000)
	libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x00007f315bcad000)
	libQt5Concurrent.so.5 => /usr/lib/libQt5Concurrent.so.5 (0x00007f315baa6000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f315b767000)
	libQt5X11Extras.so.5 => /usr/lib/libQt5X11Extras.so.5 (0x00007f315b562000)
	libxcb-keysyms.so.1 => /usr/lib/libxcb-keysyms.so.1 (0x00007f315b35f000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f315b136000)
	libQt5WebKitWidgets.so.5 => /usr/lib/libQt5WebKitWidgets.so.5 (0x00007f315c44d000)
	libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f315a8dc000)
	libQt5WebKit.so.5 => /usr/lib/libQt5WebKit.so.5 (0x00007f31578aa000)
	libQt5Network.so.5 => /usr/lib/libQt5Network.so.5 (0x00007f315751e000)
	libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f3156d5d000)
	libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f3156655000)
	libarchive.so.13 => /usr/lib/libarchive.so.13 (0x00007f31563a4000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f315601d000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3155e06000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f3155a4f000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f3155703000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f31554ff000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f31552e8000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f31550ca000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f3154ec6000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f3154cc0000)
	libQt5PrintSupport.so.5 => /usr/lib/libQt5PrintSupport.so.5 (0x00007f3154a52000)
	libQt5Quick.so.5 => /usr/lib/libQt5Quick.so.5 (0x00007f31543dc000)
	libQt5WebChannel.so.5 => /usr/lib/libQt5WebChannel.so.5 (0x00007f31541be000)
	libicuuc.so.60 => /usr/lib/libicuuc.so.60 (0x00007f3153e05000)
	libQt5Positioning.so.5 => /usr/lib/libQt5Positioning.so.5 (0x00007f3153b7d000)
	libicui18n.so.60 => /usr/lib/libicui18n.so.60 (0x00007f31536da000)
	libQt5Sensors.so.5 => /usr/lib/libQt5Sensors.so.5 (0x00007f3153499000)
	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007f3153231000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f3152ffb000)
	libwebp.so.7 => /usr/lib/libwebp.so.7 (0x00007f3152d91000)
	libhyphen.so.0 => /usr/lib/libhyphen.so.0 (0x00007f3152b8b000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007f3152825000)
	libxslt.so.1 => /usr/lib/libxslt.so.1 (0x00007f31525e6000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f315223a000)
	libgstapp-1.0.so.0 => /usr/lib/libgstapp-1.0.so.0 (0x00007f315202b000)
	libgstbase-1.0.so.0 => /usr/lib/libgstbase-1.0.so.0 (0x00007f3151dc7000)
	libgstreamer-1.0.so.0 => /usr/lib/libgstreamer-1.0.so.0 (0x00007f3151a8f000)
	libgstpbutils-1.0.so.0 => /usr/lib/libgstpbutils-1.0.so.0 (0x00007f3151858000)
	libgstaudio-1.0.so.0 => /usr/lib/libgstaudio-1.0.so.0 (0x00007f31515ec000)
	libgsttag-1.0.so.0 => /usr/lib/libgsttag-1.0.so.0 (0x00007f31513b1000)
	libgstvideo-1.0.so.0 => /usr/lib/libgstvideo-1.0.so.0 (0x00007f315111c000)
	libgstfft-1.0.so.0 => /usr/lib/libgstfft-1.0.so.0 (0x00007f3150f11000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f3150cbc000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f31509a7000)
	libQt5Qml.so.5 => /usr/lib/libQt5Qml.so.5 (0x00007f3150370000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f3150168000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f315c2bf000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f314fefe000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f314fa81000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f314f7f6000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f314f544000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f314f2be000)
	libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007f314f047000)
	libdouble-conversion.so.1 => /usr/lib/libdouble-conversion.so.1 (0x00007f314ee37000)
	libacl.so.1 => /usr/lib/libacl.so.1 (0x00007f314ec2e000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f314e9fc000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f314e7d6000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f314e5bf000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f314e3af000)
	libicudata.so.60 => /usr/lib/libicudata.so.60 (0x00007f314c807000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f314c603000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f314c3ec000)
	libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f314c196000)
	libunwind.so.8 => /usr/lib/libunwind.so.8 (0x00007f314bf7c000)
	libdw.so.1 => /usr/lib/libdw.so.1 (0x00007f314bd34000)
	liborc-0.4.so.0 => /usr/lib/liborc-0.4.so.0 (0x00007f314bab5000)
	libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f314b8ac000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f314b639000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f314b408000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f314b1f6000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f314af40000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f314ac77000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f314aa4b000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f314a72f000)
	libattr.so.1 => /usr/lib/libattr.so.1 (0x00007f314a52a000)
	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f314a2dc000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f314a0d5000)
	libelf.so.1 => /usr/lib/libelf.so.1 (0x00007f3149ebd000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f3149ca8000)
```

```archey3
OS: Arch Linux x86_64
Kernel Release: 4.15.7-1-ARCH
WM: Xfwm
DE: Xfce
RAM: 3937 MB / 15923 MB
Processor Type: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
$EDITOR: None
Root: 24G / 32G (75%) (ext4)
```
GDB message:
```
free(): invalid pointer

Thread 1 "zeal" received signal SIGABRT, Aborted.
0x00007ffff189a860 in raise () from /usr/lib/libc.so.6
```

backtrace:
```
#0  0x00007ffff189a860 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff189bec9 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff18dd437 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff18e378b in  () at /usr/lib/libc.so.6
#4  0x00007ffff18e524c in _int_free () at /usr/lib/libc.so.6
#5  0x00007fff4d356282 in std::locale::_Impl::_M_install_facet(std::locale::id const*, std::locale::facet const*) () at /usr/lib/jvm/java-9-jre/jre/lib/libdeploy.so
#6  0x00007fff4d362de3 in std::locale::_Impl::_Impl(unsigned long) () at /usr/lib/jvm/java-9-jre/jre/lib/libdeploy.so
#7  0x00007fff4d363d55 in std::locale::_S_initialize_once() () at /usr/lib/jvm/java-9-jre/jre/lib/libdeploy.so
#8  0x00007ffff0eefdef in __pthread_once_slow () at /usr/lib/libpthread.so.0
#9  0x00007fff4d363da1 in std::locale::_S_initialize() () at /usr/lib/jvm/java-9-jre/jre/lib/libdeploy.so
#10 0x00007fff4d363de3 in std::locale::locale() () at /usr/lib/jvm/java-9-jre/jre/lib/libdeploy.so
#11 0x00007fff4d3356a4 in std::ios_base::Init::Init() () at /usr/lib/jvm/java-9-jre/jre/lib/libdeploy.so
#12 0x00007fff4d32d7b8 in  () at /usr/lib/jvm/java-9-jre/jre/lib/libdeploy.so
#13 0x00007fff4d32d7ea in  () at /usr/lib/jvm/java-9-jre/jre/lib/libdeploy.so
#14 0x00007ffff7de747a in call_init.part () at /lib64/ld-linux-x86-64.so.2
#15 0x00007ffff7de7586 in _dl_init () at /lib64/ld-linux-x86-64.so.2
#16 0x00007ffff7deba5e in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
#17 0x00007ffff1997b64 in _dl_catch_error () at /usr/lib/libc.so.6
#18 0x00007ffff7deb27a in _dl_open () at /lib64/ld-linux-x86-64.so.2
#19 0x00007ffff1316e86 in  () at /usr/lib/libdl.so.2
#20 0x00007ffff1997b64 in _dl_catch_error () at /usr/lib/libc.so.6
#21 0x00007ffff1317587 in  () at /usr/lib/libdl.so.2
#22 0x00007ffff1316f22 in dlopen () at /usr/lib/libdl.so.2
#23 0x00007ffff2704b1e in  () at /usr/lib/libQt5Core.so.5
#24 0x00007ffff26fe079 in QLibrary::load() () at /usr/lib/libQt5Core.so.5
#25 0x00007ffff3c89291 in  () at /usr/lib/libQt5WebKit.so.5
#26 0x00007ffff3c6c838 in  () at /usr/lib/libQt5WebKit.so.5
#27 0x00007ffff3c69941 in  () at /usr/lib/libQt5WebKit.so.5
#28 0x00007ffff3c6a312 in  () at /usr/lib/libQt5WebKit.so.5
#29 0x00007ffff3c47bdb in  () at /usr/lib/libQt5WebKit.so.5
#30 0x00007ffff4df21ac in WebCore::Page::pluginData() const () at /usr/lib/libQt5WebKit.so.5
#31 0x00007ffff49b541b in  () at /usr/lib/libQt5WebKit.so.5
#32 0x00007ffff4cfd1c0 in  () at /usr/lib/libQt5WebKit.so.5
#33 0x00007ffff4cfd78b in  () at /usr/lib/libQt5WebKit.so.5
#34 0x00007ffff4fd9e8b in  () at /usr/lib/libQt5WebKit.so.5
#35 0x00007ffff4d68e6e in  () at /usr/lib/libQt5WebKit.so.5
#36 0x00007ffff4d525c4 in  () at /usr/lib/libQt5WebKit.so.5
#37 0x00007ffff508a907 in  () at /usr/lib/libQt5WebKit.so.5
#38 0x00007ffff508612a in  () at /usr/lib/libQt5WebKit.so.5
#39 0x00007ffff508b11d in  () at /usr/lib/libQt5WebKit.so.5
#40 0x00007ffff27396c6 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#41 0x00007ffff3468746 in  () at /usr/lib/libQt5Network.so.5
#42 0x00007ffff273a112 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#43 0x00007ffff6844fec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#44 0x00007ffff684c9c6 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#45 0x00007ffff2708da0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#46 0x00007ffff270ba06 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#47 0x00007ffff2765d04 in  () at /usr/lib/libQt5Core.so.5
#48 0x00007fffec808e38 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#49 0x00007fffec809081 in  () at /usr/lib/libglib-2.0.so.0
#50 0x00007fffec80910e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#51 0x00007ffff27652f1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#52 0x00007fffe49c2482 in  () at /usr/lib/libQt5XcbQpa.so.5
#53 0x00007ffff27073db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#54 0x00007ffff27107d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#55 0x0000555555574ba8 in main(int, char**) (argc=<optimized out>, argv=0x7fffffffdfa8) at /home/derek/workspace/arch/zeal/src/zeal-0.6.0/src/app/main.cpp:244
```

**Comment by trollixx** [comment] 2018-03-10 13:44
Duplicate of #802.

Solution: Remove Oracle JDK. See the linked ticket for more details.

**Closed by trollixx** 2018-03-10 13:44 UTC
