### ISSUE TITLE
QtNetwork Error 203 (for...in, for...of, etc.)

### ISSUE THREAD

**Issue by YoRHa-A5** [zealdocs/zeal#1197] opened 2020-03-02 21:32 UTC
When trying to look up

```- for...in
- for...of
- if...else
- do...while
- try...catch
- for each...in
- for await...of
```

the following error shows up:

![Screenshot_20200302_222411](https://user-images.githubusercontent.com/36411819/75719391-f74c0d00-5cd4-11ea-890e-4e3274434c9e.png)

`...obj` works as expected though.

**Comment by trollixx** [comment] 2020-08-16 23:10
Duplicate of #1009.

**Closed by trollixx** 2020-08-16 23:10 UTC
Labels: status/duplicate, type/defect, scope/misc/docsets, scope/docset-registry
