### ISSUE TITLE
docset substring issue

### ISSUE THREAD

**Issue by pawelkuras** [zealdocs/zeal#339] opened 2015-05-20 19:04 UTC
On the usage page (http://zealdocs.org/usage.html) it says that you can search all docsets containing a substring by having the substring preceding the colon, but this doesn't seem to work for either java or ruby.
ie. if I have Java EE6 and Java SE6 downloaded and enter the query "java:" nothing comes up.

**Comment by trollixx** [comment] 2015-05-20 19:42
Duplicate of #333. It's a bug in 0.1.1, and it has been fixed in 0.1 branch. I am going to make 0.1.2 release this week with quite a lot of small fixes including this one.

**Closed** 2015-05-20 19:42 UTC

**Comment by pawelkuras** [comment] 2015-06-12 20:20
Any idea when 0.1.2 will come out?  It's been a little over a week.

**Comment by trollixx** [comment] 2015-06-13 02:50
@pawelkuras there are some delays in my initial plan due to several issues I want to get fixed before the release and just lack of time. Should be ready "soon" :)

I hope to make 0.1.2 the last of the 0.1.x releases, and then focus on new features for 0.2.x.
