### ISSUE TITLE
Zeal 0.6.1 on Fedora 32 exits abruptly after assigning a global keyboard shortcut and pressing "Apply"

### ISSUE THREAD

**Issue by kocielnik** [zealdocs/zeal#1249] opened 2020-07-08 15:10 UTC
This is a follow-up to a comment by @trollixx on issue #500.

For a temporary solution (more like a workaround) resetting the shortcut and enabling Zeal to start on Fedora 32, see below.

A full stack trace is available here: [stack_trace.zip](https://github.com/zealdocs/zeal/files/4891484/stack_trace.zip).

## Problem details

After assigning a global keyboard shortcut and pressing "Apply" on Fedora 32, Zeal abruptly exits.

Then, when called from the desktop shortcut it does not start. The incident reporting tool reports an error that happened in the function `xcb_send_request_with_fds64`. That pointed me to this particular issue.

When calling Zeal from console, the output is:

```console
$ zeal
QSocketNotifier: Can only be used with threads started with QThread
zeal.core.applicationsingleton: Starting as a primary instance. (PID: 5115)
[1]    5115 segmentation fault (core dumped)  zeal
```

## Solution

To start Zeal, you can disable the shortcut directly in the configuration file.

Zeal stores config at `~/.config/Zeal/Zeal.conf`. In that file, find the section:

```
[global_shortcuts]
show=<your_hotkey>
```

To remove the shortcut, remove whatever is after the equality sign ("="), leaving the declaration empty as below:

```
[global_shortcuts]
show=
```

Save the file and Zeal should start normally now.

## If Zeal.conf is not there

In some cases, the configuration file may be located elsewhere. If that is true, to identify the path, try: `locate Zeal.conf`, or `find ~ -name Zeal.conf`.

**Comment by trollixx** [comment] 2020-07-11 19:48
Global shortcut implementation is based on the very old `QxtGlobalShortcut` and is known to have a long list of bugs.

Looks like call to `xcb_grab_key_checked()` causes the crash, but I am unable to reproduce it on Arch.

Does it crash when you try to set a new shortcut in settings?

**Comment by kocielnik** [comment] 2020-07-11 20:17
> Does it crash when you try to set a new shortcut in settings?

Yes, exactly after I press "Apply". So, precisely:

1. There is no shortcut defined in Settings,
2. Then I define a new shortcut of Ctrl+Alt+Z (works correctly),
3. Finally, I press "Apply" and after that Zeal crashes as described above.

(As a sidenote, thank you for your effort to create and maintain Zeal. It helps me a *lot* in my daily work!)

**Comment by trollixx** [comment] 2020-08-16 23:19
Can you please check if unreleased code also crashes the same way? The easiest way would be grabbing an AppImage from [here](https://github.com/zealdocs/zeal/actions/runs/210117166).

**Comment by azubieta** [comment] 2020-09-06 00:16
The AppImage should not be using the Qt installed in the system. That's an issue.

@kocielnik could you try `LD_DEBUG=libs ./the.AppImage 2>&1 | grep 'init: '` and share output. That will tell us what is being used from the system that should be part of the bundle.

**Comment by trollixx** [comment] 2020-09-06 04:24
I added `libqt5webenginewidgets5` in #1276 which solved the Qt version errors. Unfortunately, it now crashes for other reason:

```text
         1:     /tmp/.mount_zeal-057XqUX/usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5: error: symbol lookup error: undefined symbol: localtime64 (fatal)
         1:     /tmp/.mount_zeal-057XqUX/usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5: error: symbol lookup error: undefined symbol: localtime64_r (fatal)
[43903:43903:0906/002352.674638:FATAL:zygote_host_impl_linux.cc(196)] Check failed: ReceiveFixedMessage(fds[0], kZygoteHelloMessage, sizeof(kZygoteHelloMessage), &real_pid).
#0 0x7fd460755aee <unknown>
#1 0x7fd4607680e2 <unknown>
#2 0x7fd460372a9b <unknown>
#3 0x7fd460371b56 <unknown>
#4 0x7fd4603720fe <unknown>
#5 0x7fd46001dd55 <unknown>
#6 0x7fd460021262 <unknown>
#7 0x7fd45fe0fa9b <unknown>
#8 0x7fd45fe10bd5 <unknown>
#9 0x7fd45fda54f1 QtWebEngineCore::BrowserContextAdapter::defaultContext()
#10 0x7fd46642c6b5 QWebEngineProfile::defaultProfile()
#11 0x7fd466432a89 QWebEngineSettings::defaultSettings()
#12 0x563e42e5eaf5 <unknown>
#13 0x563e42e60e59 <unknown>
#14 0x563e42e2a257 <unknown>
#15 0x563e42e280f1 <unknown>
#16 0x7fd45dc1e152 __libc_start_main
#17 0x563e42e2867a <unknown>
```

**Comment by azubieta** [comment] 2020-09-06 16:58
That's great, the missing symbol should be solved by adding another missing library. We just have to find which one provide those missing symbols.

**Comment by zany130** [comment] 2021-03-26 01:22
still getting this issue on fedora 33 gnome running wayland
```
zeal 
QSocketNotifier: Can only be used with threads started with QThread
zeal.core.applicationsingleton: Starting as a primary instance. (PID: 259784)
[1]    259784 segmentation fault (core dumped)  zeal
```

**Comment by trollixx** [comment] 2021-04-21 12:34
Zeal [doesn't support](https://github.com/zealdocs/zeal/blob/d3c5521c501d24050f578348ff1b9d68244b992c/src/libs/ui/qxtglobalshortcut/qxtglobalshortcut.cpp#L242) global shortcuts on Wayland and the option should be disabled in the UI. I will need to check why it's not.

**Comment by christian-schulze** [comment] 2021-08-21 04:25
I'm getting the same issue on Ubuntu 21.04 with Gnome 3.38.5 using Wayland.

My workaround is the following:
- assign a global gnome shortcut via Keyboard Shortcuts to run Zeal
- make sure the following Zeal settings are `disabled`:
  - Start minimized
  - Hide to system tray on window close

**Comment by trollixx** [comment] 2024-07-22 01:19
A check for Wayland was added in v0.7.0, so this crash shouldn't happen anymore. Sort of a duplicate of #1106.

**Closed by trollixx** 2024-07-22 01:19 UTC
Labels: type/defect, platform/linux, scope/ui/global-shortcuts
