### ISSUE TITLE
Problemas al intentar abrir java SE9

### ISSUE THREAD

**Issue by NelsonZaraza** [zealdocs/zeal#1523] opened 2023-08-13 18:06 UTC
Al momento de ingresar a Java SE9 se traba y se cierra

**Comment by trollixx** [comment] 2023-08-19 15:26
English please? As much as I'd love to, I don't know all Earth languages. I bet this is about #868 pinned at the top.

**Comment by NelsonZaraza** [comment] 2023-08-20 21:07
When entering Java SE9, it locks and closes.

**Comment by trollixx** [comment] 2023-09-08 03:55
Yes, this is a duplicate of #868. Please try latest [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build. Alternatively, you can build Zeal yourself from the `main` branch.

**Closed by trollixx** 2023-09-08 03:55 UTC
