### ISSUE TITLE
cannot extract docset zeal.docset :unrecognized archive format

### ISSUE THREAD

**Issue by ghost** [zealdocs/zeal#465] opened 2016-01-12 02:07 UTC
every time i want to install a new docset I see an error like this

![zealerror](https://cloud.githubusercontent.com/assets/16218035/12252633/a3a20860-b90b-11e5-912f-efc321b050c1.png)

**Comment by trollixx** [comment] 2016-01-12 05:36
Hm, I can't reproduce. What's your Zeal version?

**Comment by i300220** [comment] 2016-01-14 22:23
Sorry to chime in.

Same problem here.  Happened as soon as I clicked 'Apache'.

Javascript was installing in the meantime.  As a result, javascript didn't install nor Apache.

Zeal v. 0.2.1

**Comment by trollixx** [comment] 2016-01-20 05:30
Related to #431.

**Comment by ecwpz91** [comment] 2016-04-02 17:47
If you're using Linux, installing the '[bsdtar](http://bit.ly/1UzSQ3w)' package fixed this issue for me.

**Comment by trollixx** [comment] 2016-04-02 18:31
@ecwpz91 you should be using a very old version of Zeal. Zeal doesn't use `bsdtar` since 0.1.0.

**Comment by ecwpz91** [comment] 2016-04-02 19:08
@trollixx I'm using RHEL Workstation release 7.1 (Maipo) and zeal version 0.2.1 (latest release).

**Comment by ecwpz91** [comment] 2016-04-02 19:14
@trollixx Maybe a compression issue across platforms for certain docsets? In my case, I received this error when downloading the "JavaScript" documentation.

**Comment by Marvelxy** [comment] 2016-04-15 22:50
Had same problem; I closed and opened Zeal and things went normal.

**Comment by trollixx** [comment] 2017-04-08 05:58
Closing in favour of #599.

**Closed by trollixx** 2017-04-08 05:58 UTC
Labels: Component: Docset Manager, Type: Defect
