### ISSUE TITLE
[feature request] Allow shell variables in zeal.conf

### ISSUE THREAD

**Issue by cocoonkid** [zealdocs/zeal#1452] opened 2023-01-19 12:35 UTC
[feature request] Allow shell variables in zeal.conf

I'd like to set a docset path to
```


[docsets]
path=$HOME/.config/Zeal/docsets/
```

or

```

[content]
custom_css_file=~/.config/Zeal/userContent.css
```

I have to manually change this for migrations everytime.

Thank you for your consideration!

**Comment by trollixx** [comment] 2023-08-08 04:47
Duplicate of #643.

**Closed by trollixx** 2023-08-08 04:47 UTC
