### ISSUE TITLE
Error when adding network shared folder in Windows

### ISSUE THREAD

**Issue by Eldadc** [zealdocs/zeal#1058] opened 2018-12-30 05:17 UTC
Hi,
Tried to add network shared folder with the following format : "\\Shared\Folders\Zeal  - Got Error:
http:\\Shared\Folders\Zeal
Any suggestions on how to add network shared path ?

Thanks

**Comment by trollixx** [comment] 2018-12-31 04:04
Duplicate of #1055. Zeal currently doesn't work with UNC paths.

**Closed by trollixx** 2018-12-31 04:04 UTC
Labels: status/duplicate, type/defect, platform/windows
