### ISSUE TITLE
HTML section not working

### ISSUE THREAD

**Issue by NightSommelier** [zealdocs/zeal#1162] opened 2019-11-19 09:45 UTC
This section does not work, it only shows to reload the page.
![image](https://user-images.githubusercontent.com/2665877/69135569-f8f51a80-0ac1-11ea-8789-c734bc2a962d.png)

**Comment by trollixx** [comment] 2019-11-21 07:30
Duplicate of #1155, please use search before creating new issues.

**Closed by trollixx** 2019-11-21 07:30 UTC
