### ISSUE TITLE
Content rendering error

### ISSUE THREAD

**Issue by Laci444** [zealdocs/zeal#1156] opened 2019-11-11 18:54 UTC
I trying to use js html or css documentation, but I cant.
![image](https://user-images.githubusercontent.com/29151964/68612551-0e17eb00-04bd-11ea-937a-95f981e83f8d.png)

**Comment by hxalfa** [comment] 2019-11-12 11:38
I am having the same issue.

**Comment by trollixx** [comment] 2019-11-13 02:57
Duplicate of #1155 (!), please use search before creating new tickets.

**Closed by trollixx** 2019-11-13 02:57 UTC
