### ISSUE TITLE
Content rendering error

### ISSUE THREAD

**Issue by mbrains** [zealdocs/zeal#1253] opened 2020-07-14 08:25 UTC
In HTML docs i have this error ( Content rendering error ).
How to fix on Windows?
Regards thanks.
![2020-07-14](https://user-images.githubusercontent.com/35772246/87402774-ef21a980-c5b3-11ea-9bf7-6eaa912b7842.png)

**Comment by trollixx** [comment] 2020-07-18 20:41
Duplicate of #1155.

**Closed by trollixx** 2020-07-18 20:41 UTC
