### ISSUE TITLE
Favor exact search match over substring ones

### ISSUE THREAD

**Issue by b52** [zealdocs/zeal#613] opened 2016-10-07 11:23 UTC
For example, try to search for the built-in function `len` in python. The word is so common, that Zeal shows a lot of noise before the actually matching function:
![image](https://cloud.githubusercontent.com/assets/23704/19188271/f8b74fe6-8c90-11e6-91bc-41462e2a1884.png)

A very trivial fix would ensure that exactly matching search strings are favored. However, a potentially more improved approach would rate each search hit and show the hits according to their rating. An exact search hit should get a higher rating in this case. That should play nicely with fuzzy searching.

**Comment by jkozera** [comment] 2016-10-07 11:41
Shameless plug for my potential sqlite match scoring implementation which could be reused here: https://github.com/zestdocs/zest/blob/master/sqlite_score/score.c#L87 (ported from devdocs - https://github.com/Thibaut/devdocs/blob/50f583246d5fbd92be7b71a50bfa56cf4e239c14/assets/javascripts/app/searcher.coffee#L91)

**Comment by trollixx** [comment] 2016-10-08 15:37
It's actually a duplicate of #603.

**Closed by trollixx** 2016-10-08 15:37 UTC
