### ISSUE TITLE
Trying to remove a docset, zeal frozen and disappeared automatically.

### ISSUE THREAD

**Issue by soulawaker** [zealdocs/zeal#659] opened 2016-11-20 05:09 UTC
I'm using Elementary OS Loki based Ubuntu 16.04, zeal version is 0.3.1.

After searching docsets a few times, I tried to remove one docset, then zeal has frozen, disappeared.

Trying to restart zeal, I saw warning, 'Another application instance can be still running, or has crashed. Make sure to start Zeal only once.'

Ah? Now I'm trying to click Help button, then zeal is alive. what happen?

When I clicked quit button in warning box, it did not happen.  

I'm frustrating whether I delete this issue or not.

**Comment by trollixx** [comment] 2017-02-18 03:35
@soulawaker, @quantuumsnot I cannot reproduce this bug, what docset you were trying to remove?

**Comment by soulawaker** [comment] 2017-02-18 16:29
Ah, recently I've changed my laptop and all environments.

I might re-try it later and comment again.

**Comment by quantuumsnot** [comment] 2017-02-18 22:05
The docset is irrelevant

**Comment by trollixx** [comment] 2017-02-18 22:08
@quantuumsnot do you still experience the problem? I tried 0.3.1 on Windows 7 with multiple docsets, but nothing unusual is happening.

**Comment by trollixx** [comment] 2017-02-18 22:09
Also give a [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable) a shot.

**Comment by quantuumsnot** [comment] 2017-02-19 00:23
Now with CI and the current version the problem seems gone ... Weird

**Comment by trollixx** [comment] 2017-02-19 02:40
Closing for now, please let me know if the bug resurfaces.

**Closed by trollixx** 2017-02-19 02:40 UTC
Labels: Component: Docset Manager, Component: Docset Registry, Resolution: Unable To Reproduce, Type: Defect
