### ISSUE TITLE
Fuzzy Finder

### ISSUE THREAD

**Issue by urozavi** [zealdocs/zeal#483] opened 2016-01-28 16:50 UTC
please excuse my bad english.

am a new user to zeal, i used to use grep to parse docs, lately devdocs but i didn't like it, zeal is very good, and since am a vim user, zeavim make searching docs even simpler.

one thing i miss is the fuzzy finder, like typing 3 letters and narrow down the result, or just search by regex.

how can i do at, is zeal support it?

**Comment by klonos** [comment] 2016-01-28 18:26
Duplicate of #100. Please close this issue and follow the other one instead.

**Comment by trollixx** [comment] 2016-01-29 05:22
As noted above, duplicate of #100. Please check #281 for a proposed implementation.

**Closed by trollixx** 2016-01-29 05:22 UTC
Labels: Component: Docset Registry, Resolution: Duplicate, Type: Feature
