### ISSUE TITLE
Add vim keys (h, j, k, l) for scrolling and back/forward navigation

### ISSUE THREAD

**Issue by Phosphenius** [zealdocs/zeal#971] opened 2018-08-13 18:54 UTC
As someone who uses vim key extensions in their browser and heavily relies on the keyboard for navigation in general, I often find myself hitting _j_ and _k_ trying to scroll down and up respectively when using Zeal. Being able to use these keys for scrolling and maybe _h_ and _l_ for going back and forward respectively would be a huge UX boost for me and other people who are using these keys for navigation.

**Comment by trollixx** [comment] 2018-08-13 18:55
Similarly to #481, this is a duplicate of #10.

**Closed by trollixx** 2018-08-13 18:55 UTC
