### ISSUE TITLE
[Bug] Not query search, if Zeal.exe disabled

### ISSUE THREAD

**Issue by Kristinita** [zealdocs/zeal#632] opened 2016-10-15 05:21 UTC
### Summary

Queries added in input area of Zeal only if `Zeal.exe` process is enabled.

Queries works correct only if `Zeal.exe` is enabled. But `Zeal.exe` takes >110 Mb in RAM for me. I don't want add Zeal to Startup.
### Expected behavior

Adding queries in input area if `Zeal.exe` process disabled.
### Actual behavior

If `Zeal.exe` disabled, If I make a query, only `Zeal.exe` was opened, but query is not added in search area.

If `Zeal.exe` enabled, all queries works correct for me.
### Steps to reproduce

I install Zeal Portable from official site to folder `E:\Zeal` → I add `E:\Zeal` to my user variable `PATH` → I download docset for HTML → I make example query in command prompt: `zeal html:div`. → `Zeal.exe` was opened for me, but query not paste in search area.

### Environment

**Operating system and version:**
Windows 10.0.14393
**Zeal:**
0.3.1 portable

Thanks.

**Comment by Kristinita** [comment] 2016-11-19 14:17
Problem reproduced for me in Standalone version 0.3.1. Thanks.

**Comment by roesneb** [comment] 2016-12-09 09:09
:+1:

**Comment by steffenkj** [comment] 2016-12-09 09:43
:raised_hand:

**Comment by trollixx** [comment] 2017-01-26 03:55
Marking this as a duplicate of #681, which provides details a bit more clear.

**Closed** 2017-01-26 03:56 UTC
Labels: Component: CLI, Component: Core, Platform: Windows, Resolution: Duplicate, Type: Defect
