### ISSUE TITLE
Javascript docs rendering error

### ISSUE THREAD

**Issue by patfranciso** [zealdocs/zeal#1226] opened 2020-05-04 17:45 UTC
I recently downloaded the Javascript API docs to a machine of mine but the pages all show a content rendering error
![ss](https://user-images.githubusercontent.com/39833360/80996279-6f4ec480-8e37-11ea-8695-62caec77fa6a.png)

**Comment by trollixx** [comment] 2020-05-05 05:34
Duplicate of #1155, which is pinned at the top of the issues page...

**Closed** 2020-05-05 05:34 UTC
Labels: resolution/duplicate, scope/ui/webview, type/defect
