### ISSUE TITLE
can't update docset

### ISSUE THREAD

**Issue by tristetravel** [zealdocs/zeal#1461] opened 2023-02-16 04:36 UTC
![image](https://user-images.githubusercontent.com/7556743/219269694-fa2f10df-adbb-4288-bc39-0afe234f3a68.png)

**Comment by slavroman** [comment] 2023-03-15 15:51
I had the same issue. Docsets update successfully for me only through VPN... So try VPN.

**Comment by trollixx** [comment] 2023-04-08 16:26
Where are you trying to download from? It doesn't look like the problem is with our API server because you can see that there are updates available. I wonder if Dash's mirrors have some issues.

**Comment by slavroman** [comment] 2023-04-08 17:01
What does from where? Russia. I downloaded from "Zeal -> Tools -> Docsets" without changing any settings. Without VPN it didn't work for me, with VPN turned on everything is ok.
Updated: I just checked, without VPN the download worked, but very slowly 1-1.5 megabit/s, with VPN enabled - from 20 to 60 megabit/s (my current tariff is 100 megabit/s).

**Comment by trollixx** [comment] 2023-04-08 23:14
Our redirect service is supposed to choose the closest mirror to you. Maybe it's doing its job.

@slavroman could you try downloading a large docset (e.g. [.NET](https://github.com/Kapeli/feeds/blob/master/NET_Framework.xml) from each mirror listed in the feed and post results? Also which mirror do you get redirected to when you hit `https://go.zealdocs.org/d/com.kapeli/NET_Framework/latest`?

**Comment by slavroman** [comment] 2023-04-29 14:54
> Also which mirror do you get redirected to when you hit `https://go.zealdocs.org/d/com.kapeli/NET_Framework/latest`?

I working under Windows 10, after I put your link in search string, Chrome just open window with Save dialog Window, no more

> could you try downloading a large docset (e.g. [.NET](https://github.com/Kapeli/feeds/blob/master/NET_Framework.xml) from each mirror listed in the feed and post results?

I will try tomorrow, sorry for delay

**Comment by tristetravel** [comment] 2023-05-17 05:45
from china; 
today try again it worked but slowly;
I guess network reason of mirror;  but two years ago I remerber it is quick;
hope it will be fine in the furture;  thank you all

**Comment by trollixx** [comment] 2023-09-17 05:24
I am going to close the issue. Unfortunately, there's not much I can do about network restrictions in Russia and China.

I moved backend services behind `api.zealdocs.org` and `go.zealdocs.org` to Vercel. That should result in a better availability and location based caching, than a single Digital Ocean droplet in Amsterdam could provide.

**Closed by trollixx** 2023-09-17 05:24 UTC
Labels: resolution/awaiting-response, scope/misc/docsets
