### ISSUE TITLE
Icon's sliding down.

### ISSUE THREAD

**Issue by kdmessner** [zealdocs/zeal#175] opened 2014-07-14 18:45 UTC
Whenever I expand a docset that would cause it to use scroll bars and then scroll down until the parent icon is off screen, it slides the icons down like this:
![1](https://cloud.githubusercontent.com/assets/6591943/3575207/27f56efc-0b86-11e4-9940-9b572fb39eb0.png)
The top docset without the icon is actually CSS and where the SVG icon is, is actually jQuery. It fixes itself whenever I restart Zeal. I can also fix it by going to Edit>Options>Docsets and then deleting the newly created docset that has no icon or name (the icons are in the correct order here and jQuery is there)

I'm experiencing this on Windows 8.1, while trying to access it from a flash drive (docsets folder is in the exe's directory)

**Comment by trollixx** [comment] 2015-01-13 10:03
Closing for now, as I cannot reproduce. Please, reopen the bug report if the problem still persists.

**Closed by trollixx** 2015-01-13 10:03 UTC
