### ISSUE TITLE
Feature request: Open in new tab command line switch

### ISSUE THREAD

**Issue by deese** [zealdocs/zeal#1455] opened 2023-01-24 14:33 UTC
I'm using Zeal from Sublime Text and it would be great if there is a way to open the query in a new tab from it. Easiest way would be to add a command line switch (-t or similar) to open the query in a new tab. 

Adding the option also to the dash-plugin will help with other integrations. 

Extra ball:  Having a setting that always open searches in a new tab, can also be useful. 

Thanks!

**Comment by trollixx** [comment] 2023-04-16 03:34
Duplicate of #845. It's a relatively simple change, please consider contributing! :)

**Closed by trollixx** 2023-04-16 03:34 UTC
