### ISSUE TITLE
SSL Handshake Filed in zeal 0.6.1 for Windows 10

### ISSUE THREAD

**Issue by binrusdi** [zealdocs/zeal#1520] opened 2023-08-01 04:57 UTC
Hi, saya mengalami permasalahan **SSL Handshake failed** ketika ingin mendownload docsets.

![gambar](https://github.com/zealdocs/zeal/assets/119654495/3d6e2e50-c155-4938-9ade-e411f4321ae4)

**Comment by dongzhaolee** [comment] 2023-08-01 10:56
I get the same err on Windows 11, still waiting for the developers to solve the issue @trollixx

**Comment by Giulidan** [comment] 2023-08-01 20:40
I have the same error, using Windows 11.

**Comment by trollixx** [comment] 2023-08-01 21:32
Please use CI builds. Binaries are attached to each build.

**Comment by Giulidan** [comment] 2023-08-01 22:17
> 

I don't know where to find them, they all appear to me as "Expired"

**Comment by marckes04** [comment] 2023-08-01 22:57
how do I solve this??

**Comment by ostap-tymchenko** [comment] 2023-08-02 01:51
Probable duplicate of: https://github.com/zealdocs/zeal/issues/1518

**Comment by binrusdi** [comment] 2023-08-03 07:18
> Please use CI builds. Binaries are attached to each build.

Thanks, I'll try it

**Comment by Epic621** [comment] 2023-08-03 21:09
CI Build Artifacts that I see are all expired

**Comment by FalcoGer** [comment] 2023-08-04 00:07
The SSL certificate for `go.zealdocs.org` has expired on 2023-07-27

**Comment by DeckerSU** [comment] 2023-08-04 01:18
https://github.com/zealdocs/zeal/issues/1307#issuecomment-1664827774 - patch for ignore SSL errors, just made it for myself :wink:

**Comment by Mintonmu** [comment] 2023-08-04 04:39
emmmm, so, how do i solve this? only build zeal with ci on windows?  Is there any other solution？

**Comment by dongzhaolee** [comment] 2023-08-04 05:14
If you guys really have no way to solve the SSL err, you can just consider downloading from the mirror website, which deployed in some specific regions. 
Also, if you need the icons, just find it by yourself and name it 'icon.png' & 'icon@2x.png'. Then put them in the docsets folders.

Although this doesn't solve your problem, at least you can get started.

**Comment by dongzhaolee** [comment] 2023-08-04 05:23
If you're really unable to solve the SSL err, maybe you should consider downloading from the mirror website, which deployed in some specific regions.
Also, if you need the icon, just find it by yourself and name it 'icon.png' & '[icon@2x.png](mailto:icon@2x.png)'. Then put them in the docsets folders.

Although this can't solve your problem, at least you can get started.In fact, except CI builds, DeckerSU's patch works.

**Comment by DeckerSU** [comment] 2023-08-04 16:35
> emmmm, so, how do i solve this? only build zeal with ci on windows? Is there any other solution？

https://github.com/zealdocs/zeal/issues/1307#issuecomment-1665807497

**Comment by zhongdongy** [comment] 2023-08-05 16:36
Guys you may try set your computer's date to some date earlier than `Thursday, July 27, 2023 at 7:00:09 AM`, which was when the SSL cert of Dash expired.

![image](https://github.com/zealdocs/zeal/assets/24528231/9fa24144-afc2-41d9-8f2d-8f79079a058f)

After that, it should work without issue.
![image](https://github.com/zealdocs/zeal/assets/24528231/3fda13fe-43b2-4088-bfb8-e044797e9a15)

**Comment by zhongdongy** [comment] 2023-08-05 16:49
> Guys you may try set your computer's date to some date earlier than `Thursday, July 27, 2023 at 7:00:09 AM`, which was when the SSL cert of zealdocs.org expired.
> 
> ![image](https://github.com/zealdocs/zeal/assets/24528231/9fa24144-afc2-41d9-8f2d-8f79079a058f)
> 
> After that, it should work without issue.
> ![image](https://github.com/zealdocs/zeal/assets/24528231/3fda13fe-43b2-4088-bfb8-e044797e9a15)
> 

Ps. the date your computer is set to must be some date after 2023-07-20 07:00:17+08:00. This is because the refresh button on Zeal will fetch https://api.zealdocs.org first, whose SSL cert was issued at that moment.

**Comment by trollixx** [comment] 2023-08-06 05:52
The certificate was updated. Didn't realize it wasn't about a much older intermittent issue with v0.6.1 not being able to establish secure connections.

Duplicate of #1528.

**Closed by trollixx** 2023-08-06 05:52 UTC

**Comment by binrusdi** [comment] 2023-08-06 09:57
> The certificate was updated. Didn't realize it wasn't about a much older intermittent issue with v0.6.1 not being able to establish secure connections.
> 
> Duplicate of #1518.

sekarang sudah bisa di gunakan, terima kasih

**Comment by Mintonmu** [comment] 2023-08-06 14:07
> > emmmm, so, how do i solve this? only build zeal with ci on windows? Is there any other solution？
> 
> [#1307 (comment)](https://github.com/zealdocs/zeal/issues/1307#issuecomment-1665807497)
It works now, thank you very much for your help！

**Comment by kdsjflsdjfdslkjfdslfjsldkf** [comment] 2023-09-01 09:05
this app is such a waste of time... does not work.. again... ugh...
