### ISSUE TITLE
Can search results still be categorized?

### ISSUE THREAD

**Issue by deping** [zealdocs/zeal#1300] opened 2020-12-02 05:49 UTC
Case:
I install OpenGL 2.0 and OpenGL 4.0. I search glBitmap and find a result, but I can't know whether it is OpenGL 2.0 or OpenGL 4.0 directly.
Possible Solution:
Keep the search results categorized like the categories without search.

**Comment by trollixx** [comment] 2021-01-28 06:04
Duplicate of #77.

**Closed by trollixx** 2021-01-28 06:04 UTC
Labels: resolution/duplicate, scope/registry, type/feature
