### ISSUE TITLE
Item order in java8 docs

### ISSUE THREAD

**Issue by pdkst** [zealdocs/zeal#709] opened 2017-03-24 01:44 UTC
_Forgive me English is not good；_
when i typed 'Thread' in java8 docs , I mean I want to search the 'java.lang.Thread' class,but it give me ‘java.lang.Runtime#public void addShutdownHook(Thread hook)’ first；
I think the current order is like this: Class>Constructor>Field>Method
because the method is more longer than class,when seaching method,"getThread" will be first,not the 'Thread'

**Comment by trollixx** [comment] 2017-03-30 13:24
It's been improved recently, please try to build Zeal from the `master` branch, or [CI build](https://bintray.com/zealdocs/windows-ci).

Duplicate of #603.

**Closed by trollixx** 2017-03-30 13:24 UTC
