### ISSUE TITLE
Could you please add Linux Manual :-P

### ISSUE THREAD

**Issue by Mark24Code** [zealdocs/zeal#425] opened 2015-11-15 12:06 UTC
Could you please add Linux Manual :-P

**Comment by trollixx** [comment] 2015-11-23 03:42
What do you mean exactly? Man pages?

**Comment by ismail** [comment] 2015-11-26 12:03
Creating a docset out of http://man7.org/linux/man-pages/ would be nice (don't think this is a zeal TODO though).

**Comment by trollixx** [comment] 2015-11-26 17:10
Looks like this one is a duplicate of #115 :) Support for native man pages is something to be done.

**Closed** 2016-01-20 05:22 UTC
Labels: Component: Docsets, Resolution: Duplicate
