### ISSUE TITLE
Angular docs are all empty pages

### ISSUE THREAD

**Issue by nolash** [zealdocs/zeal#1293] opened 2020-10-19 16:09 UTC
version 0.6.1. Got the docset today.

**Comment by struts2spring** [comment] 2020-10-31 16:38
changed the title Angular docs are empty pages Angular docs are all empty pages

**Comment by trollixx** [comment] 2020-11-25 22:46
Duplicate of #1119, which is pinned at the top.

**Closed by trollixx** 2020-11-25 22:46 UTC
