### ISSUE TITLE
[Feature request] Check if downloads are truly complete

### ISSUE THREAD

**Issue by vgturtle127** [zealdocs/zeal#736] opened 2017-06-03 03:22 UTC
I think it would be beneficial to have some sort of check that determines if the download has completed successfully or not. Being able to repair docsets could be useful as well.

The newer commits seem to be struggling with completing the downloads, or at the very least something is happening incorrectly.

This could be in the form of checking if all the expected files are there, hashes or checksums, file sizes, etc. It could be done in many ways, but at the very least we should ensure that the user doesn't download a corrupted or incomplete docset, because if they do they will probably report it here. 😄

**Comment by trollixx** [comment] 2017-06-13 21:08
Duplicate of #599 :)

**Closed by trollixx** 2017-06-13 21:08 UTC
