### ISSUE TITLE
Can the zeal add the docset query keyword in the docset window?

### ISSUE THREAD

**Issue by yosaku01** [zealdocs/zeal#793] opened 2017-10-09 07:53 UTC
In the docset window of Dash, for each docset,  it has a query keyword. For example, Java SE 8 has keyword java8, C++ has keyword cpp. It is convenient for the user. But zeal have no this feature, can you add this feature into new version?

**Comment by trollixx** [comment] 2017-10-10 09:33
Eventually Zeal will have this. Duplicate of #421.

**Closed by trollixx** 2017-10-10 09:33 UTC
Labels: Component: Docset Registry, Resolution: Duplicate, Type: Feature
