### ISSUE TITLE
error reporting 

### ISSUE THREAD

**Issue by GayanEranga1992** [zealdocs/zeal#981] opened 2018-08-28 16:36 UTC
![screenshot_1](https://user-images.githubusercontent.com/42421838/44736958-4fb5b380-ab0e-11e8-8aa5-a2778069c1d3.png)
i installed javaSE 10 in Zeal but i can't open javase 10 doc

**Comment by trollixx** [comment] 2018-09-06 04:09
Duplicate of #868.

**Closed by trollixx** 2018-09-06 04:09 UTC
