### ISSUE TITLE
Doesn't scroll to exact definition in page anymore

### ISSUE THREAD

**Issue by FichteFoll** [zealdocs/zeal#349] opened 2015-06-14 22:14 UTC
I don't know exactly when it started happening, but I noticed lately that searching for a function that is defined mid-page doesn't scroll to that definition anymore. Interestingly, it works when selecting the item in the "See also" box.

Reproduce:

1. Download Python 3 docset
2. Search for `python 3:setdefault` and find "dict.setdefault"
3. Notice how the page is not scrolled and shows the top ("4. Built-in Types") instead of the definition of `setdefault`.
4. Focus "See also" box
5. Type "dict.set" to find the item there
6. Click it
7. Zeal now scrolls correctly to the method's documentation

**Comment by trollixx** [comment] 2015-06-14 22:38
Hi. It's a duplicate of #328. Fixed in 0.1 branch, but hasn't been released yet.

**Closed by trollixx** 2015-06-14 22:38 UTC

**Comment by FichteFoll** [comment] 2015-06-14 23:39
Sorry for the duplicate, the issue has escaped my search queries (notably "scroll" is mossing).

**Comment by FichteFoll** [comment] 2015-06-15 13:32
If possible, could you perhaps speed up the release of this fix? It's *really* annoying.

**Comment by trollixx** [comment] 2015-06-15 21:31
CI builds should work as an interim solution.

0.1.2 will be released soon, I am just trying to fit it with as many bug fixes as I can, before switching to development of new features for 0.2.x.
