### ISSUE TITLE
[Feature request] Docsets Scenario Preset: allow user to enable partial docs in all installed docsets

### ISSUE THREAD

**Issue by JustusPan** [zealdocs/zeal#1567] opened 2023-10-12 04:56 UTC
Imagine following scenarios:
1) I'm working base on C++/C during day time mainly 
2) sometime I need develop a project which is made with Unity
3) when writing some notes and articles, I need LaTeX reference
4) at a weekend I want to grab up Python quickly

there are many docs installed in my Zeal, but I don't want to see all of them at all time
- C++
- C
- Qt6
- Vim
- Unity(Unity need multiple version doc, this is another topic)
- LaTeX
- Python
- Godot

Could we support a feature which allow us to only activiate specific several docs from those all installed?
this feature consists of 2 phases.
1) just allow user manage(enable/disable) installed docs in docsets settings.
2) create a "quick switch preset" feature for your predefine scenario, and you could use shortcut Alt+1,Alt+2,...Alt+9 to switch between them quickly.

**Comment by trollixx** [comment] 2024-11-05 03:04
Pretty much a duplicate of #77. Hopefully, one day.

**Closed by trollixx** 2024-11-05 03:04 UTC
