### ISSUE TITLE
First start-up does not handle the dash-plugin:// URI correctly on Windows

### ISSUE THREAD

**Issue by szhongren** [zealdocs/zeal#729] opened 2017-05-15 04:02 UTC
You can call `start dash-plugin://query=test` on Windows from the command line but Zeal does not start correctly if Zeal is not already running. Just `start dash-plugin://` works fine though, so there seems to be a problem with the parsing of the parameters.

**Comment by trollixx** [comment] 2017-06-13 22:04
Could you try a recent [CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view)? It seems to be working fine with the fresh code base.

**Comment by szhongren** [comment] 2017-06-14 22:14
That does appear to be fixed, hmm. Did you manage to reproduce the problem? I probably should have mentioned that I came across the problem while running the start command from Node's `child_process.exec()`.

**Comment by trollixx** [comment] 2017-06-14 22:18
Most likely 4711e0cf3cf07e2d2eceba4adf26b6746c11ce09 fixed the problem since 0.3.1.

**Comment by trollixx** [comment] 2017-06-14 22:20
Marking as duplicate of #681.

**Closed by trollixx** 2017-06-14 22:20 UTC
Labels: Component: Plugin Support, Resolution: Duplicate, Type: Defect

**Comment by szhongren** [comment] 2017-06-14 22:40
Is this fix supposed to come with 0.3.2? I'm still getting it with my installed Zeal 0.3.1.

**Comment by szhongren** [comment] 2017-06-14 22:44
Oh wait never mind. Unstable build, it's right in the name. Thanks!

**Comment by trollixx** [comment] 2017-06-14 22:46
The next release will be 0.4.0.

**Comment by szhongren** [comment] 2017-06-14 22:50
Sounds good. Thanks for your work on this!
