### ISSUE TITLE
angular docs

### ISSUE THREAD

**Issue by lambaaditya24** [zealdocs/zeal#1127] opened 2019-08-17 08:02 UTC
Angular docs are not getting opened. I tried downloading it two times still nothing shows.

**Comment by Acelator** [comment] 2019-08-18 12:28
I actually have the same issue. I can't access Angular docs inside Zeal
![image](https://user-images.githubusercontent.com/34861788/63224435-7e67e680-c1c4-11e9-96f2-eac629c77714.png)

**Comment by makzan** [comment] 2019-08-21 12:40
It does work when right clicking mouse and open the doc in web browser.

**Comment by olegarxs** [comment] 2019-08-24 10:33
fix please

**Comment by Moto28** [comment] 2019-08-30 10:55
having the same issue

**Comment by samedwards1989** [comment] 2019-09-02 08:51
Having this issue too

**Comment by iHmD** [comment] 2019-09-02 17:07
same issue!

**Comment by trollixx** [comment] 2019-09-03 03:12
It appears that Qt WebKit can't parse some of the JS files:

```

**Comment by iHmD** [comment] 2019-09-04 11:40
> Blocking JS allows all the page to load.

@trollixx how did you do that please?

**Comment by trollixx** [comment] 2019-09-05 03:10
@iHmD by changing the source, but still haven't figured out why it can't parse what other browsers parse without issues.

**Comment by trollixx** [comment] 2019-09-05 03:45
This one is a duplicate of #1119.

**Closed by trollixx** 2019-09-05 03:45 UTC
Labels: resolution/duplicate, scope/ui/webview, type/defect
