### ISSUE TITLE
`Less` Documentation crashes Zeal

### ISSUE THREAD

**Issue by RomeuG** [zealdocs/zeal#1053] opened 2018-12-10 11:18 UTC
I downloaded `Less` documentation and whenever I select it and scroll down, Zeal crashes with this information:

```
Empty filename passed to function
free(): invalid pointer
[1]    5888 abort (core dumped)  zeal
```

Version: Zeal 0.6.1

EDIT: It seems it is not only the `Less` documentation, but also `Matplotlib` documentation too, in the `methods` category. This is most likely a bigger issue than something specific to a single documentation.

**Comment by trollixx** [comment] 2019-01-13 06:31
I just realized that this is a duplicate of #802.

You either need to remove Oracle  JDK, or `/usr/lib/mozilla/plugins/libnpjp2-jdk${VERSION}.so`.

**Closed by trollixx** 2019-01-13 06:31 UTC
Labels: type/defect

**Comment by RomeuG** [comment] 2019-01-13 10:02
Thank you, removing `/usr/lib/mozilla/plugins/libnpjp2-jdk${VERSION}.so` just fixed the problem.
