### ISSUE TITLE
New tab should focus search field

### ISSUE THREAD

**Issue by dbedrenko** [zealdocs/zeal#750] opened 2017-07-22 07:57 UTC
Zeal version: 0.3.1
OS: ArchLinux

To improve keyboard navigation in Zeal, it would be great that when you create a new tab (Ctrl+T) that it also focuses the search field, as it doesn't make sense to use the keyboard shortcut to open the tab but then immediately have to go back to the mouse to select the search field (and then back again to the keyboard to type your search term).

Steps to reproduce:
1. Click on the document section (of whatever API documentation or the big Zeal logo on startup)
2. Ctrl+T

Notice the search field is not focused.

PS: Love this app, thank you for your work!

**Comment by trollixx** [comment] 2017-07-24 19:09
Duplicate of #725. Already implemented in the `master` branch.

**Closed by trollixx** 2017-07-24 19:09 UTC

**Comment by dbedrenko** [comment] 2017-07-24 20:01
I tested `master` before writing this ticket to try and fix the issue myself, and focus was still not switched, despite the fix.
