### ISSUE TITLE
Zeal crashes with java10 docset

### ISSUE THREAD

**Issue by GayanEranga1992** [zealdocs/zeal#983] opened 2018-09-03 19:00 UTC
I'm using zeal 0.5.0 on Win10 I have installed the javase10 docset but i can't open this docset zeal crashed re-opened zeal the javase 10 docset removed

**Comment by trollixx** [comment] 2018-09-06 04:08
Duplicate of #868.

**Closed by trollixx** 2018-09-06 04:08 UTC
