### ISSUE TITLE
Ability to download and bookmark specific documentation versions

### ISSUE THREAD

**Issue by chrisyarbrough** [zealdocs/zeal#1006] opened 2018-10-08 09:50 UTC
Currently, when downloading a docset, we only get the most recent version. It would be great to select a specific version of the documentation to download. Additionally, I would like to either bookmark multiple versions or quickly switch between them. This would also require me to easily see which version of the docset I'm looking at.

I'm using multiple versions of the Unity engine, which is why I would like for Zeal to also handle docset versions.

Thank you for your consideration!

**Comment by auscompgeek** [comment] 2018-10-08 11:59
I think this is a duplicate of #208.

**Comment by trollixx** [comment] 2018-10-09 04:18
Duplicate of #208.

**Closed by trollixx** 2018-10-09 04:18 UTC
Labels: Component: UI/Docset Manager, Resolution: Duplicate, Type: Feature
