### ISSUE TITLE
Zeal crashes whenever try to download CSS or CakePHP doc sets

### ISSUE THREAD

**Issue by aliraza-io** [zealdocs/zeal#841] opened 2017-12-10 01:53 UTC
Whenever i try to download CSS or CakePHP doc sets it crashes the zeal. Mostly this happens when the docs set is 100% downloaded and instead of installing, it crashes instantly after that. I have just checked two of the doc sets but others may have the similar problem as well.
I have tried using both portable and installer versions on windows but the problem is the same. I am using Windows 8.1 x64.
![zeal-crash](https://user-images.githubusercontent.com/33189534/33801246-d2a83774-dd76-11e7-9bd9-afa5a97bc620.PNG)

**Comment by trollixx** [comment] 2017-12-10 14:14
Remove corresponding docset directories from your docset storage, and try again. Duplicate of #788.

**Closed by trollixx** 2017-12-10 14:14 UTC
