### ISSUE TITLE
Open the document garbled

### ISSUE THREAD

**Issue by itning** [zealdocs/zeal#942] opened 2018-05-14 12:40 UTC
OS:Win10 1803 X64
I am a Chinese user so I think it may be a coding issue.
GBK UTF-8 ?
---
![garbled1](https://raw.githubusercontent.com/itning/FilePool/master/images/garbled1.png)
![garbled2](https://raw.githubusercontent.com/itning/FilePool/master/images/garbled2.png)

**Comment by trollixx** [comment] 2018-05-22 05:27
@annulen Another problem like before. Ideas on how to track this down?

Duplicate of #816 I guess.

**Comment by annulen** [comment] 2018-05-22 11:12
Seems so

**Comment by ywx217** [comment] 2018-06-05 09:35
I'm also facing the same issue, system language is Chinese

**Comment by jpsouzasilva** [comment] 2018-06-17 03:20
Zeal 0.5.0 64-bits
Windows 10 x64

---

I was able to "get around this", **and only partially,** by switching my region on the Windows' options to United States.

![untitled](https://user-images.githubusercontent.com/17429390/41504383-b3dae6d4-71c3-11e8-9afa-c766851793d4.jpg)

By default, my computer is set to my current region (which is Brazil) but it 
uses English as a display language. It's a similar symptom of mismatching region and display language to what the other guys posted above.

I think it's using whatever default encoding is for the Windows' region selected, but it needs to be fixed to something which works for the English language specifically. Tell me if I can help on this @annulen @trollixx.

**Comment by trollixx** [comment] 2018-06-20 12:34
Very interesting, I thought this only affected our Chinese users.

We should check where Qt WebKit processes information about system's locale.

**Comment by annulen** [comment] 2018-06-20 12:41
@jpsouzasilva Please build this application: https://github.com/RJVB/fontweightissue-qt5, and try loading fonts with "load font file" button

**Comment by jpsouzasilva** [comment] 2018-06-21 11:40
Hi, thanks for the fast response.

@annulen any chance you could build that for me, pretty please? ☹️ I don't have Qt installed on Windows and my internet is quite bad to download the whole toolkit by myself, it would probably take a whole day...

I spent some time this morning trying to search for a way to get the development libraries alone, even using the Qt Installer, but couldn't manage it.

**Comment by itning** [comment] 2018-06-22 11:04
@annulen could you give me an executable file(.exe) ? My computer doesn't have qt development environment.

**Comment by Danielesk** [comment] 2018-07-15 07:10
@trollixx 
How to solve it?

**Comment by trollixx** [comment] 2018-07-16 01:36
There's no fix so far. If you can build and test https://github.com/RJVB/fontweightissue-qt5, that may help debugging it.

**Comment by ZX1209** [comment] 2019-04-22 02:53
i tried to set minimum font size to 56,and it's fixed ,i mean there's no garbled  there but font are too big too read.
ps:every language doc has different minimun size in my experiment

**Comment by itning** [comment] 2019-04-22 03:17
> i tried to set minimum font size to 56,and it's fixed ,i mean there's no garbled there but font are too big too read.
> ps:every language doc has different minimun size in my experiment
> no it's macType's problem,close it and every doc will show correctly
> ps:win10 user,zeal 0.61

![](https://raw.githubusercontent.com/itning/FilePool/master/images/a.png)

![](https://raw.githubusercontent.com/itning/FilePool/master/images/b.png)

Good!

**Closed** 2019-04-22 03:18 UTC
Labels: resolution/duplicate, resolution/upstream-problem, scope/ui/webview, type/defect
