### ISSUE TITLE
Downloading of a docset always stucks

### ISSUE THREAD

**Issue by qqmash** [zealdocs/zeal#844] opened 2017-12-11 18:07 UTC
When downloading a huge docset like Yii or PHP Zeal shows "Connection closed" at 70-90%. Then I press "Retry" and it starts to download the docset again from 0. And after a while it breaks connection again, so I cannot download any package that is big enough. When I try to close the window, it says to me "Please wait for all operations to finish" and don't close. I have to kill the window manually and start an application again to continue working.
I use Manjaro Linux x86_64 and 128 kbps internet connection.

P.S.: is there any way to download docsets manually and then unpack them to ~/.Zeal/docsets directory?

**Comment by trollixx** [comment] 2017-12-11 23:47
Downloading docsets manually is possible, but would result in them lacking some metadata. You can find links to the docset archives [here](https://github.com/Kapeli/feeds/).

There's a feature request for an ability to resume interrupted downloads - #430.

**Comment by qqmash** [comment] 2017-12-12 18:46
Thanx for the link, I've found a solution [here](https://lucasg.github.io/2017/02/05/Downloading-Dash-docsets/) (just some missing icons), but what is about the "Please wait for all operations to finish" message that makes me to kill the application? Today I had this thing even while (or, maybe, after) updating docset list. I'm not sure, but I think Zeal failed to download the list.

**Comment by trollixx** [comment] 2017-12-12 21:09
You might be right, and Zeal tries to fetch the updated docset list. You can simply click cancel button next to the progress bar in the bottom of the window.

**Comment by MoSala7** [comment] 2017-12-13 23:43
Hello, I solved this problem by searching for docs directory
1 - open docs directory
2 - delete stuck doc
3 - restart zealdocs and download the stucked doc again
good luck

**Comment by qqmash** [comment] 2017-12-25 11:01
@trollix, there is no such button (tried also on 0.5 version, 
![screenshot](https://user-images.githubusercontent.com/23568990/34338668-329f76ea-e995-11e7-96d2-b095c3901e9e.png)
). The application needs to be killed manually after a fail downloading docset.
@MoSala7, thanx, but this is not a solution. Re-downloading docset that is over 100mb makes me waste much time.

**Comment by trollixx** [comment] 2018-01-14 23:51
Right now deleting the corrupted/unfinished docsets is the only fix.

There's a known problem (#707) regarding progress not displayed during docset update.

Also #430, #599 and #842 will address this problem.

Closing as a duplicate of all problems and missing features mentioned.

**Closed by trollixx** 2018-01-14 23:51 UTC
Labels: Component: UI/Docset Manager, Type: Defect
