### ISSUE TITLE
crash after downloading finished

### ISSUE THREAD

**Issue by Antisunny** [zealdocs/zeal#828] opened 2017-11-27 06:56 UTC
in the latest Windows 17046. Zeal crashes when downloading and unpacking any docset.

**Comment by MamyRaoby** [comment] 2017-11-27 11:38
After dowloading JavaFX docsets, it stops automatically and then I restart the download, the problem repeats again and again.. :(

**Comment by trollixx** [comment] 2017-12-01 19:41
Duplicate of #788. Simply remove directory for the docset failing to install. It's in the docset storage path.

**Closed by trollixx** 2017-12-01 19:41 UTC
