### ISSUE TITLE
Persisting Docset Modal Window and impersistent docset storage path

### ISSUE THREAD

**Issue by tej-kweku** [zealdocs/zeal#618] opened 2016-10-08 13:01 UTC
I am using Zeal 0.3.0, 32-bit on Windows 8.1 64-bit.
Anytime I open the Docset dialog to download new and update existing docsets, I am unable to close the dialog. I am presented with an error message, "Please wait for all operations to finish" even if I have not issued any download or update actions.  Thus, I cannot continue to view the downloaded docsets as in the snapshot attached
![zeal_error](https://cloud.githubusercontent.com/assets/7029109/19213251/0ae820e4-8d56-11e6-96ad-f0487fbf65be.png)
Also, I made a directory on my secondary harddrive's partition to keep all my docsets (due to storage size issues). Unfortunately, Zeal does not persistently save the path to the docsets hence I have to update the path in the Preferences dialog each time I want to use Zeal. This is similar to the issue #609.
I hope these issues would be resolved

**Comment by trollixx** [comment] 2016-10-08 15:31
First is a duplicate of #608, second of #609. Please do not report two unrelated problems in one ticket.

**Closed by trollixx** 2016-10-08 15:31 UTC
