### ISSUE TITLE
JavaScript Docs rendering error

### ISSUE THREAD

**Issue by dimaln** [zealdocs/zeal#1239] opened 2020-06-15 10:53 UTC
All JS doc pages  return error message:
Content rendering error
An unhandled error occurred in the application. We apologize for the inconvenience!

Env: Windows 10, Zeal v.0.6.1

**Comment by trollixx** [comment] 2020-06-18 03:10
Duplicate of #1155.

**Closed by trollixx** 2020-06-18 03:10 UTC
