### ISSUE TITLE
Unable to Update Custom Feeds

### ISSUE THREAD

**Issue by ferronrsmith** [zealdocs/zeal#482] opened 2016-01-26 08:45 UTC
Due to the implementation if a custom feed is added, it has to be removed and re-added to be updated. Defeats the entire the purpose of document management. If you could provide a way to load in custom feeds like `com.kapeli.json` that would be awesome.

**Comment by trollixx** [comment] 2016-01-29 05:24
Duplicate of #289. I think this is coming soon.

**Closed by trollixx** 2016-01-29 05:24 UTC
Labels: Component: Docset Manager (UI), Resolution: Duplicate, Type: Feature
