### ISSUE TITLE
Support high-DPI screens

### ISSUE THREAD

**Issue by binki** [zealdocs/zeal#111] opened 2014-02-10 15:54 UTC
When viewing documentation in zeal, I cannot figure out how to zoom the documentation in. When reading the same documentation in mozilla versus zeal, I notice that zeal is rendering text with the assumption that my display’s resolution is 96DPI.

When mozilla launches, it reads in the system-wide DPI value and automatically scales its UI and all HTML appropriately. (It would be nice if it supported Windows 8.1 per-monitor DPI, but only IE supports that so far; for now I just restrict my use of mozilla to the monitor that happens to match Windows’s calculated system-wide DPI value).

When zeal launches, it calls [SetProcessDPIAware()](http://msdn.microsoft.com/en-us/library/windows/desktop/ms633543). This function is  not to be confused with the newer/better API [SetProcessDpiAwareness()](http://msdn.microsoft.com/en-us/library/windows/desktop/dn302122); calling `SetProcessDPIAware()` is equivalent to calling `SetProcessDpiAwareness(Process_System_DPI_Aware)`. (Ideally, you/qt will eventually support calling `SetProcessDpiAwareness(Process_Per_Monitor_DPI_Aware)`.) (I am just assuming your application is calling the said function because its behavior is consistent with calling `SetProcessDPIAware()` and I can find that this method is referenced in `platforms/qwindowsdll`.) This means that if the user’s system DPI reflects a very high DPI, such as from a high density monitor (mine is only semi-high density at 120DPI), the users would see text at half-size or smaller and be unable to read it. I mean, if the screen is high density, the user could always use a real-life magnifying glass (and still not be able to see the pixels, isn’t it awesome? :-D) and be able to read the text fine, but this would be quite inconvenient.

As a stop-gap measure, adding in C-+ and C-- zoom (copying more functionality from web browsers) and later fixing your code to support Qt’s DPI support (I really hope that Qt and its webkit control support DPI if it’s calling `SetProcessDPIAware()` on your behalf) is really the only way to go. Maybe someday Qt will add support for Windows 8.1 per-monitor/dynamic DPI and, by using Qt’s current DPI APIs, your app will automamagically work with that?

**Comment by jonohl** [comment] 2015-06-10 09:39
1+, I have a 4k display on 13.3-inches and for me zeal is unusable. Running Ubuntu 15.04 btw.

**Comment by trollixx** [comment] 2015-06-10 20:54
It should be possible to enable high DPI support in Qt starting with version 5.4. There's an [article](http://doc.qt.io/qt-5/highdpi.html) about that in Qt documentation. I don't have a high DPI device, so I have no idea how I could test it. Setting `QT_DEVICE_PIXEL_RATIO` environment variable to `auto` or specific value theoretically should do the trick. If someone could test whether setting `QT_DEVICE_PIXEL_RATIO` works, then I would hard code it in Zeal.

It's also possible to set the minimum font size for the embedded web view in the Zeal settings.

**Comment by sidewinder94** [comment] 2015-06-17 15:35
I can test that for you if you can provide me a compiled test version (Win 8 3200x1800 15.6")

**Comment by trollixx** [comment] 2015-06-18 05:59
@sidewinder94 [CI builds](https://bintray.com/zealdocs/windows-ci/zeal-stable/view) should be the best option for testing.

**Comment by sidewinder94** [comment] 2015-06-18 15:00
Well the, i tested the latest stable build (zeal-stable-0.1.1-9-gfd4f3e2-windows-x86.zip)
The interface was really better.
The default font size for the browser is still too small but thanks to the appearance tab in the options, it can be set at any value.

I would say the problem is solved :)

**Comment by trollixx** [comment] 2015-06-19 07:01
@sidewinder94 Thanks for testing. Did you use `QT_DEVICE_PIXEL_RATIO=auto` or it worked out of the box?

I do see a problem with the tab bar. Tab maximum width is fixed in pixels, so this requires a fix.

**Comment by trollixx** [comment] 2015-06-19 07:09
As per font size in the web view issue, it should be possible to set text size / scaling based on actual DPI. Additional info in [QTBUG-29571](https://bugreports.qt.io/browse/QTBUG-29571) and [this](http://stackoverflow.com/a/27647535/721710) SO answer.

**Comment by sidewinder94** [comment] 2015-06-19 13:33
@trollixx It worked out of the box.

**Comment by FichteFoll** [comment] 2015-06-25 08:58
My DPI scaling is set to 1.25 and I didn't have problems with Zeal 0.1.1 (was displaying just fine). After I downloaded 0.1.1-82-g8a8544f, it rendered the window in the same way (except for margin-left on the seach list view and see also icons; but fonts where the same) and setting `QT_DEVICE_PIXEL_RATIO=auto` didn't do anything different either.

Since it was fine for me before I just assume that this issue never existed for me, but I wanted to mention it anyway.

**Comment by SamyStyle** [comment] 2015-07-09 15:53
+1 I have the same problem, running Windows 8.1 with v0.1.1

Internal laptop screen 3200x1800 @ 13.3inch ( 276.05 PPI) its scaled 150%: but is is presented with 100%, so really tiny:
![ppi276](https://cloud.githubusercontent.com/assets/12493208/8599805/68b3534c-265a-11e5-872e-0d858087cb91.png)

its necessary to have the scaling dependent on the actual monitor. cos often external laptop screens have different DIP scaling. 
This happens on my external scaled 100% screen (1920x1080 @ 24inch):
![external](https://cloud.githubusercontent.com/assets/12493208/8599796/5be62afe-265a-11e5-8a15-091377a282d1.png)

**Comment by trollixx** [comment] 2016-09-30 05:50
I wonder if anyone still experiencing any issues with Zeal on HiDPI screens? Qt should behave quite well nowadays.

**Comment by kjaquier** [comment] 2016-11-01 14:54
Hi. Just discovered and installed Zeal to try out. I also have a display issue on Ubuntu 16.04 with my Dell XPS 13 9350 (3200x1800px with Unity scale set to 2x). I try upgrading to the updated version from the PPA but the issue remains.
![capture du 2016-11-01 15-49-05](https://cloud.githubusercontent.com/assets/3680822/19893890/229c9a96-a04b-11e6-976b-766e55406422.png)

**Comment by robotlovesyou** [comment] 2016-11-12 23:57
@kjaquier Starting zeal using the QT_DEVICE_PIXEL_RATIO=auto environment variable as described further up this thread addresses this issue

**Comment by kjaquier** [comment] 2016-11-16 09:18
@robotlovesyou Thanks. I tried it and it works great.
Though, I had to use `QT_DEVICE_PIXEL_RATIO=2` instead of `auto`, because for some reason `auto` makes everything too big.

**Closed** 2017-02-19 05:10 UTC
Labels: Component: UI, Type: Enhancement

**Comment by trollixx** [comment] 2017-02-19 05:13
The change committed requires Qt 5.6+ to work, our CI is currently building with Qt 5.5.1. I am working on fixing that.
