### ISSUE TITLE
Java SE17 doc, make close the app.

### ISSUE THREAD

**Issue by Nekko-Code** [zealdocs/zeal#1391] opened 2022-05-01 19:36 UTC
when i enter in eny doc (classes, constants, ...) the app crash.

**Comment by Dominiquini** [comment] 2022-05-11 19:19
Happens to me too!

**Comment by AlbaxBM** [comment] 2022-05-26 12:37
I have the same problem!

**Comment by OrtizUriel112** [comment] 2022-06-02 19:23
Me three :(

**Comment by SEEKnight** [comment] 2022-06-15 08:43
me too

**Comment by Binjuan23** [comment] 2022-06-16 10:56
I have the same problem.

**Comment by MarneusAugustusCalgar** [comment] 2022-06-20 05:59
The bug is still unsolved :(

**Comment by Frandella** [comment] 2022-06-26 02:54
It happens with Java SE15 too, i put "ja" in the search bar and it closed
![bug](https://user-images.githubusercontent.com/95258225/175797380-2ae542c9-4b21-4108-bbaf-292f34ad9e3d.png)

**Comment by trollixx** [comment] 2022-07-23 18:03
Duplicate of #868.

**Closed by trollixx** 2022-07-23 18:03 UTC
