### ISSUE TITLE
UI Elements awkwardly sized

### ISSUE THREAD

**Issue by hahuang65** [zealdocs/zeal#909] opened 2018-03-17 01:58 UTC
I'm using i3wm on Arch Linux with a 4K screen. I'm having lots of trouble with the sizing of the UI elements.

I'm wondering if anyone else has experienced this and knows how to work around it. It's not completely unusable but it's very inconvenient and difficult to read.

Some of the UI elements are massive, and some others (especially text) is tiny.

![2018-03-16-184628_3840x2160_scrot](https://user-images.githubusercontent.com/280972/37550521-edfa24d0-294b-11e8-9cef-ee64b9296382.png)
![2018-03-16-185607_3840x2160_scrot](https://user-images.githubusercontent.com/280972/37550522-ee136f30-294b-11e8-99a3-3c293d11c10e.png)
![2018-03-16-185623_3840x2160_scrot](https://user-images.githubusercontent.com/280972/37550523-ee2b2832-294b-11e8-8c22-5f7b605ef8cb.png)
![2018-03-16-185643_3840x2160_scrot](https://user-images.githubusercontent.com/280972/37550525-ee4057fc-294b-11e8-91a9-230b9785c891.png)

**Comment by hahuang65** [comment] 2018-03-17 02:03
I've found the comment about using `QT_AUTO_SCREEN_SCALE_FACTOR=0 zeal` and that makes the UI properly scaled, but ultimately, a little too small to read.

But it does look WAY nicer...
![2018-03-16-190312_3840x2160_scrot](https://user-images.githubusercontent.com/280972/37550567-b5c7447a-294c-11e8-8410-43a0e905cbd5.png)

**Comment by hahuang65** [comment] 2018-03-17 05:43
I may have found the answer, even though I wasn't able to get it installed due to some issues with the packages in the AUR.

Checking out the Arch Wiki's HiDPI page, it suggests the `run_scaled` script:
https://wiki.archlinux.org/index.php?title=HiDPI&oldid=468803#Unsupported_applications

**Comment by trollixx** [comment] 2018-03-18 22:20
Duplicate of #869.

Qt should address this, I don't think there's a good solution from our side. You may want to do a custom build, with scaling disabled, check the referenced ticket.

**Closed by trollixx** 2018-03-18 22:20 UTC
