### ISSUE TITLE
When user disable some doc set, the doc file should not be deleted.

### ISSUE THREAD

**Issue by billxc** [zealdocs/zeal#910] opened 2018-03-19 10:08 UTC
I often select several types of docs set. When I search for some keyword, results of different doc sets appeared. This makes me hard to find the doc I want. 

Sometimes, I need to disable some doc set temporarily. And the only way to disable the doc set is to delete it. When the next time I want to enable it again, I have to download it again. 

It will be helpful if I can just disable the doc set without deleting it from the disk.

Thanks!

**Comment by trollixx** [comment] 2018-03-19 22:50
Duplicate of #77.

**Closed by trollixx** 2018-03-19 22:50 UTC
