### ISSUE TITLE
Search specifically for classes, functions, etc.

### ISSUE THREAD

**Issue by kalekundert** [zealdocs/zeal#1061] opened 2019-01-07 22:41 UTC
It's very possible that I missed something in the documentation, but is there a way to limit a search to a particular entry type?  For example, I often need to find myself needing to look at the API docs for the `Axes` class from `matplotlib`.  Unfortunately, the first ~15 results for `matplotlib:axes` are a bunch of demos: not what I'm looking for.  Since I know in advance that I want the docs for a class, is there any way to limit my search to classes?

Relatedly, in general I'm most interested in class and function entry types.  It'd be nice if there was an option to specify "search-rank bonuses" for different entry types, or even to force certain entry types to the top of the search results.

**Comment by trollixx** [comment] 2019-02-02 04:31
This is a frequent request, but I haven't yet figured out the best way approach such feature.

Duplicate of #795. There's also a proposed implementation in #1038.

**Closed by trollixx** 2019-02-02 04:31 UTC
