### ISSUE TITLE
SSL handshake failed (0.6.1) 

### ISSUE THREAD

**Issue by xFurther** [zealdocs/zeal#1307] opened 2021-01-07 11:29 UTC
I still get this error on Windows 10.

#1088

What can I do to fix this?

![image](https://user-images.githubusercontent.com/6121565/103887838-b277da80-511e-11eb-8cee-fdb8993bcd0f.png)

**Comment by dcunited001** [comment] 2021-03-23 19:23
I'm running into the same problems. There's a redirect from https://go.zealdocs.org/d/com.kapeli/Clojure/latest to https://mumbai.kapeli.com/feeds/Clojure.tgz, which fails on SSL handshake. I think mumbai.kapeli.com's cert has expired.

**Comment by arsenypoga** [comment] 2021-03-24 03:36
Same issue as the above. Redirect that leads to the https://mumbai.kapeli.com seems to have expired certs.

**Comment by arsenypoga** [comment] 2021-03-24 03:44
If you *really* want the working docsets, there is a workaround. [This](https://github.com/Kapeli/feeds) git repo contains the feeds for the docs. What you can do, is copy the raw URL to the feed and import it through `Add Feeds` option under `Tools > Docsets`

**Comment by trollixx** [comment] 2021-03-24 17:37
Duplicate of #1330.

**Closed by trollixx** 2021-03-24 17:37 UTC

**Comment by raulgm00** [comment] 2023-08-04 15:16
> En mi caso, tampoco pude descargar ninguno de los conjuntos de documentos disponibles con Zeal `v0.6.1`instalado desde los repositorios oficiales de Ubuntu 22.04 a través de `sudo apt-get install zeal`. Para intentar resolver este problema, instalé dependencias adicionales:
> 
> ```
> sudo apt-get install extra-cmake-modules libqt5x11extras5-dev libxcb-keysyms1-dev libsqlite3-dev
> ```
> 
> y construí Zeal desde este repositorio usando lo siguiente:
> 
> ```shell
> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=Release ..
> cmake --build . -- -j$(nproc)
> ```
> 
> Sin embargo, el problema persistió. Luego de una mayor investigación, descubrí que el certificado SSL en https://go.zealdocs.org (RedirectServerUrl) había expirado el `Thursday, July 27, 2023 at 1:00:09 AM` . A pesar de esto, el contenido requerido todavía estaba accesible. Para evitar los errores de SSL, escribí el siguiente parche:
> 
> ```diff
> diff --git a/src/libs/ui/docsetsdialog.cpp b/src/libs/ui/docsetsdialog.cpp
> index 5195454..bfab2da 100644
> --- a/src/libs/ui/docsetsdialog.cpp
> +++ b/src/libs/ui/docsetsdialog.cpp
> @@ -675,6 +675,13 @@ bool DocsetsDialog::updatesAvailable() const
>  QNetworkReply *DocsetsDialog::download(const QUrl &url)
>  {
>      QNetworkReply *reply = m_application->download(url);
> +
> +    // Connect to the reply's sslErrors signal to handle SSL errors
> +    connect(reply, &QNetworkReply::sslErrors, [=](const QList<QSslError>& errors){
> +        // Ignore all SSL errors
> +        reply->ignoreSslErrors();
> +    });
> +
>      connect(reply, &QNetworkReply::downloadProgress, this, &DocsetsDialog::downloadProgress);
>      connect(reply, &QNetworkReply::finished, this, &DocsetsDialog::downloadCompleted);
>      m_replies.append(reply);
> ```
> 
> Después de implementar el parche anterior, pude descargar todos los conjuntos de documentos disponibles sin necesidad de URL de fuentes personalizadas. Este enfoque podría resultar útil para otras personas que enfrentan un problema similar.

How is it that you execute or create that file, at what level of the os?

**Comment by raulgm00** [comment] 2023-08-04 16:00
> Ya hice un [PR](https://github.com/zealdocs/zeal/pull/1521) que agrega [x] Ignorar errores de SSL al descargar la configuración en la pestaña Red:
> 
> ![imagen](https://user-images.githubusercontent.com/22120003/258466286-ef3bb0f2-956b-48cd-a386-593c9806e29b.png)
> 
> Puede descargar los artefactos de compilación de este PR [aquí](https://github.com/zealdocs/zeal/actions/runs/5758454460?pr=1521) :
> 
> ![imagen](https://user-images.githubusercontent.com/22120003/258466607-3c78acbf-93e5-4665-bc78-9b31707ab720.png)

Very kind colleague, with this modification that you share, it was possible to download, I appreciate you a lot, you are the best, thanks for sharing, the truth is that I currently need this resource for my students, resources that are scarce and do not have internet, this will make them I've come a long way, thanks for sharing for the future of humanity.
