### ISSUE TITLE
Open Link in a new Window does not work as in previous versions

### ISSUE THREAD

**Issue by genom5** [zealdocs/zeal#875] opened 2018-01-26 08:59 UTC
Selection via context menu.

After mouse click the link is open in the current tab (or window) and
a new empty tab (or window) gets opened

zeal version : 0.5.0
OS: MS Windows

In V 0.4.0 and before it worked without any problems.

**Comment by 14m3** [comment] 2018-01-26 09:25
yeah, I have the same problem. 
zeal version : 0.5.0 portable
OS: Windows10

**Comment by trollixx** [comment] 2018-01-26 10:25
Duplicate of #851.

**Closed by trollixx** 2018-01-26 10:25 UTC
Labels: Component: UI, Resolution: Duplicate, Type: Defect
