### ISSUE TITLE
extended capabilities fuzzy search

### ISSUE THREAD

**Issue by D1mon** [zealdocs/zeal#796] opened 2017-10-10 07:24 UTC
The exact match option is of interest. A lot of superfluous and not exact shows.
[link](https://github.com/junegunn/fzf#search-syntax)

**Comment by trollixx** [comment] 2017-10-10 08:36
Please use English for all issue details and comments.

**Comment by trollixx** [comment] 2017-10-10 09:11
Fuzzy search can be disabled in the settings, but then there's currently a regression bug in how the results are ordered (#791).

Thanks for the link, that's an interesting project.

**Comment by trollixx** [comment] 2018-01-07 15:24
Duplicate of #791, which has been fixed in 0.5.0.

**Closed by trollixx** 2018-01-07 15:24 UTC
