### ISSUE TITLE
Search results on the left don't specify which docset each result comes from

### ISSUE THREAD

**Issue by daveloyall** [zealdocs/zeal#1504] opened 2023-06-01 14:46 UTC
Hello.  Nice application, thank you.

I have all the Java docsets installed.

If I type "runtimeexception" in the search box, I get many results, but I can't tell which one is from the docset "Java SE8".

One way to change this would be to simply change the icon for each of the Java docsets.

Another way to change it would be to display the docset name on the left in the search results.

**Comment by trollixx** [comment] 2023-09-17 18:21
Duplicate of #343. #1032 is also related.

**Closed by trollixx** 2023-09-17 18:21 UTC
