### ISSUE TITLE
The last character of search result can't be displayed

### ISSUE THREAD

**Issue by nuzar** [zealdocs/zeal#572] opened 2016-07-27 11:45 UTC
![load](https://cloud.githubusercontent.com/assets/4602400/17174201/4ff870c4-5432-11e6-8a23-253a8fef4ac3.PNG)
When I search json.load 'd' will not be displayed.
![loads](https://cloud.githubusercontent.com/assets/4602400/17174202/52f96daa-5432-11e6-8ffd-d5536ffff0f2.PNG)
And when search json.loads 's' will not be displayed.
I'm using Zeal 0.2.1 on Windows 10.

**Comment by jybhaha** [comment] 2016-08-01 02:37
I find that， too

**Comment by trollixx** [comment] 2016-08-03 05:16
The truncation should not happen in [CI builds](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view), please try out the latest. Weird font is another problem though...

**Comment by trollixx** [comment] 2016-09-19 02:59
Closing as a duplicate of #262.

**Closed by trollixx** 2016-09-19 02:59 UTC
Labels: Component: UI, Type: Defect
