### ISSUE TITLE
Crashing with SIGSEGV in QNetworkConfiguration::~QNetworkConfiguration()

### ISSUE THREAD

**Issue by abforce** [zealdocs/zeal#671] opened 2016-12-18 12:27 UTC
How to reproduce:

 - Preferences -> Hide to system tray on window close
 - Close the window
 - Click on the icon in tray and choose "Quit"
 - [Occasionally for example when offline] program crashes

Stacktrace is attached.
![screenshot from 2016-12-18 15-54-10](https://cloud.githubusercontent.com/assets/5196179/21293458/aefccb5a-c53a-11e6-8b4f-f2b6ad6ff107.png)

**Comment by trollixx** [comment] 2016-12-18 15:38
I can't reproduce this. What version of Zeal are you using? Any other custom settings?

**Comment by abforce** [comment] 2016-12-19 10:06
Version `0.3.1`. No other custom settings except setting `ctrl + meta + z` as the Zeal hotkey, if it matters.

**Comment by trollixx** [comment] 2016-12-21 07:05
Also please provide information about your distribution and desktop environent.

**Comment by abforce** [comment] 2016-12-23 06:48
I'm using Ubuntu 16.10 (amd64) and Unity 7.5.0 desktop.

**Comment by deronnax** [comment] 2017-03-14 11:47
reproduced many, many times, exact same environnement (Ubuntu 16.10, Unity 7.5, Zeal 0.3.1), same crash location (QNetworkConfiguration destructor)

**Comment by trollixx** [comment] 2017-04-09 03:40
[Seems](https://bugs.launchpad.net/ubuntu/+source/unity8/+bug/1631278) to only affect Ununtu.

**Comment by trollixx** [comment] 2017-04-09 03:45
Aha, according to [LP #1630765](https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1630765) should be fixed with Qt updated to `5.6.1+dfsg-3ubuntu7~2`.

Everyone here who's been running into this crash, please make sure you have the update installed.

**Comment by chriscortopassi** [comment] 2017-07-21 23:23
Could someone please tell me specifically how to update Qt to 5.6.1+dfsg-3ubuntu7~2? e.g. could you supply a terminal log of the command(s)? Thank you

**Comment by chriscortopassi** [comment] 2017-07-21 23:59
I have 6~4 on my machine, and it appears 7~2 doesn't exist

chriscortopassi@A353:~/Downloads$ apt-cache policy qtbase5-dev
qtbase5-dev:
  Installed: 5.6.1+dfsg-3ubuntu6~4
  Candidate: 5.6.1+dfsg-3ubuntu6~4
  Version table:
 *** 5.6.1+dfsg-3ubuntu6~4 500
        500 http://us.archive.ubuntu.com/ubuntu yakkety/main amd64 Packages
        100 /var/lib/dpkg/status
chriscortopassi@A353:~/Downloads$ 
chriscortopassi@A353:~/Downloads$ sudo apt-get install qtbase5-dev=5.6.1+dfsg-3ubuntu7~2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '5.6.1+dfsg-3ubuntu7~2' for 'qtbase5-dev' was not found

**Comment by trollixx** [comment] 2017-10-07 13:40
I don't use Ubuntu, so not sure how that update is supposed to be distributed. Just picked version from the linked ticket, please inquire further support there.

**Closed** 2017-10-07 13:40 UTC
Labels: Component: Core, Resolution: Upstream Problem, Type: Defect
