### ISSUE TITLE
Menu dissapears after second close in Ubuntu 15.04

### ISSUE THREAD

**Issue by hectorcanto** [zealdocs/zeal#412] opened 2015-10-13 16:33 UTC
If I launch Zeal I can see the menu (File, View, Tabs, Help). After I minimize it, when I maximize it again the Menu is missing.

**Comment by trollixx** [comment] 2015-10-17 02:25
It's a bug in Ubuntu. Please mark [LP #1451946](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1451946) as affecting you.

Duplicate of #327.

**Closed by trollixx** 2015-10-17 02:25 UTC
