### ISSUE TITLE
Zeal stoped working when installing laravel docset

### ISSUE THREAD

**Issue by SamiruR** [zealdocs/zeal#799] opened 2017-10-14 20:16 UTC
Im using Zeal 0.4.0 portable version on windows 7 64bit Ent. PC,
I have already installed Angular, bootstrap and Emmet docset in zeal,
but when i try to install laravel , program stopped working at thee 100% install completion.

**Comment by trollixx** [comment] 2017-10-15 17:37
Until #788 is fixed you need to delete `Lavarel.docset` directory from the docset storage path, and then re-download the docset.

**Comment by trollixx** [comment] 2017-10-15 17:38
Duplicate of #788.

**Closed** 2017-10-16 18:39 UTC
Labels: Component: Docset Registry, Resolution: Duplicate, Type: Defect
