### ISSUE TITLE
CSS docsets couldn't working.

### ISSUE THREAD

**Issue by GHNNS** [zealdocs/zeal#1214] opened 2020-04-19 15:32 UTC
I try to reload the page according to the note, even uninstall and reinstall it, but the problem remain.

btw, the docsets in Dash on ipad read normal.

![Snipaste_2020-04-19_23-28-29](https://user-images.githubusercontent.com/20828349/79692118-fd527900-8295-11ea-9eff-c62c5d462d84.png)

**Comment by GHNNS** [comment] 2020-04-19 15:34
btw, the docsets in Dash on ipad read normal.

**Comment by trollixx** [comment] 2020-04-19 16:18
Duplicate of #1155.

**Closed by trollixx** 2020-04-19 16:18 UTC
