### ISSUE TITLE
JavaScript docset content rendering error

### ISSUE THREAD

**Issue by edgars-b** [zealdocs/zeal#1259] opened 2020-07-23 17:28 UTC
![Screenshot_2020-07-23_20-27-24](https://user-images.githubusercontent.com/58686023/88318134-f585f300-cd22-11ea-9621-07b8014ed81d.png)

Linux mint 19.3

**Comment by trollixx** [comment] 2020-07-25 15:55
Duplicate of #1155.

**Closed by trollixx** 2020-07-25 15:55 UTC
