### ISSUE TITLE
Slow cpu-greedy page scrolling

### ISSUE THREAD

**Issue by Yanpas** [zealdocs/zeal#837] opened 2017-12-04 21:55 UTC
I observe it on Windows 10 (x64 msi installer) in almost all doc pages (`python3:bytearray` e.g.). I drag side scroller and move it up-down quickily, one of cpu cores quickly goes 100%.

Cannot reproduce on Arch/KDE.

See also #723

**Comment by trollixx** [comment] 2017-12-05 21:24
It's a problem with (Qt) WebKit, as I can reproduce it outside of Zeal. Reported (sort of) upstream.

CC: @annulen

**Comment by Yanpas** [comment] 2017-12-05 21:27
Are there any plans to switch to oficially supported QWebEngine (Blink)?

**Comment by trollixx** [comment] 2017-12-05 21:34
Nope, all the basic support we had for it has been removed.

Yesterday somebody asked me the same questions on Gitter, and here's my answer:

> Unfortunately, Qt WE had issues with rendering docsets as well. It also didn't support setting custom CSS (no idea if it does now). Plus it created some temporary files in user's appdata directory, and that didn't play nicely with the portable edition. Also there was no support for traversing DOM, which might be needed for certain features.

I also recall Qt WE having different performance issues on Windows. So, there's no clear winner here.

I believe The Qt Company doesn't have enough resources to maintain Qt WE at a decent level, but it's just my personal opinion.

**Comment by trollixx** [comment] 2017-12-08 21:07
According to WebKit developers it's a known problem with Python documentation. See https://bugs.webkit.org/show_bug.cgi?id=180577

There's nothing we can do about it, since we do not generate the docset.

@Kapeli Perhaps you can remove JavaScript that drives the side bar, since the side bar is already cut out in the docset.

**Comment by Kapeli** [comment] 2017-12-08 22:33
I've updated the Python 2 and 3 docsets and they don't include the `sidebar.js` anymore. Let me know if that improves things.

**Comment by trollixx** [comment] 2017-12-08 22:48
@Kapeli Scrolls fine for me, thanks!

@Yanpas Please update the docset, and check.

**Comment by Yanpas** [comment] 2017-12-09 10:12
I've updated, it's the same. It's not python doc problem or any docset's, almost every docset is very slow: Apache, c++ etc. QWebKit should be profiled on windows, I don't know

**Comment by trollixx** [comment] 2018-01-09 08:27
@Yanpas Do you observe any improvements with Zeal 0.5.0?

**Comment by Yanpas** [comment] 2018-01-09 19:23
It's definetely better, but still much slower than any browser. May be closed I think, but qwebkit still needs optimizations

**Comment by annulen** [comment] 2018-01-09 19:30
@Yanpas If you provided us profiling results, we could do something about that.

**Comment by trollixx** [comment] 2018-01-09 22:04
Closing, per above, and as there's nothing to do from Zeal side.

**Closed by trollixx** 2018-01-09 22:04 UTC
Labels: Component: Other/Docsets, Component: UI/Web View, Resolution: Upstream Problem, Type: Defect
