### ISSUE TITLE
Clicking refresh while installing docsets makes status go wrong

### ISSUE THREAD

**Issue by allopislozano** [zealdocs/zeal#974] opened 2018-08-15 10:14 UTC
if you want to add some docsets, you click several ones to start downloading/installing. Some progress bars appear for downloading and installing progress and the closing of the dialog is blocked (which is also inconvenient, would be better if it could be done in the back while browsing documentation). If you click now refresh, the status is gone and all the progress bars are gone, but the dialog is blocked

**Comment by trollixx** [comment] 2018-08-20 03:05
Duplicate of #842. Will be resolved with the new backend.

**Closed by trollixx** 2018-08-20 03:05 UTC
