### ISSUE TITLE
Main page of the "Wordpress" docsets it's broken

### ISSUE THREAD

**Issue by albertomarun** [zealdocs/zeal#1390] opened 2022-04-28 22:42 UTC
Good day, there is a small error in the main page of the Wordpress docsets, I corrected it locally but it would be good to take this correction to all those who have that library, here is the modification in the "Info.plist" file located in "\Zeal\ docsets\WordPress.docset\Contents"

The corrected content is this:

```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
<key>isJavaScriptEnabled</key><true/><key>CFBundleIdentifier</key>
<string>wordpress</string>
<key>CFBundleName</key>
<string>WordPress</string>
<key>DocSetPlatformFamily</key>
<string>wordpress</string><key>DashDocSetBlocksOnlineResources</key><true/><key>DashDocSetFamily</key><string>unsorteddashtoc</string><key>dashIndexFilePath</key><string>codex.wordpress.org/index.html</string>
<key>isDashDocset</key>
<true/></dict>
</plist>
```

**Comment by trollixx** [comment] 2023-04-15 05:56
Duplicate of #1316. This should be fixed in the `main` branch. Please try the latest [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build.

**Closed by trollixx** 2023-04-15 05:56 UTC
