### ISSUE TITLE
Zeal crashes on Debian buster/sid when selecting class in 'Ionic' or 'Typescript' docset

### ISSUE THREAD

**Issue by thesignal** [zealdocs/zeal#753] opened 2017-07-24 19:41 UTC
I tried other docsets, for example CSS, C, C++, HTML5, Python and all seem to work. 

Strangly, my compiled Zeal from source seems to work without crashes.

The output zeal produces after crashing is as follows:
```
(zeal:3167): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(zeal:3167): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(zeal:3167): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Speicherzugriffsfehler

```
It also dumps segfault messages to dmesg:
```
[549753.016482] zeal[30610]: segfault at 18 ip 00007f677a17f080 sp 00007ffe4f41f938 error 4 in libgdk-3.so.0.2200.16[7f677a14a000+ee000]
[550055.695665] zeal[22186]: segfault at 18 ip 00007f8be1e68080 sp 00007fff8ddb5b48 error 4 in libgdk-3.so.0.2200.16[7f8be1e33000+ee000]
[550201.024618] zeal[628]: segfault at 18 ip 00007f8d529f5080 sp 00007ffe3c95c508 error 4 in libgdk-3.so.0.2200.16[7f8d529c0000+ee000]

```

Please see the strace attached.
[zeal.txt](https://github.com/zealdocs/zeal/files/1170986/zeal.txt)

Any suggestions?

**Comment by trollixx** [comment] 2017-08-19 19:20
This might be another Qt WebKit bug. Please check with the [updated Qt WebKit](https://github.com/annulen/webkit).

**Comment by razorMureithi** [comment] 2017-11-15 11:05
i had the same problem with arch Linux, the solution was to go to dockets folder and delete the docket with the problem and just reinstall it a fresh.
my location is `~/.local/share/Zeal/Zeal/docsets`

**Comment by trollixx** [comment] 2017-11-16 00:04
@razorMureithi Thanks for the information. Then this a duplicate of #788, which is fixed in the upcoming 0.5.0.

**Comment by trollixx** [comment] 2017-11-16 00:06
Actually, doesn't seem so. This crash is in the Docsets Dialog.

**Comment by trollixx** [comment] 2017-11-16 00:06
@razorMureithi Do you happen to have the corrupted docset directory?

**Comment by trollixx** [comment] 2018-01-02 21:43
Cannot reproduce.

**Closed by trollixx** 2018-01-02 21:43 UTC
Labels: Platform: Linux, Resolution: Awaiting Response, Type: Defect
