### ISSUE TITLE
"Please wait for all operations to finish."

### ISSUE THREAD

**Issue by drguildo** [zealdocs/zeal#630] opened 2016-10-13 16:32 UTC
I just upgraded to 0.3.0 and proceeded to update all of the docsets I have installed. This seemed to complete but when I hit OK I get a dialog box asking me to wait for all operations to finish.

![image](https://cloud.githubusercontent.com/assets/9282/19357787/034a6bbc-916b-11e6-994c-8e4e1c156b47.png)

**Comment by trollixx** [comment] 2016-10-14 02:16
Duplicate of #608.

**Closed by trollixx** 2016-10-14 02:16 UTC
Labels: Component: Docset Manager, Resolution: Duplicate, Type: Defect
