### ISSUE TITLE
deleting a docset fails

### ISSUE THREAD

**Issue by schlamar** [zealdocs/zeal#249] opened 2015-01-09 14:05 UTC
Selecting to delete a docset gives a dialog message "failed to delete docset". Afterwards, zeal crashes. On restart, the docset is broken, e.g. title is not displayed:

![unbenannt](https://cloud.githubusercontent.com/assets/238652/5680642/71d0417a-9810-11e4-8e7d-08799219806d.PNG)

Zeal: Help > About says 20140215, but actually I downloaded 20141123 ;)
Windows 7 64bit

**Comment by trollixx** [comment] 2015-01-09 17:56
I cannot reproduce the problem. Could you verify it still occurs with the latest build from [here](https://bitbucket.org/jerzykozera/zeal-win32-binary-downloads/downloads)?

**Comment by schlamar** [comment] 2015-01-12 07:28
Seems to be fixed in 20150112054614

**Comment by schlamar** [comment] 2015-01-13 10:13
I've just seen this again on latest build (zeal-github-shippable-20150113094246.zip). Sadly, it's not 100% reproducible... Any idea how to debug this?

**Comment by schlamar** [comment] 2015-01-13 10:46
Ah, I have set my docset directory to docset\ in the directory of zeal.exe. There seems to be same race condition with this configuration.

**Comment by trollixx** [comment] 2015-01-30 06:01
@schlamar, could you test a recent build? I think the problem should be fixed now.

**Comment by schlamar** [comment] 2015-01-30 07:24
I'm still getting something like "failed to delete" and the docSet.dsidx is not getting deleted. Windows explorer can't delete this file, too - due to file in use as long as zeal is open. However, I'm no longer using this configuration so it's not really a priority getting this fixed...

**Comment by schlamar** [comment] 2015-01-30 07:24
Forgot to mention: the crash is fixed :)

**Comment by trollixx** [comment] 2015-01-30 07:29
Oh, that's weird. I thought I fixed that. Do you have d92834e4da89f0bfa2bd948609488d6ebe74b497?

**Comment by schlamar** [comment] 2015-01-30 08:51
Yes, reproducible with zeal-github-shippable-20150130074659.zip

![unbenannt](https://cloud.githubusercontent.com/assets/238652/5973175/8d1075f8-a865-11e4-9e1b-f0643f5b0d8e.PNG)

**Comment by trollixx** [comment] 2015-01-31 23:55
I've tested on Windows XP and Windows 8.1 without any success in reproducing this issue. I have no idea why SQLite database stays open...

**Comment by trollixx** [comment] 2015-02-10 02:43
@schlamar, I've changed some database related stuff. Zeal should now properly close all connections and unlock databases. Could you check if docset removal still fails for you?

**Comment by trollixx** [comment] 2015-02-21 00:17
Closing due to lack of feedback. Please reopen if the issue still occurs.

**Closed by trollixx** 2015-02-21 00:17 UTC
Labels: bug, needs feedback
