### ISSUE TITLE
crash with 0.6.1

### ISSUE THREAD

**Issue by teto** [zealdocs/zeal#1070] opened 2019-01-22 02:12 UTC
When running zeal on nixos-unstable, I get this kind of crash:
```
#0  0x0000000000466980 in QMap<QString, int>::QMap(QMap<QString, int> const&) ()
#1  0x000000000045fe9d in Zeal::Registry::Docset::symbolCounts() const ()
#2  0x00000000004798ca in Zeal::Registry::ListModel::addDocset(QString const&) ()
#3  0x00007f35eff76372 in QObject::event(QEvent*) () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Core.so.5
#4  0x00007f35f407602c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Widgets.so.5
#5  0x00007f35f407d5df in QApplication::notify(QObject*, QEvent*) () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Widgets.so.5
#6  0x00007f35eff46608 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Core.so.5
#7  0x00007f35eff4914d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Core.so.5
#8  0x00007f35effa1113 in ?? () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Core.so.5
#9  0x00007f35e98d0f47 in g_main_context_dispatch () from /nix/store/nndjz8l466v2i8rjcc339qalf77gichr-glib-2.56.0/lib/libglib-2.0.so.0
#10 0x00007f35e98d1180 in g_main_context_iterate.isra () from /nix/store/nndjz8l466v2i8rjcc339qalf77gichr-glib-2.56.0/lib/libglib-2.0.so.0
#11 0x00007f35e98d120c in g_main_context_iteration () from /nix/store/nndjz8l466v2i8rjcc339qalf77gichr-glib-2.56.0/lib/libglib-2.0.so.0
#12 0x00007f35effa073f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Core.so.5
#13 0x00007f35db879461 in ?? () from /nix/store/bsq1anhb5fj65msz5dy03fy4ijqqh50v-qtbase-5.11.1-bin/lib/qt-5.11/plugins/platforms/../../../../../24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5XcbQpa.so.5
#14 0x00007f35eff4493a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Core.so.5
#15 0x00007f35eff4de00 in QCoreApplication::exec() () from /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/lib/libQt5Core.so.5
#16 0x0000000000423d64 in main ()
```

**Comment by trollixx** [comment] 2019-01-22 06:53
Looks like a corrupted docset. Can you move docset folders one by one from the docset storage path (can be found in settings), and see which one crashes the app? Redownloading the docset should fix that, but first please compress and upload the corrupted version here.

**Comment by teto** [comment] 2019-01-22 07:10
not sure what happened, I moved the C.docset out of the folder, I launched zeal and it worked fine. So I put the C.docset back and it works fine :/ is there some kind of caching in zeal ?

**Comment by trollixx** [comment] 2019-01-23 03:06
No caching, moving the docset folder back should have triggered the crashing again.

**Comment by trollixx** [comment] 2019-01-27 02:45
Closing, as I cannot reproduce this.

**Closed by trollixx** 2019-01-27 02:45 UTC
Labels: Resolution: Unable To Reproduce, scope/registry, type/defect

**Comment by teto** [comment] 2019-01-28 08:31
seems like it's random and not peculiar to a docset since this morning it crashed during startup 3 or 4 times, everytime loading more docsets until it worked. On rebooting zeal though, zeal crashed again.
My docsets are on an external drive.

**Comment by trollixx** [comment] 2019-01-28 15:16
No reliable way to reproduce the crash? Is it always the same stack trace?
