### ISSUE TITLE
When opening HTML, CSS, JS documents, css cannot be loaded and styles are lost

### ISSUE THREAD

**Issue by shwb123** [zealdocs/zeal#1415] opened 2022-07-22 09:10 UTC
Hello, when I use zeal to view HTML, JS and CSS documents, the page styles are lost and the css cannot be loaded.

**Comment by trollixx** [comment] 2022-07-23 17:33
Duplicate of #1155.

**Closed by trollixx** 2022-07-23 17:33 UTC

**Comment by asterson** [comment] 2023-02-08 07:27
It is not the same problem as #1155.
This problem is "The page styles are lost and the css cannot be loaded"，NOT a normal page showing "Content rendering error".
And there is no folder named “build”. We can't  remove files like
CSS.docset\Contents\Resources\Documents\developer.mozilla.org\static\build\js\react-main.ddbbd86b0685.js

![zealcssmissingproblem](https://user-images.githubusercontent.com/30658881/217461802-0823ba96-2281-40dc-86a9-5e01bb8544fc.png)
