### ISSUE TITLE
Enhancement request: Scoped find

### ISSUE THREAD

**Issue by dvorka** [zealdocs/zeal#638] opened 2016-10-20 08:41 UTC
It would be useful to scope `find` based on the position in the left menu - for instance search for `string` while in C++ documentation doesn't return results from Java documentation.

**Comment by trollixx** [comment] 2016-10-27 04:09
`cpp:string`?

**Comment by dvorka** [comment] 2016-10-27 08:31
This is exactly what I was looking for! Perhaps it would be helpful to give search text line a tooltip. Thank you!

**Comment by abforce** [comment] 2016-11-09 19:25
@trollixx Yes. `cpp:string` does work but how about `OpenCV C++`? I tried `opencv:<keywords>` and It doesn't work. Wouldn't it better to confine the search in the selected topic in the left panel? It's more user-friendly I think.

**Comment by trollixx** [comment] 2016-11-16 09:03
@abforce `OpenCV C++` uses `cvcpp` keyword, but that's hard to guess. I'll update the docset manager to display keywords for each docset, also the current keyword autocomplete is pretty much useless, as it doesn't show all available options.

**Comment by trollixx** [comment] 2017-04-09 04:01
Basically duplicate of #77.

**Closed by trollixx** 2017-04-09 04:01 UTC
Labels: Component: Docset Registry, Resolution: Duplicate, Type: Enhancement

**Comment by trollixx** [comment] 2017-04-09 04:07
Marking as a duplicate of #716.
