### ISSUE TITLE
Java closes automatically

### ISSUE THREAD

**Issue by jony-glz** [zealdocs/zeal#1527] opened 2023-09-02 03:40 UTC
I try to open the documentation from Java SE-19 (with any Java documentation), and the program closes automatically. I use Windows 11 and Zeal 0.6.1

**Comment by trollixx** [comment] 2023-09-08 03:54
Duplicate of #868. Please try latest [CI builds](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml). Binary artifacts are attached to each build.

**Closed by trollixx** 2023-09-08 03:54 UTC
