### ISSUE TITLE
Ruby2 - Clicking on left pane method/class has no effect on right pane

### ISSUE THREAD

**Issue by qwebek** [zealdocs/zeal#733] opened 2017-05-28 13:02 UTC
Steps to reproduce:
---

1. Install Zeal 0.3.1
2. Add Ruby2 pack
3. Search for some class
4. Click or doubleckick on some method of class on left pane

Actual behavior:
---

- Right pane is refreshed but focus doesn't go to selected method

Expected behavior:
---

- On right pane focus goes to selected method or class

**Comment by clfsoft** [comment] 2017-06-13 09:47
try the snapshot build . it works for me
https://bintray.com/zealdocs/windows-ci

**Comment by trollixx** [comment] 2017-06-13 21:49
Duplicate of #641, please wait for 0.4.0, or use a recent CI build from the link above.

**Closed by trollixx** 2017-06-13 21:49 UTC
