### ISSUE TITLE
Bug with 0.7

### ISSUE THREAD

**Issue by lordgodgiven** [zealdocs/zeal#1604] opened 2024-03-10 13:19 UTC
I installed the latest version of zeal, but after downloading the documentation, once I closed and relaunched the application, the downloaded documentation was no longer available, so I had to install version 0.61.

**Comment by trollixx** [comment] 2024-03-23 18:04
Duplicate of #1559. It's fixed in the upcoming v0.7.1.

**Closed by trollixx** 2024-03-23 18:04 UTC
