### ISSUE TITLE
ability to temporarily disable docsets from being searched

### ISSUE THREAD

**Issue by edgimar** [zealdocs/zeal#188] opened 2014-08-08 20:09 UTC
On the main zeal tree-view, there should be something like checkboxes connected with each docset, or it should be possible to right-click on a docset and select "disable searching" from a context menu.  Doing so will make it so that searches only return results for non-disabled docsets (but it should still be possible to *browse* the documentation of search-disabled docsets).  When search is disabled for a particular docset, the tree-view root node could be a different color to indicate this.  This overall idea is hinted at in issue #77, but not directly addressed by it.

**Comment by kmoppel** [comment] 2015-01-19 12:33
+1

**Comment by trollixx** [comment] 2015-02-09 09:23
I consider this a duplicate of #77. With docset groups implemented, docsets that are not in an active group will not be searched.

**Closed by trollixx** 2015-02-09 09:23 UTC
