### ISSUE TITLE
Zeal 0.7.0 always asking for updating all the docsets

### ISSUE THREAD

**Issue by Carsampa** [zealdocs/zeal#1580] opened 2023-11-27 17:00 UTC
Hi

Zeal 0.7.0 (tested in Windows) is always asking for updating all docsets after refreshing their list.

It seems that's because it is not storing the "revision" field line in files meta.json after each docsets installation. This way we never know when some docset really needs to be updated.

**Comment by igsol** [comment] 2023-11-29 00:33
The same in Linux. Several docsets always labeled with "Update available" despite they were updated indeed.
![image](https://github.com/zealdocs/zeal/assets/14091049/a4325c23-825b-419e-9244-8d5fe4e15f5e)

**Comment by wdscxsj** [comment] 2023-12-01 04:20
Duplicate of #1559 and already fixed. I wish a new release just for this fix could be published, because the updates are piling up quickly.

**Comment by trollixx** [comment] 2024-03-23 18:05
Duplicate of https://github.com/zealdocs/zeal/issues/1559. It's fixed in the upcoming v0.7.1.

**Closed by trollixx** 2024-03-23 18:05 UTC
