### ISSUE TITLE
Add 'checkbox' beside docset to query specifically

### ISSUE THREAD

**Issue by zbandhan** [zealdocs/zeal#695] opened 2017-02-24 10:34 UTC
Sometimes, we need to search only a specific docset other than search all docsets together. So plz consider to add query filtering checkboxes beside every docset.
Thank to zeal team.

**Comment by trollixx** [comment] 2017-02-25 00:45
Duplicate of #77, hopefully [soon](http://wow.gamepedia.com/Soon).

**Closed by trollixx** 2017-02-25 00:45 UTC
