### ISSUE TITLE
window 11 闪退

### ISSUE THREAD

**Issue by hatface** [zealdocs/zeal#1666] opened 2024-11-04 11:45 UTC
windows 11环境下，zeal-0.7.2-windows-x64 版本，闪退

**Comment by trollixx** [comment] 2024-11-04 13:30
English? I have not learned Chinese yet :)

**Comment by Kakueeen** [comment] 2024-11-05 02:14
The same issue #1662

**Comment by trollixx** [comment] 2024-11-05 02:53
Duplicate of #1658.

**Closed by trollixx** 2024-11-05 02:53 UTC
Labels: resolution/duplicate, type/defect, scope/packaging, platform/windows
