### ISSUE TITLE
Crash on download of dot net framework crashes

### ISSUE THREAD

**Issue by ticviking** [zealdocs/zeal#210] opened 2014-10-14 19:28 UTC
When I try to download this docset the app crashes. 

I'll try build it locally and debug later today.

**Comment by trollixx** [comment] 2015-02-06 07:07
Is it still reproducible with the latest Zeal builds?

**Comment by trollixx** [comment] 2015-05-15 23:48
It's been quite a while since the last response. Closing for now, but, please, comment here in case the problem still occurs, and I'll reopen the issue.

**Closed by trollixx** 2015-05-15 23:48 UTC
Labels: needs feedback
