### ISSUE TITLE
Zeal stops running when there is an update

### ISSUE THREAD

**Issue by cmalard** [zealdocs/zeal#777] opened 2017-09-11 18:17 UTC
Seen on 0.3.1, Zeal immediately closes itself after the popup asking to update.
It should continue to run.

Cf. https://github.com/zealdocs/zeal/issues/772#issuecomment-328247967

**Comment by trollixx** [comment] 2017-09-14 07:02
Duplicate of #637.

**Closed by trollixx** 2017-09-14 07:02 UTC
Labels: Platform: Linux, Type: Defect
