### ISSUE TITLE
Be able to install a specific version of a docset

### ISSUE THREAD

**Issue by daveslab** [zealdocs/zeal#873] opened 2018-01-20 10:55 UTC
Is it possible or would it be possible to add a feature whereby one could install not just the latest version of a docset but also a **specific** version? Use case: I work on a project that uses a slightly outdated version of Django and Python and several others packages. It would be great to able to download just the versions of their docsets that I want.

Sidenote: it might be nice to be able to see which version of the docset I have in the UI without needing to look at the `meta.json` file.

**Comment by trollixx** [comment] 2018-01-20 11:10
Support for multiple versions is not there yet. Duplicate of #208.

**Closed by trollixx** 2018-01-20 11:10 UTC
