### ISSUE TITLE
Can't distinguish multiple results

### ISSUE THREAD

**Issue by Rhywun** [zealdocs/zeal#896] opened 2018-02-27 22:11 UTC
When I search for a term that has multiple results, I can't tell them apart unless I click every single one to get the one I'm looking for.

Example: 
1. Search for `haskell:elemIndex`
2. Results include 11 exact matches but the UI does not indicate which module each match is from

Wish:
- Results list should include the module/namespace (or more generically, the "group") that each match is located inside

v0.5.0

**Comment by trollixx** [comment] 2018-03-02 17:03
This has been reported before, but at the moment I don't have a good solution to address this.

Duplicate of #343.

**Closed by trollixx** 2018-03-02 17:03 UTC
