### ISSUE TITLE
“Open in new window” not working like before anymore

### ISSUE THREAD

**Issue by Hibou57** [zealdocs/zeal#862] opened 2018-01-07 15:04 UTC
Running Zeal 0.5.0, after a recent update I believe, the contextual menu “Open in new window” now has a strange behaviour. Before, it was opening the link in a new tab, now it opens a new tab with the Zeal welcome page and opens the expected link in the original tab where the contextual menu was opened.

**Comment by trollixx** [comment] 2018-01-07 15:15
Duplicate of #851.

**Closed by trollixx** 2018-01-07 15:15 UTC
Labels: Component: UI/Web View, Resolution: Duplicate, Type: Defect
