### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by qiushics** [zealdocs/zeal#1023] opened 2018-10-31 09:09 UTC
Previously, there was lovelydocs, but now it's discontinued.
Does zeal supports android? If so, how to compile it?

**Comment by trollixx** [comment] 2018-11-04 04:04
Duplicate of #454 .

I know that LovelyDocs vanished from the Google Play. I was in contact with the developer (@mario) a while ago, and he wanted to continue the work on the app, but then I was unable to reach him after LovelyDocs disappeared.

I don't have near term plans to work on this, but there were people in #454 looking for collaborators to work on Zeal for Android.

**Closed by trollixx** 2018-11-04 04:04 UTC
