### ISSUE TITLE
Is there supposed to be advertisements in zeal?

### ISSUE THREAD

**Issue by miss-looptux** [zealdocs/zeal#1201] opened 2020-03-11 18:37 UTC
I want to know to make sure I'm not infected with an adware
thanks.

**Comment by trollixx** [comment] 2020-03-14 05:10
The ad has been deleted in the master branch, will be part of the next release.

Duplicate of #779.

**Closed by trollixx** 2020-03-14 05:10 UTC

**Comment by trollixx** [comment] 2020-03-14 05:11
I misread the question, if you are seeing ads from Carbon, those are not adware. You can also disable them in settings.

**Comment by miss-looptux** [comment] 2020-03-15 23:43
i figured it out, this can be closed
