### ISSUE TITLE
Querying Results show imcompleted

### ISSUE THREAD

**Issue by showbye** [zealdocs/zeal#262] opened 2015-01-26 13:39 UTC
Search "printf" for example, the returning items show partly like "print" and 'f' is invisible,just in windows version.
![default](https://cloud.githubusercontent.com/assets/1239362/5900373/42b94bac-a5a3-11e4-9c1c-bf1a0133ee25.PNG)
It seems happened in every windows realease version.

**Comment by trollixx** [comment] 2015-05-20 04:41
Does it still occur with more recent Zeal versions? I cannot reproduce the bug.

**Comment by showbye** [comment] 2015-05-22 19:20
Problem still in the latest build .
Changing '2' to a big number in file searchitemdelegate.cpp 、line 44 seems better.

line 44:     rect.adjust(margin, 0, 2, 0); // +2px for bold text

**Comment by trollixx** [comment] 2016-09-18 23:57
I think this is fixed by 6c2401da6157cdadf9a2844a25ee355c98b13f22. Cannot reproduce anymore.

**Closed by trollixx** 2016-09-18 23:57 UTC
Labels: Component: UI, Platform: Windows, Resolution: Fixed, Type: Defect
