### ISSUE TITLE
Can't choose search result if sent via (PyCharm) plugin

### ISSUE THREAD

**Issue by lusitania** [zealdocs/zeal#441] opened 2015-11-26 08:09 UTC
Hi

When searching for a word in PyCharm, i.e. `FROM` in a Dockerfile, I'm correctly being sent to Zeal. The first result however is from Python's include statement `from module include name`. Only the second result is about Docker but I can't switch to any other result except for sending Zeal into background and back.

Tab/Shift-Tab should have cycled focus through the different panes. Please add those shortcuts.

Best

**Comment by trollixx** [comment] 2016-01-20 03:02
Looks like a focus issue.

Regarding search results, the IDE plugin should tell Zeal to limit the search scope to Docker docset, but that's up the plugin to pass the correct prefix.

**Comment by trollixx** [comment] 2016-01-20 05:21
Might be the same problem as #440.

**Comment by lusitania** [comment] 2016-01-20 12:23
I've [asked](https://github.com/gdelmas/IntelliJDashPlugin/issues/49) @gdelmas to look into the contextual search issue.

**Comment by trollixx** [comment] 2016-01-20 12:27
Great, thanks! I'll look the into focus issue shortly.

**Comment by trollixx** [comment] 2017-10-05 11:58
Duplicate of #440.

Regarding <kbd>Tab</kbd>/<kbd>Shift</kbd>+<kbd>Tab</kbd>, see #401. Most likely it will be <kbd>F6</kbd>, but not sure yet.

**Closed by trollixx** 2017-10-05 11:58 UTC
Labels: Component: Plugin Support, Component: UI, Type: Defect
