### ISSUE TITLE
If docs for multiple versions (e.g. Python 2 and 3) are installed, telling them is impossible

### ISSUE THREAD

**Issue by salmiakki** [zealdocs/zeal#476] opened 2016-01-19 04:32 UTC
I have both Python 2 and 3 docsets installed. I need both. The problem is when I search for something that is present in both, it's impossible to tell which version I'm looking at. See screenshot:

![2016-01-19 07_27_42-zeal](https://cloud.githubusercontent.com/assets/4760420/12409764/32ed1538-be7e-11e5-8015-c082c71496df.png)

Half of those correspond to 2, half to 3. It would be nice to know which search result corresponds to which version. This problem applies to other docsets as well.

* * *

On an unrelated note, what's the deal with those last letters in the search result list?

**Comment by cupen** [comment] 2016-01-19 06:31
you may search for something by a prefix which is the docset's name.
e.g.:
Python2 is your python2 docset's name.
type `Python 2:functools` you will got this.

![image](https://cloud.githubusercontent.com/assets/1221615/12410782/5adc99c6-beb3-11e5-857b-6c5731defb2e.png)

**Comment by drognanar** [comment] 2016-01-19 06:41
This seems to be a duplicate of #343.
Unfortunately for now there is no way to tell the versions apart. Keep in mind that to search for python 2 you need to include a space (`python 2:functools` and not `python2:functools`).

Regarding the unrelated note the deal with the last letters is a known rendering issue and there is an open PR fixing it.

**Comment by trollixx** [comment] 2016-01-20 02:53
Closing as a duplicate. Please follow #343 for updates.

**Closed by trollixx** 2016-01-20 02:53 UTC
Labels: duplicate
