### ISSUE TITLE
Feature proposal: better support for resumable download of docsets

### ISSUE THREAD

**Issue by wdscxsj** [zealdocs/zeal#1016] opened 2018-10-21 04:25 UTC
Not everyone is lucky enough to download a large docset continuously. Let's suppose someone living behind a [wall](https://en.wikipedia.org/wiki/Great_Firewall) is updating the Android and JavaScript docsets via a VPN. It's no unusual to see the download gets interrupted.

Say the progress bar reaches 72% when broken. The wallman wishes to continue from 70% or so, but he just gets 36%! And the download is interrupted more frequently! After several attempts in vain, he enters a state of pure relief...

In this thought experiment Zeal is not to blame. But if it could resume the download better, not just from the half way, many wallmans will be deeply grateful.

**Comment by trollixx** [comment] 2018-10-24 03:50
Duplicate of #430.

**Closed by trollixx** 2018-10-24 03:50 UTC
