### ISSUE TITLE
Zeal exited abnormally after loading docs

### ISSUE THREAD

**Issue by dongzhaolee** [zealdocs/zeal#1512] opened 2023-07-06 09:40 UTC
I imported the docsets successfully. 
However, when I try to open the docs for Java SE15 or later versions, such as Java SE18 or Java SE19, Zeal exits abnormally. I have encountered this bug on **all versions above Java SE14**

**Comment by trollixx** [comment] 2023-08-06 16:46
Duplicate of #868.

Until v0.7.0 is released, please build Zeal from `main` or give [CI build](https://github.com/zealdocs/zeal/actions/workflows/build-check.yml) a try.

**Closed by trollixx** 2023-08-06 16:46 UTC
Labels: resolution/duplicate, type/defect, scope/ui/webview
