### ISSUE TITLE
Monospace font size cannot be changed

### ISSUE THREAD

**Issue by cweiske** [zealdocs/zeal#984] opened 2018-09-03 22:26 UTC
I'm using Zeal 0.6.0 and am trying to change the monospace font size on Edit -> Preferences -> Content -> Monospace -> Size.

Whatever font size I select, after "OK"ing and re-opening the settings dialogue the "9" size is back.

**Comment by trollixx** [comment] 2018-09-06 04:06
Duplicate of #903, which has been fixed in `master`. I'll try to release 0.6.1 over the weekend.

**Closed by trollixx** 2018-09-06 04:06 UTC
