### ISSUE TITLE
Problems for plugins using the query command line parameter in v0.3.0

### ISSUE THREAD

**Issue by ianchanning** [zealdocs/zeal#611] opened 2016-10-06 07:37 UTC
As noted in the v0.3.0 release notes:

> - Dropped support `--query` command line parameter

This breaks the Sublime Text Zeal plugin that opens Zeal with a particular command. I assume it will break almost all 3rd party plugins that want to interact with Zeal.

What should the plugins use instead?

**Comment by trollixx** [comment] 2016-10-08 15:23
Duplicate of #610. See that ticket for details.

**Closed by trollixx** 2016-10-08 15:23 UTC
Labels: Component: Plugin Support, Resolution: Duplicate, Type: Defect
